//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFC_EN.rc
//
#define IDOK2                           3
#define IDC_BTN_LOAD                    3
#define IDOK3                           4
#define IDC_BTN_SAVEFILE                4
#define IDOK4                           5
#define IDC_BTN_READFILIE               5
#define IDD_PIN_PR                      9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STATUS_SEND                 101
#define IDS_STATUS_RECV                 102
#define IDS_STATUS_ERR                  103
#define IDD_GODALOGIN_DIALOG            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_OUTPUT_WND                  105
#define IDS_ECHOCURVE                   106
#define IDS_BUILD_TAB                   107
#define IDS_DEBUG_TAB                   108
#define IDS_FIND_TAB                    109
#define IDB_WRITESMALL                  110
#define IDS_LOCALLOGIN                  110
#define IDB_WRITELARGE                  111
#define IDS_RIBBON_LOAD                 111
#define IDB_MAIN                        112
#define IDS_RIBBON_BASIC                112
#define IDB_BUTTONS                     113
#define IDS_RIBBON_BASIC_LEVEL          113
#define IDB_FILELARGE                   114
#define IDS_RIBBON_BASIC_APPLICATION    114
#define IDB_FILESMALL                   115
#define IDS_RIBBON_CURRENTOUTPUT        115
#define IDS_RIBBON_RESET                116
#define IDS_RIBBON_FALSEECHO            117
#define IDS_RIBBON_PIN                  118
#define IDR_POPUP_EDIT                  119
#define IDS_RIBBON_OTHER                119
#define ID_STATUSBAR_SEND               120
#define IDS_RIBBON_ADVANCED1            120
#define ID_STATUSBAR_RECV               121
#define IDS_RIBBON_ADVANCED2            121
#define IDS_RIBBON_CONNECTION           122
#define IDS_RIBBON_DEVICEOP             123
#define IDS_RIBBON_DEVICESETTINGS       124
#define IDS_RIBBON_USER                 125
#define IDS_RIBBON_SOFTWARESETTINGS     126
#define IDS_RIBBON_LANGUAGE             127
#define IDS_OUTPUT_SIMULATE             128
#define IDR_MAINFRAME_256               129
#define IDS_OUTPUT_TREND                129
#define IDR_MFCTYPE                     130
#define IDS_OUTPUT_ECHOCURVE            130
#define IDS_OUTPUT_OUTPUTMAPPING        131
#define IDS_OUTPUT_ECHODATA             132
#define IDR_MAINFRAME                   133
#define IDS_PERCENT                     134
#define IDS_MAPPINGPERCENT              135
#define IDS_ECHODATA_NUMBER             136
#define IDS_ECHODATA_DISTANCE           137
#define IDS_ECHODATA_AMPLITUDE          138
#define IDS_ECHODATA_WIDTH              139
#define IDS_ECHODATA_POSSIBILITY        140
#define IDS_RIBBON_RECONNECT            141
#define IDS_RIBBON_CHANGERUSER          142
#define IDS_RIBBON_USERMANAGEMENT       143
#define IDS_MSG_LOGINERR                144
#define IDS_SENSORDONOTHING             145
#define IDS_MSG_CONNECTERR              146
#define IDS_DEVSTAT0                    147
#define IDS_DEVSTAT1                    148
#define IDS_SENSOROK                    149
#define ID_VIEW_PropertiesWndPR         150
#define IDS_MSG_RESETCONFIRM            150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDS_MSG_ILLEGALNUM              151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define IDS_MSG_ECHOLABEL               152
#define ID_PROPERTIES2                  153
#define IDS_MSG_INPUTPW                 153
#define ID_EXPAND_ALL                   154
#define IDS_MSG_CONFIRMPW               154
#define IDS_MSG_CONFIRMERR              155
#define IDD_LEVEL_ADJUSTMENT            156
#define IDD_LEVEL_ADJUSTMENT_PR         156
#define IDS_MSG_INPUTORGPW              156
#define IDS_MSG_PWERR                   157
#define IDS_PROPERTIES_WND              158
#define IDS_MSG_INPUTNULLHIGHT          159
#define IDS_ONLINE                      160
#define IDS_OFFLINE                     161
#define IDD_USERMANAGE                  161
#define IDS_DEVICESTAT_WND              162
#define IDS_SAVEOK                      163
#define IDS_SAVEFAIL                    164
#define IDS_MSG_CONFIRMLEARN            165
#define IDS_MSG_CONFIRMDEL              166
#define IDI_PROPERTIES_WND              167
#define IDS_MSG_COMERR                  167
#define IDI_PROPERTIES_WND_HC           168
#define IDS_STARTSIM                    168
#define IDS_DEVICENUM                   169
#define IDS_STOPSIM                     170
#define IDS_POINTNUMBER                 171
#define IDS_GRTITLE                     172
#define IDS_PRTITLE                     173
#define IDS_TUTITLE                     174
#define IDS_SUTITLE                     175
#define IDS_MAPGENMSG                   176
#define IDS_MAPPINGWARN1                177
#define IDS_FLOWERR                     178
#define IDS_USERTYPEFACTORY             179
#define IDS_USERTYPEADVANCED            180
#define IDS_USERTYPENORMAL              181
#define IDS_PASSWORDNOTNULL             182
#define IDR_PROPERTIES                  183
#define IDS_USERNAMENOTNULL             183
#define IDB_PROPERTIES_HC               184
#define IDS_USERNOTEXIST                184
#define IDS_SELECTUSERTYPE              185
#define IDS_SELECTAUSER                 186
#define IDD_MAPPINGEDIT                 187
#define IDS_USERNAME                    187
#define IDD_USERPIN                     188
#define IDS_USERTYPE                    188
#define IDS_USERALREADYEXIST            189
#define IDD_ADVANCEDSETUP               190
#define IDD_ADVANCEDSETUP2_PR           190
#define IDS_DEVICEOP_REFRESH            190
#define IDS_STARTRELAYTEST              191
#define IDD_APPLICATION                 192
#define IDD_APPLICATION_PR              192
#define IDS_STOPRELAYTEST               192
#define IDS_CLOSERELAY                  193
#define IDD_LINEARIZATION               194
#define IDD_LINEARIZATION_PR            194
#define IDS_OPENRELAY                   194
#define IDD_SIMULATE_PR                 196
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDD_LINEDIT_FLOW                203
#define IDD_OTHERSETTINGS               204
#define IDD_OTHERSETTINGS_PR            204
#define IDD_DAMPING                     207
#define IDD_DAMPING_PR                  207
#define IDD_DISPLAY                     208
#define IDD_DISPLAY_PR                  208
#define IDD_DIAGNOSIS                   209
#define IDD_DIAGNOSIS_PR                209
#define ID_VIEW_APPLOOK_WIN_2000        210
#define IDD_CURRENT                     210
#define IDD_CURRENTOUTPUT_PR            210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define IDD_ADVANCEDSETUP2              212
#define IDD_ADVANCEDSETUP3_PR           212
#define IDD_ADVANCEDSETUP1_PR           212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define IDD_RESET                       213
#define IDD_RESET_PR                    213
#define ID_VIEW_APPLOOK_VS_2005         214
#define IDD_FALSEECHO_PR                214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define IDD_SERVICE                     217
#define IDD_SERVICEOTHER_PR             217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDD_CALIBRATION                 254
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EDIT_MENU                   306
#define ID_STATUSBAR_ERR                310
#define IDD_ECHOCURVE                   311
#define IDD_ECHOCURVE_PR                311
#define ID_VIEW_OutputWndPR             312
#define IDS_RIBBON_BASIC_DAMPING        312
#define IDD_TREND_PR                    312
#define IDR_OUTPUT_POPUP                313
#define IDS_RIBBON_BASIC_LINEARIZATION  313
#define IDR_MENU_BASIC                  313
#define IDD_OUTPUTMAPPING_PR            313
#define ID_WND_OUTPUT                   314
#define IDS_RIBBON_BASIC_OTHER          314
#define IDR_MENU_DISPLAY                314
#define IDD_ECHODATA_PR                 314
#define IDS_RIBBON_DISPLAY              315
#define ID_FILE_LOAD                    315
#define IDR_MENU_DIAGNOSIS              315
#define IDS_RIBBON_DIAGNOSIS            316
#define ID_BASIC_SHADOW                 316
#define IDR_MENU_SERVICE                316
#define IDS_RIBBON_SERVICE              317
#define IDR_MENU_ADVANCED               317
#define IDS_RIBBON_ADVANCED             318
#define IDS_RIBBON_INFO                 319
#define IDR_MENU_DEVICEOP               319
#define IDS_SHADOW_RIGION               320
#define IDS_MEASUREMENT_RANGE           321
#define IDS_MAX_ADJUSTMENT              322
#define IDS_MIN_ADJUSTMENT              323
#define IDS_DEVSTAT2                    324
#define IDD_PROGRESSDLG                 325
#define IDS_DEVSTAT3                    325
#define IDS_DEVSTAT4                    326
#define IDD_INPUT                       326
#define IDS_DEVSTAT5                    327
#define ID_WND_DEVICESTAT               327
#define IDS_DEVSTAT6                    328
#define IDS_DEVSTAT7                    329
#define IDD_CURRENTOUTPUT_GR            330
#define IDD_DAMPING_GR                  331
#define IDD_DIAGNOSIS_GR                332
#define IDD_DISPLAY_GR                  333
#define IDD_LEVEL_ADJUSTMENT_GR         334
#define IDD_DEVICESTAT                  337
#define IDD_LEVEL_ADJUSTMENT_TU         338
#define IDR_MENU_SOFTWARE               338
#define IDD_SERVER_DLG                  339
#define IDD_DAMPING_TU                  340
#define IDD_DISPLAY_TU                  343
#define IDD_MAPPING_SPYT                344
#define IDD_CURRENTOUTPUT_TU            345
#define IDD_ADVANCEDSETUP1_TU           346
#define IDD_ADVANCEDSETUP2_TU           347
#define IDB_QT                          347
#define IDD_FALSEECHO_TU                348
#define IDB_SPYT                        348
#define IDD_SERVICEOTHER_TU             349
#define IDB_BITMAP3                     349
#define IDB_ZT                          349
#define IDD_PIN_TU                      350
#define IDB_REDFLAG                     350
#define IDD_RESET_TU                    351
#define IDB_GREENFLAG                   351
#define IDD_ECHOCURVE_TU                352
#define IDB_REDFLAG2                    352
#define IDB_BLUEFLAG                    352
#define IDD_ECHODATA_TU                 353
#define IDD_TREND_TU                    354
#define IDB_FLOWDengkuanbaobi           354
#define IDD_FLOWBAXIEER                 355
#define IDD_OUTPUTMAPPING_TU            356
#define IDB_FLOWJuxingbaobi             356
#define IDD_ADVANCEDSETUP1_SU           357
#define IDB_FLOWJuxingkuanding          357
#define IDD_FLOWWUHOUDAO                358
#define IDB_FLOWSanjiaobaobi            358
#define IDB_FLOWSanjiaoxingpoumian      359
#define IDD_CURRENTOUTPUT_SU            360
#define IDB_FLOWVxingyan                360
#define IDD_DAMPING_SU                  361
#define IDB_FLOWWuhoudao                361
#define IDD_DIAGNOSIS_SU                362
#define IDB_FLOWBaxier                  362
#define IDD_DISPLAY_SU                  363
#define IDB_BITMAP1                     363
#define IDB_FlowYuanyuan                363
#define IDD_ECHOCURVE_SU                364
#define IDD_ECHODATA_SU                 365
#define IDD_FALSEECHO_SU                366
#define IDB_BITMAP2                     366
#define IDB_HEAD                        366
#define IDD_LEVEL_ADJUSTMENT_SU         367
#define IDD_PIN_SU                      369
#define IDD_RESET_SU                    370
#define IDB_BITMAP4                     370
#define IDB_GODA                        370
#define IDD_SERVICEOTHER_SU             371
#define IDB_BITMAP_PR                   371
#define IDB_BITMAP_SU                   372
#define IDD_TREND_SU                    373
#define IDB_BITMAP_TU                   373
#define IDD_OUTPUTMAPPING_SU            374
#define IDB_BITMAP_GR                   374
#define IDB_BITMAP5                     375
#define IDD_TREND_GR                    376
#define IDB_BITMAP6                     376
#define IDB_BITMAP7                     377
#define IDD_ADVANCEDSETUP1_GR           378
#define IDB_BITMAP8                     378
#define IDD_ADVANCEDSETUP2_GR           379
#define IDB_BITMAP9                     379
#define IDD_ECHOCURVE_GR                380
#define IDB_BITMAP10                    380
#define IDD_ECHODATA_GR                 381
#define IDB_BITMAP11                    381
#define IDD_FALSEECHO_GR                382
#define IDB_BITMAP12                    382
#define IDD_OUTPUTMAPPING_GR            383
#define IDB_BITMAP13                    383
#define IDD_RESET_GR                    384
#define IDD_PIN_GR                      385
#define IDD_SERVICEOTHER_PR1            386
#define IDD_SERVICEOTHER_GR             386
#define IDD_APPLICATION_GR              387
#define IDB_BITMAP14                    388
#define IDB_CONNECT                     388
#define IDD_APPLICATION_TU              389
#define IDD_OTHERSETTINGS_GR            390
#define IDD_OTHERSETTINGS_SU            391
#define IDD_OTHERSETTINGS_TU            392
#define IDD_SIMULATE_GR                 393
#define IDD_SIMULATE_TU                 394
#define IDD_SIMULATE_PR3                395
#define IDD_SIMULATE_SU                 395
#define IDD_APPLICATION_SU              396
#define IDD_ADVANCEDSETUP2_SU           397
#define IDD_DEVICESTAT_3                398
#define IDD_DIAGNOSIS_PR1               399
#define IDD_DIAGNOSIS_TU                399
#define IDD_LINEDIT                     400
#define IDD_MAPPING_QT                  401
#define IDD_MAPPING_ZT                  402
#define IDD_LINEARIZATION_GR            403
#define IDD_LINEARIZATION_TU            404
#define IDD_LINEARIZATION_SU            405
#define IDD_FLOWBAXIEER1                406
#define IDD_FLOWSANJIAOPOUMIAN          406
#define IDD_FLOWSANJIAOBAOBI            407
#define IDD_FLOWDENGKUANBAOBI           408
#define IDD_FLOWJUXINGKUANDING          409
#define IDD_FLOWYUANYUAN                410
#define IDD_FLOWVXINGYAN                411
#define IDD_FLOWVXINGYAN1               412
#define IDD_FLOWJUXINGBAOBI             412
#define IDD_INFO                        413
#define IDR_MENU1                       415
#define IDR_MENU_INFO                   415
#define IDB_BITMAP15                    416
#define IDB_BITMAP16                    417
#define IDI_MAINFRAME                   425
#define IDS_FLOWERR0                    500
#define IDS_FLOWERR1                    501
#define IDS_FLOWERR2                    502
#define IDS_FLOWERR3                    503
#define IDS_FLOWERR4                    504
#define IDS_FLOWERR5                    505
#define IDS_FLOWERR6                    506
#define IDS_FLOWERR7                    507
#define IDS_FLOWERR8                    508
#define IDC_EDIT_NAME                   1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_PW                     1001
#define IDC_EDIT_STAT                   1001
#define IDC_EDIT_TEMPFFFSET             1001
#define IDC_COMBO_LOGINTYPE             1002
#define IDC_COMBO_DEVICETYPE            1003
#define IDC_COMBO_COMPORT               1004
#define IDC_EDIT_HIGH                   1005
#define IDC_COMBO_PROTOCOL              1006
#define IDC_LIST_MAPPING                1006
#define IDC_IPADDRESS1                  1007
#define IDC_LIST_ECHODATA               1007
#define IDC_COMBO_MEDIATYPE             1008
#define IDC_TITLE                       1010
#define IDC_CHECK_FOAM                  1011
#define IDC_TITLE2                      1011
#define IDC_COMBO1                      1012
#define IDC_COMBO_SIMUTYPE              1012
#define IDC_COMBO_ADDRESS               1012
#define IDC_COMBO_POINTNUMBER           1012
#define IDC_COMBO_CURRENTOUT            1012
#define IDC_COMBO_ADDITIONALADJUST      1013
#define IDC_COMBO2                      1013
#define IDC_COMBO_VESSELTYPE            1013
#define IDC_COMBO_POINTNUM              1013
#define IDC_COMBO_POINTNUMBER2          1013
#define IDC_COMBO3                      1014
#define IDC_COMBO_MIN                   1014
#define IDC_COMBO_LINTYPE               1014
#define IDC_COMBO_RELAYALARM            1014
#define IDC_COMBO4                      1015
#define IDC_COMBO_UNIT                  1015
#define IDC_COMBO_CURRENTPORT           1015
#define IDC_EDIT_0PERCENT               1016
#define IDC_COMBO_CALIBRATION           1016
#define IDC_COMBO_RELAY                 1016
#define IDC_COMBO5                      1016
#define IDC_COMBO6                      1017
#define IDC_COMBO_LINEARIATIONTYPE      1017
#define IDC_COMBO_LIN0EARIZATIONTYPE    1017
#define IDC_COMBO_SENSOR                1017
#define IDC_COMBO_SENSERTYPE            1018
#define IDC_COMBO_SENSOR2               1018
#define IDC_COMBO_DISPLAY               1019
#define IDC_EDIT_TEMPERATURE            1020
#define IDC_COMBO_ERROR                 1021
#define IDC_COMBO_OUTPUT                1022
#define IDC_COMBO_LANGUAGE              1023
#define IDC_EDIT_FREQ                   1024
#define IDC_BUTTON_EDIT                 1025
#define IDC_BTN_SAVE                    1026
#define IDC_LABEL_IP                    1027
#define IDC_SHOCKWAVEFLASH1             1028
#define IDC_SHOCKWAVEFLASH              1028
#define IDC_EDIT_MAPVAL0                1029
#define IDC_CHECK_ENVELOP               1030
#define IDC_CHECK_FALSEECHO             1031
#define IDC_RADIO1                      1031
#define IDC_CHECK_ECHOCURVE             1032
#define IDC_RADIO2                      1032
#define IDC_CURVE                       1033
#define IDC_USERPOWER                   1033
#define IDC_BTN_RESET1                  1034
#define IDC_BTN_RESET2                  1035
#define IDC_ADD                         1035
#define IDC_BTN_RESET3                  1036
#define IDC_MODIFY                      1036
#define IDC_BTN_RESET4                  1037
#define IDC_USERNAME                    1037
#define IDC_LABEL                       1038
#define IDC_PASSWORD                    1038
#define IDC_EDIT_VALUE                  1039
#define IDC_USERINFO                    1039
#define IDC_BTN_NEW                     1040
#define IDC_PASSWORD2                   1040
#define IDC_BTN_UPDATE                  1041
#define IDC_BUTTON_DISTADJ              1042
#define IDC_BUTTON_VELOADJ              1043
#define IDC_CHECK_ENABLEDIA             1045
#define IDC_ADDRESS                     1046
#define IDC_RADIO_NOTLEARN              1046
#define IDC_RADIO_LEARN                 1047
#define IDC_ADDRESS2                    1047
#define IDC_BTN_SETLEARN                1048
#define IDC_ADDRESS3                    1048
#define IDC_MEASUREDVAL0                1049
#define IDC_ADDRESS4                    1049
#define IDC_MEASUREDVAL8                1050
#define IDC_ADDRESS5                    1050
#define IDC_BTN_SIMULATE                1051
#define IDC_BTN_SIMULATE2               1052
#define IDC_LIST1                       1053
#define IDC_LIST_DEVSTAT                1053
#define IDC_COMBOBOXEX2                 1053
#define IDC_EDIT_ADDRESS                1054
#define IDC_RADIO3                      1055
#define IDC_EDIT_CHANGEDISTRICT         1055
#define IDC_EDIT_ADDRESS2               1055
#define IDC_RADIO4                      1056
#define IDC_EDIT_BLENDAREA              1056
#define IDC_RADIO5                      1057
#define IDC_EDIT_ECHO                   1057
#define IDC_EDIT_ECHORANGE              1057
#define IDC_EDIT_UNIT                   1058
#define IDC_EDIT_ADDRESS5               1058
#define IDC_EDIT_TGC1                   1058
#define IDC_EDIT_FREQMIN                1060
#define IDC_EDIT_FREQMAX                1061
#define IDC_STATIC_IP                   1062
#define IDC_STATIC_USER                 1063
#define IDC_STATIC_USERSTATUS           1063
#define IDC_CHECK_ENABLEMULTISENSOR     1063
#define IDC_LOAD                        1064
#define IDC_SAVE                        1065
#define IDC_CHECK_MULTIECHO             1066
#define IDC_EDIT_NULLHIGHT1             1067
#define IDC_EDIT_L                      1067
#define IDC_STATIC_INFO                 1068
#define IDC_EDIT_H                      1068
#define IDC_STATIC_CLASSIFYUSER         1069
#define IDC_EDIT_D                      1069
#define IDC_STATIC_CONTROL              1070
#define IDC_BUTTON_GENERATE             1070
#define IDC_STATIC_NEWUSER              1071
#define IDC_EDIT_R                      1071
#define IDC_STATIC_USERNAME             1072
#define IDC_EDIT_DENSITY                1072
#define IDC_STATIC_PASSWORD             1073
#define IDC_STATIC_CONFIRMPASSWORD      1074
#define IDC_PROGRESS1                   1075
#define IDC_BUTTON_LOAD                 1075
#define IDC_BUTTON_SAVE                 1076
#define IDC_COMBO_B                     1077
#define IDC_LABEL2                      1078
#define IDC_COMBO_FLOWTYPE              1078
#define IDC_COMBO_B2                    1078
#define IDC_LABEL1                      1079
#define IDC_STATIC_FLOWTYPE             1079
#define IDC_LABEL3                      1080
#define IDC_BUTTON1                     1080
#define IDC_LABEL4                      1081
#define IDC_LABEL14                     1082
#define IDC_EDIT1                       1082
#define IDC_BUTTON6                     1082
#define ID_EDIT_HIGH_PERCENT            1083
#define IDC_EDIT_DAMPING                1083
#define IDC_EDIT_100PERCENT             1083
#define IDC_EDIT_SENSERTAG              1083
#define ID_EDIT_MIN                     1083
#define IDC_EDIT_TGC                    1083
#define IDC_EDIT_MAPVAL1                1083
#define IDC_MEASUREDVAL1                1083
#define IDC_EDIT_SIMUVALUE              1083
#define IDC_EDIT68                      1083
#define IDC_LABEL23                     1084
#define IDC_CHECKBOX1                   1084
#define IDC_EDIT3                       1084
#define IDC_EDIT_ECHOAM                 1084
#define IDC_EDIT_MAPVAL2                1084
#define IDC_MEASUREDVAL2                1084
#define IDC_EDIT_DEVICETYPE             1084
#define IDC_EDIT_LOWADJUST_PERCENT      1085
#define IDC_EDIT4                       1085
#define IDC_EDIT_MAX                    1085
#define IDC_EDIT_MAPVAL3                1085
#define IDC_MEASUREDVAL3                1085
#define IDC_EDIT_SHORTWITDH             1085
#define IDC_LABEL18                     1085
#define IDC_EDIT5                       1086
#define IDC_EDIT_PIPEDIAMETER           1086
#define IDC_EDIT_MAPVAL4                1086
#define IDC_MEASUREDVAL4                1086
#define IDC_EDIT_NOISE                  1086
#define IDC_EDIT_SERIALNUM              1086
#define IDC_EDIT_LOWADJUST              1087
#define IDC_EDIT6                       1087
#define IDC_EDIT_CURRENT                1087
#define IDC_EDIT_MAPVAL5                1087
#define IDC_MEASUREDVAL5                1087
#define IDC_EDIT_LONGWIDTH              1087
#define IDC_EDIT_HIGHT                  1087
#define IDC_LABEL19                     1087
#define IDC_LABEL25                     1088
#define IDC_LABEL6                      1088
#define IDC_BUTTON3                     1088
#define IDC_EDIT7                       1088
#define IDC_EDIT_MAPVAL6                1088
#define IDC_MEASUREDVAL6                1088
#define IDC_EDIT_DATE                   1088
#define IDC_BTN_RELAYTEST               1088
#define IDC_EDIT8                       1089
#define IDC_STATIC1                     1089
#define IDC_EDIT_RIGION                 1089
#define IDC_EDIT_MAPVAL7                1089
#define IDC_MEASUREDVAL7                1089
#define IDC_EDIT_HIGHALARM              1089
#define IDC_LABEL22                     1089
#define IDC_EDIT_SHADOWRIGION           1090
#define IDC_EDIT9                       1090
#define IDC_EDIT_MAPVAL8                1090
#define IDC_EDIT_LOWALARM               1090
#define IDC_EDIT_VERSION                1090
#define IDC_BTN_TEST                    1090
#define IDC_EDIT10                      1091
#define IDC_EDIT_MAPVAL9                1091
#define IDC_MEASUREDVAL9                1091
#define IDC_LABEL28                     1091
#define IDC_CHECKBOX2                   1092
#define IDC_EDIT11                      1092
#define IDC_EDIT_MAPVAL10               1092
#define IDC_MEASUREDVAL10               1092
#define IDC_CHECKBOX3                   1093
#define IDC_EDIT67                      1093
#define IDC_CHECKBOX4                   1094
#define IDC_LABEL9                      1094
#define IDC_EDIT70                      1094
#define IDC_CHECKBOX5                   1095
#define IDC_EDIT71                      1095
#define IDC_CHECKBOX6                   1096
#define IDC_EDIT72                      1096
#define IDC_LABEL12                     1097
#define IDC_EDIT73                      1097
#define IDC_LABEL13                     1098
#define IDC_EDIT_HYSTERESYS             1098
#define IDC_EDIT74                      1098
#define IDC_LABEL17                     1099
#define IDC_EDIT69                      1099
#define IDC_LABEL15                     1100
#define IDC_EDIT12                      1100
#define IDC_EDIT_HIGHT0                 1100
#define IDC_MEASUREDVAL11               1100
#define IDC_LABEL16                     1101
#define IDC_EDIT13                      1101
#define IDC_EDIT_HIGHT1                 1101
#define IDC_MEASUREDVAL12               1101
#define IDC_EDIT14                      1102
#define IDC_EDIT_HIGHT2                 1102
#define IDC_MEASUREDVAL13               1102
#define IDC_LABEL24                     1103
#define IDC_EDIT15                      1103
#define IDC_EDIT_HIGHT3                 1103
#define IDC_MEASUREDVAL14               1103
#define IDC_EDIT16                      1104
#define IDC_EDIT_HIGHT4                 1104
#define IDC_MEASUREDVAL15               1104
#define IDC_EDIT17                      1105
#define IDC_EDIT_DISTOFFSET             1105
#define IDC_EDIT_HIGHT5                 1105
#define IDC_MEASUREDVAL16               1105
#define IDC_EDIT18                      1106
#define IDC_EDIT_VELOCITYOFFSET         1106
#define IDC_EDIT_HIGHT6                 1106
#define IDC_MEASUREDVAL17               1106
#define IDC_LABEL20                     1107
#define IDC_EDIT19                      1107
#define IDC_EDIT_HIGHT7                 1107
#define IDC_MEASUREDVAL18               1107
#define IDC_LABEL21                     1108
#define IDC_EDIT20                      1108
#define IDC_EDIT_HIGHT8                 1108
#define IDC_MEASUREDVAL19               1108
#define IDC_EDIT22                      1110
#define IDC_EDIT_HIGHT10                1110
#define IDC_MEASUREDVAL21               1110
#define IDC_EDIT78                      1111
#define IDC_EDIT_20MA                   1111
#define IDC_EDIT23                      1111
#define IDC_EDIT_MAPVAL11               1111
#define IDC_MEASUREDVAL22               1111
#define IDC_LABEL26                     1112
#define IDC_EDIT24                      1112
#define IDC_EDIT_MAPVAL12               1112
#define IDC_MEASUREDVAL23               1112
#define IDC_EDIT80                      1113
#define IDC_EDIT_4MA                    1113
#define IDC_EDIT25                      1113
#define IDC_EDIT_MAPVAL13               1113
#define IDC_MEASUREDVAL24               1113
#define IDC_LABEL27                     1114
#define IDC_EDIT26                      1114
#define IDC_EDIT_MAPVAL14               1114
#define IDC_MEASUREDVAL25               1114
#define IDC_EDIT82                      1115
#define IDC_EDIT_ECHOLIMIT              1115
#define IDC_EDIT27                      1115
#define IDC_EDIT_MAPVAL15               1115
#define IDC_MEASUREDVAL26               1115
#define IDC_LABEL29                     1116
#define IDC_EDIT28                      1116
#define IDC_EDIT_MAPVAL16               1116
#define IDC_MEASUREDVAL27               1116
#define IDC_EDIT29                      1117
#define IDC_EDIT_MAPVAL17               1117
#define IDC_MEASUREDVAL28               1117
#define IDC_EDIT30                      1118
#define IDC_EDIT_MAPVAL18               1118
#define IDC_MEASUREDVAL29               1118
#define IDC_EDIT31                      1119
#define IDC_EDIT_MAPVAL19               1119
#define IDC_CALIVAL0                    1119
#define IDC_EDIT32                      1120
#define IDC_EDIT_MAPVAL20               1120
#define IDC_CALIVAL1                    1120
#define IDC_EDIT33                      1121
#define IDC_EDIT_MAPVAL21               1121
#define IDC_CALIVAL2                    1121
#define IDC_EDIT34                      1122
#define IDC_EDIT_HIGHT11                1122
#define IDC_CALIVAL3                    1122
#define IDC_EDIT35                      1123
#define IDC_EDIT_HIGHT12                1123
#define IDC_CALIVAL4                    1123
#define IDC_EDIT36                      1124
#define IDC_EDIT_HIGHT13                1124
#define IDC_CALIVAL5                    1124
#define IDC_EDIT37                      1125
#define IDC_EDIT_HIGHT14                1125
#define IDC_CALIVAL6                    1125
#define IDC_EDIT38                      1126
#define IDC_EDIT_HIGHT15                1126
#define IDC_CALIVAL7                    1126
#define IDC_EDIT39                      1127
#define IDC_EDIT_HIGHT16                1127
#define IDC_CALIVAL8                    1127
#define IDC_EDIT40                      1128
#define IDC_EDIT_HIGHT17                1128
#define IDC_CALIVAL9                    1128
#define IDC_EDIT41                      1129
#define IDC_EDIT_HIGHT18                1129
#define IDC_CALIVAL10                   1129
#define IDC_EDIT42                      1130
#define IDC_EDIT_HIGHT19                1130
#define IDC_CALIVAL11                   1130
#define IDC_EDIT43                      1131
#define IDC_EDIT_HIGHT20                1131
#define IDC_CALIVAL12                   1131
#define IDC_EDIT44                      1132
#define IDC_EDIT_HIGHT21                1132
#define IDC_CALIVAL13                   1132
#define IDC_EDIT45                      1133
#define IDC_EDIT_MAPVAL22               1133
#define IDC_CALIVAL14                   1133
#define IDC_EDIT46                      1134
#define IDC_EDIT_MAPVAL23               1134
#define IDC_CALIVAL15                   1134
#define IDC_EDIT47                      1135
#define IDC_EDIT_MAPVAL24               1135
#define IDC_CALIVAL16                   1135
#define IDC_EDIT48                      1136
#define IDC_EDIT_MAPVAL25               1136
#define IDC_CALIVAL17                   1136
#define IDC_EDIT49                      1137
#define IDC_EDIT_MAPVAL26               1137
#define IDC_CALIVAL18                   1137
#define IDC_EDIT50                      1138
#define IDC_EDIT_MAPVAL27               1138
#define IDC_CALIVAL19                   1138
#define IDC_EDIT51                      1139
#define IDC_EDIT_MAPVAL28               1139
#define IDC_CALIVAL20                   1139
#define IDC_EDIT52                      1140
#define IDC_EDIT_MAPVAL29               1140
#define IDC_CALIVAL21                   1140
#define IDC_EDIT53                      1141
#define IDC_EDIT_MAPVAL30               1141
#define IDC_CALIVAL22                   1141
#define IDC_EDIT54                      1142
#define IDC_EDIT_MAPVAL31               1142
#define IDC_CALIVAL23                   1142
#define IDC_IMAGE1                      1143
#define IDC_EDIT81                      1143
#define IDC_EDIT56                      1144
#define IDC_EDIT_HIGHT22                1144
#define IDC_CALIVAL25                   1144
#define IDC_EDIT57                      1145
#define IDC_EDIT_HIGHT23                1145
#define IDC_CALIVAL26                   1145
#define IDC_EDIT58                      1146
#define IDC_EDIT_HIGHT24                1146
#define IDC_CALIVAL27                   1146
#define IDC_EDIT59                      1147
#define IDC_EDIT_HIGHT25                1147
#define IDC_CALIVAL28                   1147
#define IDC_EDIT60                      1148
#define IDC_EDIT_HIGHT26                1148
#define IDC_CALIVAL29                   1148
#define IDC_EDIT61                      1149
#define IDC_EDIT_HIGHT27                1149
#define IDC_MEASUREDVAL30               1149
#define IDC_EDIT62                      1150
#define IDC_EDIT_HIGHT28                1150
#define IDC_MEASUREDVAL31               1150
#define IDC_EDIT63                      1151
#define IDC_EDIT_HIGHT29                1151
#define IDC_MEASUREDVAL32               1151
#define IDC_EDIT64                      1152
#define IDC_EDIT_HIGHT30                1152
#define IDC_CALIVAL30                   1152
#define IDC_EDIT65                      1153
#define IDC_EDIT_HIGHT31                1153
#define IDC_CALIVAL31                   1153
#define IDC_EDIT75                      1154
#define IDC_EDIT55                      1155
#define IDC_EDIT_MAPVAL32               1155
#define IDC_CALIVAL24                   1155
#define IDC_EDIT66                      1156
#define IDC_EDIT_HIGHT32                1156
#define IDC_CALIVAL32                   1156
#define IDC_EDIT77                      1158
#define IDC_EDIT79                      1160
#define IDC_BUTTON4                     1161
#define IDC_BUTTON_RESETVAL             1161
#define IDC_LIST2                       1162
#define IDC_IMAGE                       1164
#define IDC_STATUSSELECT                1171
#define IDC_FRQZONE                     1174
#define IDC_FRQZONE2                    1175
#define IDC_STATIC3                     1175
#define IDC_FRQZONE3                    1176
#define IDC_STATIC4                     1176
#define IDC_FRQZONE4                    1177
#define IDC_STATIC5                     1177
#define IDC_STATIC6                     1178
#define IDC_STATIC7                     1179
#define IDC_STATIC8                     1180
#define IDC_STATIC9                     1181
#define IDC_STATIC10                    1182
#define IDC_STATIC11                    1183
#define IDC_STATIC12                    1184
#define IDC_STATIC13                    1185
#define IDC_CANCELPIN                   1191
#define IDC_BTN_DEL                     1191
#define IDC_BEPIN                       1192
#define IDC_STATICTEMP                  1196
#define IDC_SENSOR1                     1198
#define IDC_PORT1                       1200
#define IDC_PORT2                       1201
#define IDC_CURRENT                     1202
#define IDC_LINPERCENT                  1203
#define IDC_LINVALUE                    1204
#define IDC_MAXHEIGH                    1208
#define IDC_GDSL53S                     1246
#define IDC_GDSL53E                     1247
#define IDC_SOLIDKIND                   1248
#define IDC_STATICKJ                    1252
#define IDC_CHECK_ENABLEFLOW            1254
#define IDC_CHECK_AGITATEDSURFACE       1255
#define IDC_CHECK_POWDER                1257
#define IDC_CHECK_LARGEANGLE            1258
#define IDC_CHECK_LOWDK                 1259
#define IDC_STATICB                     1259
#define IDC_STATICL                     1260
#define IDC_STATICP2                    1261
#define IDC_STATICP                     1262
#define IDC_STATICP1                    1263
#define IDC_BTN_CALIBRATE               1272
#define IDC_CELIANG1                    1273
#define IDC_CELIANG2                    1274
#define IDC_CELIANG3                    1275
#define IDC_CELIANG4                    1276
#define IDC_BIAODING1                   1277
#define IDC_BIAODING2                   1278
#define IDC_BIAODING3                   1279
#define IDC_BIAODING4                   1280
#define IDC_EDIT21                      1287
#define IDC_EDIT_HIGHT9                 1287
#define IDC_MEASUREDVAL20               1287
#define IDC_DKVALUE                     1290
#define IDC_NULLHIGH                    1291
#define IDC_EDITHIGH                    1292
#define IDC_EDIT_NULLHIGHT              1292
#define IDC_EDITDK                      1293
#define IDC_EDIT_DKVALUE                1293
#define IDC_EDIT_NULLHIGHT2             1293
#define IDC_EDIT_NULLHIGHT3             1294
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_BASIC_LEVEL                  32776
#define ID_BASIC_APPLICATION            32777
#define ID_BASIC_DAMPING                32778
#define ID_BASIC_LINERIZATION           32779
#define ID_BASIC_OTHER                  32780
#define ID_32781                        32781
#define ID_DISPLAY_DISPLAY              32782
#define ID_32783                        32783
#define ID_DIAGNOSIS_DIAGNOSIS          32784
#define ID_32785                        32785
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_SERVICE_CURRENTOUTPUT        32790
#define ID_SERVICE_RESET                32791
#define ID_SERVICE_FALSEECHO            32792
#define ID_SERVICE_PIN                  32793
#define ID_SERVICE_OTHER                32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_ADVANCED_ADVANVCE1           32797
#define ID_ADVANCED_ADVANVCED1          32798
#define ID_ADVANCED_ADVANVCED2          32799
#define ID_32800                        32800
#define ID_32801                        32801
#define ID_DEVICEOP_LOAD                32802
#define ID_DEVICEOP_SAVE                32803
#define ID_32804                        32804
#define ID_32805                        32805
#define ID_32806                        32806
#define ID_RECONNECT                    32807
#define ID_CHANGEUSER                   32808
#define ID_USERMANAGEMENT               32809
#define ID_Menu                         32810
#define ID_INFO_INFO                    32811
#define ID_32812                        32812
#define ID_DEVICEOP_REFRESH             32813
#define IDC_BUTTON2                     59506
#define IDC_DELETE                      59506
#define IDC_BUTTON5                     59507
#define IDC_BTN_DELETE                  59507

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        426
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           359
#endif
#endif
