//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PVCS v1.0.rc
//
#define IDOK2                           2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDT_UPDATE_VALUES               101
#define IDS_TITLE_BALLAST               101
#define IDC_TANKVALUELIST               102
#define IDS_TITLE_BALLAST_BACKUP        102
#define IDC_DXFLAYOUT                   103
#define IDS_TITLE_CARGO                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDT_GETWAGODATA                 104
#define IDD_SPLASHWND                   105
#define IDS_TITLE_CARGO_BACKUP          105
#define IDT_CLOSESPLASH                 106
#define IDS_TITLE_SPLASH                106
#define IDT_SPLASHPROGRESS              107
#define IDC_LEGENDLIST                  108
#define IDT_ALARM_FLASH                 109
#define IDT_ALARM_BEEP                  110
#define IDD_PVCSDIALOGCARGOCLOSE        111
#define IDD_PVCSWAGOCONNECTDLG          112
#define IDR_HTML_PVCSWARNINGMESSAGE     113
#define IDR_HTML_MANUALCONTROLMESSAGE   114
#define IDR_MAINFRAME                   128
#define IDR_PVCSv10TYPE                 129
#define IDD_PVCSOBJECTCONTROLDLG        130
#define IDD_PVCSTANKDLG                 131
#define IDB_BITMAP1                     133
#define IDB_BITMAPAN                    133
#define IDD_CALIBRATEWAGO               135
#define IDD_ALARM_DLG                   137
#define IDD_WARNING_MESSAGE             138
#define IDD_LODING_PVCS                 139
#define IDD_Time_out_Dialog             142
#define IDD_WagoUnitStatus              144
#define IDB_BITMAP2                     145
#define IDB_BITMAP3                     146
#define IDR_PVCSTOOLBAR                 150
#define IDD_DIALOG1                     152
#define IDD_AlARMBUTTONHOLDER           152
#define IDD_DIALOG2                     155
#define IDD_PVCS_MANUAL_CTRL_DLG        155
#define IDD_PASSWORD                    163
#define IDD_PVCS_EMERGENCY_CTRL_DLG     164
#define IDD_TIMEOUT_DLG                 165
#define IDC_BUTTON_ON                   1000
#define IDC_BUTTON_ONE                  1000
#define IDC_TEXT                        1001
#define IDC_BUTTON_OFF                  1002
#define IDC_BUTTON_TWO                  1002
#define IDC_BUTTON_CONFIRM              1003
#define IDC_SPIN                        1004
#define IDC_EDIT1                       1005
#define IDC_EDIT_RPM                    1005
#define IDC_EDIT_VALUE                  1005
#define IDC_EDITSTARTCALIBRATION        1005
#define IDC_PROGRESS_INIT               1006
#define IDC_EDIT                        1007
#define IDC_COMBO1                      1009
#define IDC_OBJECTNAMECOMBO             1009
#define IDC_STARTCALIBRATION            1010
#define IDC_STOPCALIBRATION             1011
#define IDC_EDITSTOPCALIBRATION         1012
#define IDC_STATICCHANNELNUMBER         1013
#define IDC_EDITCHANNELNO               1014
#define IDC_ALARMACKNOW_BUTTON          1014
#define IDC_COMBO2                      1015
#define IDC_COMBOCHANNELTYPE            1015
#define IDC_SILENCEALARM_BUTTON         1015
#define IDC_COMBOCHANNELNUMBER          1015
#define IDC_BUTTON1                     1016
#define IDC_ALARM_LIST                  1016
#define IDC_BUTTON2                     1017
#define IDC_OK                          1017
#define IDC_CHECK1                      1017
#define IDC_BUTTON3                     1018
#define IDC_EDIT2                       1018
#define IDC_ENTER_MESSAGE               1019
#define IDC_LIST1                       1019
#define IDC_CALIBRATION_LIST            1019
#define IDC_Time_Out_LIST               1019
#define IDC_WagoUnitStatusList          1019
#define IDC_EDIT3                       1019
#define IDC_LOADING_PVCS                1020
#define IDC_LOADING_PVCS_TEXT           1020
#define IDC_LOGO                        1023
#define IDC_PVCS_HANDLE                 1024
#define IDC_SPIN1                       1025
#define IDC_LIST2                       1026
#define ID_WagoUnitStatusOK             1027
#define IDWagoUnitStatusOK              1028
#define IDC_PROGRESS1                   1029
#define IDC_PVCS_PROGRESS               1029
#define IDC_STATUS_TEXT                 1030
#define IDC_ALARMBUTTON                 1031
#define IDC_PASSWORD_TEXT               1032
#define IDC_PUMPBUTTON1                 1032
#define IDC_TIMEOUT_ST                  1033
#define IDC_PUMPBUTTON2                 1033
#define IDC_PUMPBUTTON3                 1034
#define IDC_PUMPBUTTON4                 1035
#define IDC_PUMPBUTTON5                 1036
#define ID_FILE_REQUESTCOMMAND          32772
#define ID_FILE_CALIBRATE               32773
#define ID_Menu                         32774
#define ID_FILE_ALARM                   32777
#define ID_CONNECT                      32778
#define ID_FILE_R                       32779
#define ID_FILE_WINDOWSWITCH            32780
#define ID_WINDOWSWITCH_CARGOSHIP       32781
#define ID_WINDOWSWITCH_BALLSATSHIP     32782
#define ID_ANWIN                        32783
#define ID_TEST                         32785
#define ID_TEXT                         32786
#define ID_COMMAND                      32788
#define IDT_ALARM                       32788
#define ID_COMMAND_MULTIPLESCREEN       32791
#define ID_COMMAND_THISSCREEN           32792
#define ID_CONTROL_COMMAND              32793
#define ID_FILE_TIMEOUTLIST             32794
#define ID_FILE_WAGOUNITSTATUS          32795
#define ID_FILE_SENDTOALLCLIENTS        32796
#define ID_FILE                         32797
#define ID_FILE_SENDTOALLCLIENTS32798   32798
#define ID_BUTTON32820                  32820
#define ID_BUTTON32821                  32821
#define IDC_ALARM                       32822
#define IDT_PUMP1                       32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
