#include "TSNIncludes.h"
#pragma hdrstop
//---------------------------------------------------------------------------
NewLanguageWord GermanDictionary[]=
{
//	{ Keyword	,English (0)
	{ L_WORD0   ,L"FEIL-FEIL-"},
	{L_WORD1  ,L"Einschalten"},
	{L_WORD2    ,L"Ausschalten"},
	{L_WORD3    ,L"An"},
	{L_WORD4    ,L"Aus"},
	{L_WORD5    ,L"Drucker"},
	{L_WORD6    ,L"Sprache:"},
	{L_WORD7    ,L"Alarme"},
	{L_WORD8    ,L"Ballast Austausch"},
	{L_WORD9    ,L"Cargo"},
	{L_WORD10   ,L"Service"},
	{L_WORD11   ,L"Temperatur"},
	{L_WORD12   ,L"Tankdruck"},
	{L_WORD13   ,L"Aufzeichnung wählen:"},
	{L_WORD14   ,L"Aufzeichnungszeit"},
	{L_WORD15   ,L"Stunden"},
	{L_WORD16   ,L"Drucker Einrichtung"},
	{L_WORD17   ,L"Öffnen"},
	{L_WORD18   ,L"Schliessen"},
	{L_WORD19   ,L"Aufzeichnungsperiode"},
	{L_WORD20   ,L"System Seite 1"},
	{L_WORD21   ,L"Bedienungsanleitung"},
	{L_WORD22   ,L"Einrichtung"},
	{L_WORD23   ,L"Drucker"},
	{L_WORD24   ,L"Programmversion"},
	{L_WORD25   ,L"Datenversion:"},
	{L_WORD26   ,L"System ID:"},
	{L_WORD27   ,L"Systemeinheit:"},
	{L_WORD28   ,L"Sprache"},
	{L_WORD29   ,L"GMT"},
	{L_WORD30   ,L"System Seite 2"},
	{L_WORD31   ,L"Atmospherische Ref."},
	{L_WORD32   ,L"Meter"},
	{L_WORD33   ,L"Quelle Trimm:"},
	{L_WORD34   ,L"Grad"},
	{L_WORD35   ,L"Tiefgang:"},
	{L_WORD36   ,L"Einheit"},
	{L_WORD37   ,L"Seewasser"},
	{L_WORD38   ,L"Quelle Krängung:"},
	{L_WORD39   ,L"System Seite 3: IO Einheiten"},
	{L_WORD40   ,L"Auswahl:"},
	{L_WORD41   ,L"System Seite 4: Hardware Einheiten"},
	{L_WORD42   ,L"System Seite 5"},
	{L_WORD43   ,L"Total für alle Tanks"},
	{L_WORD44   ,L"Volumen"},
	{L_WORD45   ,L"Gewicht"},
	{L_WORD46   ,L"Wasser"},
	{L_WORD47   ,L"Ballast"},
	{L_WORD48   ,L"Schweröl"},
	{L_WORD49   ,L"Dieselöl"},
	{L_WORD50   ,L"Schmiermittel"},
	{L_WORD51   ,L"Frischwasser"},
	{L_WORD52   ,L"Verschiedenes"},
	{L_WORD53   ,L"Grand total"},
	{L_WORD54   ,L"Systemeinrichtungsseite"},
	{L_WORD55   ,L"Bildschirmschoner:"},
	{L_WORD56   ,L"Minuten"},
	{L_WORD57   ,L"Alarm Abschaltverzögerung:"},
	{L_WORD58   ,L"Sekunden"},
	{L_WORD59   ,L"SI Einheit"},
	{L_WORD60   ,L"US Einheit"},
	{L_WORD61   ,L"Farbe einstellen:"},
	{L_WORD62   ,L"Hintergrund"},
	{L_WORD63   ,L"Vordergrund"},
	{L_WORD64   ,L"Helligkeit:"},
	{L_WORD65   ,L"Summer /\nLicht Test"},
	{L_WORD66   ,L"PIN Code ändern"},
	{L_WORD67   ,L"Bildschirm kalibrieren"},
	{L_WORD68   ,L"EEPROM"},
	{L_WORD69   ,L"Anwendungseinstellungen"},
	{L_WORD70   ,L"Spalte 1"},
	{L_WORD71   ,L"Spalte 2"},
	{L_WORD72   ,L"Spalte 3"},
	{L_WORD73   ,L"Spalte 4"},
	{L_WORD74   ,L"Name"},
	{L_WORD75   ,L"Nulljustierung Tank\n Drucksensor für\n alle Ballasttanks."},
	{L_WORD76   ,L"Nulljustierung Füllstand\n Sensor(en) für\n alle Ballasttanks."},
	{L_WORD77   ,L"Ballastwasser Dichte"},
	{L_WORD78   ,L"Nulljustierung Tank\n Drucksensor für\n alle Cargotanks."},
	{L_WORD79   ,L"Nulljustierung Füllstand\n Sensor(en) für\n alle Cargotanks."},
	{L_WORD80   ,L"Dichte für:"},
	{L_WORD81   ,L"Nulljustierung Tank\n Drucksensor für\n alle Tankdruckpunkte."},
	{L_WORD82   ,L"Allgemeiner Eingang für alle Ballasttanks"},
	{L_WORD83   ,L"Dichte"},
	{L_WORD84   ,L"Konfigurationsfehler"},
	{L_WORD85   ,L"Text"},
	{L_WORD86   ,L"Weiter"},
	{L_WORD87   ,L"Bild hoch"},
	{L_WORD88   ,L"Bild runter"},
	{L_WORD89   ,L"Anwendungseinstellungen"},
	{L_WORD90   ,L"Detail"},
	{L_WORD91   ,L"\nUnbekannter Fehler in Konfiguration."},
	{L_WORD92   ,L"Cargo line pressure"},
	{L_WORD93   ,L"Vapour return line"},
	{L_WORD94   ,L"Wassereinbruch Erkennung"},
	{L_WORD95   ,L"Füllstandschalter"},
	{L_WORD96   ,L"System"},
	{L_WORD97   ,L"Alarm"},
	{L_WORD98   ,L"übernehmen\n Gruppe"},
	{L_WORD99   ,L"Nicht konfiguriert"},
	{L_WORD100  ,L"Nicht benutzt"},
	{L_WORD101  ,L"Linear"},
	{L_WORD102  ,L"API / ASTM-IP"},
	{L_WORD103  ,L"Gemessene Dichte benutzen"},
	{L_WORD104  ,L"Referenztemperatur"},
	{L_WORD105  ,L"Referenztemperatur benutzen"},
	{L_WORD106  ,L"Referenz 1"},
	{L_WORD107  ,L"Referenz 2"},
	{L_WORD108  ,L"Koeffizient"},
	{L_WORD109  ,L"Overfill"},
	{L_WORD110  ,L"High Level"},
	{L_WORD111  ,L"Low Level"},
	{L_WORD112  ,L"High Temp"},
	{L_WORD113  ,L"Low Temp"},
	{L_WORD114  ,L"High Tank Press"},
	{L_WORD115  ,L"Low Tank Press"},
	{L_WORD116  ,L"Nulljustierung Tank- \nDrucksensor"},
	{L_WORD117  ,L"Nulljustierung Füllstand- \nsensor(en)."},
	{L_WORD118  ,L"Füllstand justieren"},
	{L_WORD119  ,L"Peilung justieren"},
	{L_WORD120  ,L"Freiraum justieren"},
	{L_WORD121  ,L"Volumen justieren"},
	{L_WORD122  ,L"Gewicht justieren"},
	{L_WORD123  ,L"Entsperren"},
	{L_WORD124  ,L"Ort"},
	{L_WORD125  ,L"Ein"},
	{L_WORD126  ,L"Verstärkung"},
	{L_WORD127  ,L"Versatz"},
	{L_WORD128  ,L"Wert"},
	{L_WORD129  ,L"Neuer Wert"},
	{L_WORD130  ,L"Vorgang bestätigen"},
	{L_WORD131  ,L"Eingestellte Dichte für alle Cargotanks übernehmen."},
	{L_WORD132  ,L"Eingestellte Dichte für alle Ballasttanks übernehmen."},
	{L_WORD133  ,L"Eingestellte Dichte für alle Servicetanks übernehmen."},
	{L_WORD134  ,L"Neue Alarm-Grenze"},
	{L_WORD135  ,L"Derzeitige Alarmeinstellungen für alle Cargotanks übernehmen."},
	{L_WORD136  ,L"Derzeitige Alarmeinstellungen für alle Ballasttanks übernehmen."},
	{L_WORD137  ,L"Derzeitige Alarmeinstellungen für alle Servicetanks übernehmen."},
	{L_WORD138  ,L"Derzeitige Alarmeinstellungen für jeden Tankdruck übernehmen."},
	{L_WORD139  ,L"Derzeitige Alarmeinstellungen für jeden Temperaturpunkt übernehmen."},
	{L_WORD140  ,L"Nulljustierung Sensor"},
	{L_WORD141  ,L"Der Sensor muss in die Atmosphäre entlüftet werden"},
	{L_WORD142  ,L"Nulljustierung Füllstandsensor(en)!"},
	{L_WORD143  ,L"Der Tank muss leer und die letzte Tankreinigung länger als 30 min. her sein."},
	{L_WORD144  ,L"Der Füllstand wird auf den eingegebenen Stand justiert. Falsche Eingaben führen zur Fehlfunktion des Systems."},
	{L_WORD145  ,L"überwachter Stand"},
	{L_WORD146  ,L"überwachte Peilung"},
	{L_WORD147  ,L"überwachter Freiraum"},
	{L_WORD148  ,L"überwachtes Volumen"},
	{L_WORD149  ,L"überwachtes Gewicht"},
	{L_WORD150  ,L"PIN Code eingeben:"},
	{L_WORD151  ,L"Sensorverstärkung einstellen"},
	{L_WORD152  ,L"Sensorvolumen einstellen"},
	{L_WORD153  ,L"Warnung"},
	{L_WORD154  ,L"Sie sind dabei, die Sensorverstärkung zu justieren. Dies kann die Genauigkeit beeinträchtigen!"},
	{L_WORD155  ,L"Sie sind dabei, den Sensor zu justieren. Dies kann die Genauigkeit beeinträchtigen!"},
	{L_WORD156  ,L"Nulljustierung"},
	{L_WORD157  ,L"Sensorwerte"},
	{L_WORD158  ,L"Hoher Leitungsdruck"},
	{L_WORD159  ,L"Niedriger Leitungsdruck"},
	{L_WORD160  ,L"Nulljustierung Leitungs- \nDrucksensor"},
	{L_WORD161  ,L"OK"},
	{L_WORD162  ,L"Ja"},
	{L_WORD163  ,L"Nein"},
	{L_WORD164  ,L"Weiter?"},
	{L_WORD165  ,L"Detailansicht-Warnung:"},
	{L_WORD166  ,L"Zur Tankauswahl auf die Zeile, dann auf Detail drücken."},
	{L_WORD167  ,L"< zurück"},
	{L_WORD168  ,L"vorwärts >"},
	{L_WORD169  ,L"Bestätigung"},
	{L_WORD170  ,L"Beschreibung"},
	{L_WORD171  ,L"Alarmbeginn"},
	{L_WORD172  ,L"Reset"},
	{L_WORD173  ,L"Kein Alarm"},
	{L_WORD174  ,L"Datum einstellen (DD.MM.YY)"},
	{L_WORD175  ,L"Zeit einstellen (HH.MM.SS)"},
	{L_WORD176  ,L"Fehler bei Zeiteingabe!"},
	{L_WORD177  ,L"Zeitformat (h.m.s)"},
	{L_WORD178  ,L"Fehler bei Datumseingabe!"},
	{L_WORD179  ,L"Datumsformat (d.m.y)"},
	{L_WORD180  ,L"Neuen Wert eingeben:"},
	{L_WORD181  ,L"Kein Wert"},
	{L_WORD182  ,L"Kein Sensor"},
	{L_WORD183  ,L"Trimm einstellen (Aft ist -)"},
	{L_WORD184  ,L"Krängung einstellen (Port ist -)"},
	{L_WORD185  ,L"Neue Dichte eingeben:"},
	{L_WORD186  ,L"0"},
	{L_WORD187  ,L"1"},
	{L_WORD188  ,L"Fehler"},
	{L_WORD189  ,L"Automatisch"},
	{L_WORD190  ,L"Manuell"},
	{L_WORD191  ,L"Kein Fehler"},
	{L_WORD192  ,L"Eingabefehler"},
	{L_WORD193  ,L"Fehler Dichte"},
	{L_WORD194  ,L"Ref.-Temp. 1 ist fix"},
	{L_WORD196  ,L"Falscher Koeffizient"},
	{L_WORD197  ,L"Wert ist zu hoch"},
	{L_WORD198  ,L"Wert ist zu niedrig"},
	{L_WORD199  ,L"API benutzen"},
	{L_WORD200  ,L"Ref.Dichte 1 benutzen"},
	{L_WORD201  ,L"Auswahl API Tabelle"},
	{L_WORD202  ,L"ungültiger Verweis"},
	{L_WORD203  ,L"ungültiger Wert"},
	{L_WORD204  ,L"unbekannter Tank"},
	{L_WORD205  ,L"AD nicht gefunden"},
	{L_WORD206  ,L"Kein tmp Sensor"},
	{L_WORD207  ,L"Wert ausserhalb der Bandbreite"},
	{L_WORD208  ,L"System Seewasser benutzen"},
	{L_WORD209  ,L"System Ballastwasser benutzen"},
	{L_WORD210  ,L"Temp.tief=Temp.hoch"},
	{L_WORD211  ,L"Eingabe nicht erlaubt"},
	{L_WORD212  ,L"Cargo undefiniert"},
	{L_WORD213  ,L"Eingabe wiederholen"},
	{L_WORD214  ,L"Ref.- Dichte 1 zu niedrig"},
	{L_WORD215  ,L"Ref.- Dichte 1 zu hoch"},
	{L_WORD216  ,L"Ref.- Dichte 2 zu niedrig"},
	{L_WORD217  ,L"Ref.- Dichte 2 zu hoch"},
	{L_WORD218  ,L"API ausserhalb des Spektrums"},
	{L_WORD219  ,L"Sensorfehler"},
	{L_WORD220  ,L"Verstärkung ausserhalb des Spektrums"},
	{L_WORD221  ,L"Systems Frischwasser benutzen"},
	{L_WORD222  ,L"System Schweröl benutzen"},
	{L_WORD223  ,L"System Diesel benutzen"},
	{L_WORD224  ,L"Systems Schmierstoffe benutzen"},
	{L_WORD225  ,L"unteres > oberes Limit"},
	{L_WORD226  ,L"oberes < unteres Limit"},
	{L_WORD227  ,L"oberes = unteres Limit"},
	{L_WORD228  ,L"Nicht justierbar"},
	{L_WORD229  ,L"Keine Eingabeberechtigung"},
	{L_WORD230  ,L"Sensor ist abgeschaltet"},
	{L_WORD231  ,L"API53 Tabelle benutzen"},
	{L_WORD232  ,L"API54 Tabelle benutzen"},
	{L_WORD233  ,L"Ref.-Dichte 2 benutzen"},
	{L_WORD234  ,L"Kann gemeinsamen Eingang nicht benutzen"},
	{L_WORD235  ,L"Überschreiben nur möglich bei Vor- oder Hauptalarm"},
	{L_WORD236  ,L"Keine Einheit"},
	{L_WORD237  ,L""},
	{L_WORD238  ,L"Länge"},
	{L_WORD239  ,L"Atm.-/Dampfdruck"},
	{L_WORD240  ,L"Cargo/Ballast Druck"},
	{L_WORD241  ,L"Leitungsdruck"},
	{L_WORD242  ,L"Dichtekoeffizient"},
	{L_WORD243  ,L"Winkel"},
	{L_WORD244  ,L"Freie Oberfläche"},
	{L_WORD245  ,L"Moment"},
	{L_WORD246  ,L"Eintauchnung"},
	{L_WORD247  ,L"Ladungsrate"},
	{L_WORD248  ,L"Prozent"},
	{L_WORD249  ,L"Stromstärke"},
	{L_WORD250  ,L"Spannung"},
	{L_WORD252  ,L"Zeit"},
	{L_WORD253  ,L"mSekunden"},
	{L_WORD254  ,L"Tage"},
	{L_WORD255  ,L"feet  1"},
	{L_WORD256  ,L"d.feet"},
	{L_WORD257  ,L"m³"},
	{L_WORD258  ,L"Liter"},
	{L_WORD259  ,L"US g."},
	{L_WORD260  ,L"US bls"},
	{L_WORD261  ,L"ton"},
	{L_WORD262  ,L"l.ton"},
	{L_WORD263  ,L"kN"},
	{L_WORD264  ,L"m³/h"},
	{L_WORD265  ,L"USb/h"},
	{L_WORD266  ,L"°C"},
	{L_WORD267  ,L"°F"},
	{L_WORD268  ,L"mH2O"},
	{L_WORD269  ,L"mmH2O"},
	{L_WORD270  ,L"mBar"},
	{L_WORD271  ,L"Bar"},
	{L_WORD272  ,L"Psi"},
	{L_WORD273  ,L"kPa"},
	{L_WORD274  ,L"InH2O"},
	{L_WORD275  ,L"InHg"},
	{L_WORD276  ,L"t/m³ vac"},
	{L_WORD277  ,L"t/m³ air"},
	{L_WORD278  ,L"lb/usg"},
	{L_WORD279  ,L"Grad"},
	{L_WORD280  ,L"Rad."},
	{L_WORD281  ,L"t/m³°C"},
	{L_WORD282  ,L"t/m³°F"},
	{L_WORD283  ,L"l/g/°C"},
	{L_WORD284  ,L"l/g/°F"},
	{L_WORD285  ,L"m^4"},
	{L_WORD286  ,L"Feet^4"},
	{L_WORD287  ,L"t*m"},
	{L_WORD288  ,L"lton*Ft"},
	{L_WORD289  ,L"kNm"},
	{L_WORD290  ,L"t/cm"},
	{L_WORD291  ,L"lton/in"},
	{L_WORD292  ,L"m*Rad"},
	{L_WORD293  ,L"%"},
	{L_WORD294  ,L"‰"},
	{L_WORD295  ,L"mA"},
	{L_WORD296  ,L"A"},
	{L_WORD297  ,L"V"},
	{L_WORD298  ,L"mV"},
	{L_WORD299  ,L"ms"},
	{L_WORD300  ,L"s"},
	{L_WORD301  ,L"Min"},
	{L_WORD302  ,L"Stunden"},
	{L_WORD303  ,L"Tage"},
	{L_WORD304  ,L"unbenutzt"},
	{L_WORD305  ,L"Füllstand bei Sensor"},
	{L_WORD306  ,L"Füllstand bei Referenzpunkt"},
	{L_WORD307  ,L"Füllstand bei Flotationszentrum"},
	{L_WORD308  ,L"Peilung"},
	{L_WORD309  ,L"Ullage"},
	{L_WORD310  ,L"Volumen%"},
	{L_WORD311  ,L"Druck"},
	{L_WORD312  ,L"Hoher Druck"},
	{L_WORD313  ,L"Niedriger Druck"},
	{L_WORD314  ,L"Endzeit"},
	{L_WORD315  ,L"Restzeit"},
	{L_WORD316  ,L"Cargotyp"},
	{L_WORD317  ,L"unterer Druck"},
	{L_WORD318  ,L"mittl. Druck"},
	{L_WORD319  ,L"oberer Druck"},
	{L_WORD320  ,L"Top Druck"},
	{L_WORD321  ,L"p(u) Verstärkung"},//  p(u)=Unterer Druck"},
	{L_WORD322  ,L"p(m) Verstärkung"},//  p(m)=Mittlerer Druck"},
	{L_WORD323  ,L"p(o) Verstärkung"},//  p(o)=Oberer Druck"},
	{L_WORD324  ,L"p(t) Verstärkung"},//  p(t)=Top Druck"},
	{L_WORD325  ,L"p(u) Versatz"},
	{L_WORD326  ,L"p(m) Versatz"},
	{L_WORD327  ,L"p(o) Versatz"},
	{L_WORD328  ,L"p(t) Versatz"},
	{L_WORD329  ,L"FstS"},//  Fst=Füllstand   Max 4 char, used on the tPC350"},
	{L_WORD330  ,L"FstR"},//  Fst=Füllstand   Max 4 char, used on the tPC351"},
	{L_WORD331  ,L"FstF"},//  Fst=Füllstand   Max 4 char, used on the tPC352"},
	{L_WORD332  ,L"Peil"},//  Peil=Peilung    Max 4 char, used on the tPC353"},
	{L_WORD333  ,L"Ull"},//     Max 4 char, used on the tPC354"},
	{L_WORD334  ,L"Vol"},//     Max 4 char, used on the tPC355"},
	{L_WORD335  ,L"Vol%"},//      Max 4 char, used on the tPC356"},
	{L_WORD336  ,L"Gew."},//      Max 4 char, used on the tPC357"},
	{L_WORD337  ,L"Di."},//     Max 4 char, used on the tPC358"},
	{L_WORD338  ,L"Temp"},//      Max 4 char, used on the tPC359"},
	{L_WORD339  ,L"Dru."},//      Max 4 char, used on the tPC360"},
	{L_WORD340  ,L"HTmp"},//      Max 4 char, used on the tPC361"},
	{L_WORD341  ,L"LTmp"},//      Max 4 char, used on the tPC362"},
	{L_WORD342  ,L"HD"},//      Max 4 char, used on the tPC363"},
	{L_WORD343  ,L"ND"},//      Max 4 char, used on the tPC364"},
	{L_WORD344  ,L"LRate"},//     Max 4 char, used on the tPC365"},
	{L_WORD345  ,L"FZt."},//  FZt.=Fertig Zeit    Max 4 char, used on the tPC366"},
	{L_WORD346  ,L"RZt."},//  RZt.=Restzeit     Max 4 char, used on the tPC367"},
	{L_WORD347  ,L"CTyp"},//      Max 4 char, used on the tPC368"},
	{L_WORD348  ,L"p(u)"},//      Max 4 char, used on the tPC369"},
	{L_WORD349  ,L"p(m)"},//      Max 4 char, used on the tPC370"},
	{L_WORD350  ,L"p(o)"},//      Max 4 char, used on the tPC371"},
	{L_WORD351  ,L"p(t)"},//      Max 4 char, used on the tPC372"},
	{L_WORD352  ,L"pu-V"},//  puV=Verstärkung Druck unten   Max 4 char, used on the tPC373"},
	{L_WORD353  ,L"pm-V"},//  pmV=Verstärkung Druck mitte   Max 4 char, used on the tPC374"},
	{L_WORD354  ,L"po-V"},//  poV=Verstärkung Druck oben    Max 4 char, used on the tPC375"},
	{L_WORD355  ,L"pt-V"},//  ptV=Verstärkung Druck top   Max 4 char, used on the tPC376"},
	{L_WORD356  ,L"pu-O"},//  pu-O=pu-Offset=pu-Versatz   Max 4 char, used on the tPC377"},
	{L_WORD357  ,L"pm-O"},//  pm-O=pm-Offset=pm-Versatz   Max 4 char, used on the tPC378"},
	{L_WORD358  ,L"po-O"},//  po-O=po-Ofgfset=po-Versatz    Max 4 char, used on the tPC379"},
	{L_WORD359  ,L"pt-O"},//  pt-O=pt-Offset=pt-Versatz   Max 4 char, used on the tPC380"},
	{L_WORD360  ,L"untere Temp"},
	{L_WORD361  ,L"mittl. Temp"},
	{L_WORD362  ,L"obere Temp"},
	{L_WORD363  ,L"Top Temp"},
	{L_WORD364  ,L"T(u)"},
	{L_WORD365  ,L"T(m)"},
	{L_WORD366  ,L"T(o)"},
	{L_WORD367  ,L"T(t)"},
	{L_WORD368  ,L"Atm. Sensor"},
	{L_WORD369  ,L"Stromversorgung 24V(1)"},
	{L_WORD370  ,L"Stromversorgung 24V(2)"},
	{L_WORD371  ,L"Stromversorgung 3.3V"},
	{L_WORD372  ,L"Stromversorgung 1.8V"},
	{L_WORD373  ,L"OS Status"},
	{L_WORD374  ,L"Flash Status"},
	{L_WORD375  ,L"Anwendungsname"},
	{L_WORD376  ,L"Laufzeit"},
	{L_WORD377  ,L"Stromversorgung 5.0V"},
	{L_WORD378  ,L"Stromversorgung 12V"},
	{L_WORD379  ,L"Com Kanal"},
	{L_WORD380  ,L"Com Version"},
	{L_WORD381  ,L"Speicher Vers."},
	{L_WORD382  ,L"Rx Puffergröße"},
	{L_WORD383  ,L"Tx Puffergröße"},
	{L_WORD384  ,L"Status Reset"},
	{L_WORD385  ,L"Neustart Total"},
	{L_WORD386  ,L"Ausfallzähler"},
	{L_WORD387  ,L"Totalausfallzahler"},
	{L_WORD388  ,L"Programm"},
	{L_WORD389  ,L"Stromversorgung 24V"},
	{L_WORD390  ,L"Seriennummer"},
	{L_WORD391  ,L"Status Einheit"},
	{L_WORD392  ,L"Status Karte"},
	{L_WORD393  ,L"Cargo Name"},
	{L_WORD394  ,L"VolKorrFaktor"},
	{L_WORD395  ,L"VKF@Temp"},
	{L_WORD396  ,L"API gemessen"},
	{L_WORD397  ,L"Comp. Dichte"},
	{L_WORD398  ,L"Op. Dichte1"},
	{L_WORD399  ,L"Op. Dichte2"},
	{L_WORD400  ,L"Ref. Temp1"},
	{L_WORD401  ,L"Ref. Temp2"},
	{L_WORD402  ,L"Nicht definiert"},
	{L_WORD403  ,L"Einfach"},
	{L_WORD404  ,L"Atm.Druck"},
	{L_WORD405  ,L"Ballast"},
	{L_WORD406  ,L"Schweröl"},
	{L_WORD407  ,L"Diesel"},
	{L_WORD408  ,L"Schmierstoffe"},
	{L_WORD409  ,L"Frischwasser"},
	{L_WORD410  ,L"Seewasser"},
	{L_WORD411  ,L"TV"},
	{L_WORD421  ,L"TBb"},
	{L_WORD422  ,L"TStb"},
	{L_WORD423  ,L"TH"},
//	{L_WORD424  ,L"Füllstand"},
	{L_WORD425  ,L"Trimmung in Grad"},
	{L_WORD426  ,L"Trimmung in Meter"},
	{L_WORD427  ,L"Krängung in Grad"},
	{L_WORD428  ,L"TV (Auswahl Anwender)"},
	{L_WORD429  ,L"TH (Auswahl Anwender)"},
	{L_WORD430  ,L"TV@Mark"},
	{L_WORD431  ,L"TH@Mark"},
	{L_WORD432  ,L"TV@PP"},
	{L_WORD433  ,L"TH@PP"},
	{L_WORD434  ,L"Ein/Aus"},
	{L_WORD435  ,L"Systemdaten"},
	{L_WORD436  ,L"Tiefgang"},
	{L_WORD437  ,L"Cargotank"},
	{L_WORD438  ,L"andere Tanks"},
	{L_WORD446  ,L"gem. Dichte"},
	{L_WORD447  ,L"Krängung in Meter"},
	{L_WORD448  ,L"Latitude"},
	{L_WORD449  ,L"Typ"},
	{L_WORD450  ,L"SnsDB"},
	{L_WORD451  ,L"Platzieren"},
	{L_WORD454  ,L"Kabellänge"},
	{L_WORD460  ,L"Trimm"},
	{L_WORD461  ,L"List"},
	{L_WORD462  ,L"Schwarz"},
	{L_WORD463  ,L"Dunkelgrau"},
	{L_WORD464  ,L"Hellgrau"},
	{L_WORD465  ,L"Weiss"},
	{L_WORD466  ,L"Blau"},
	{L_WORD467  ,L"Drucken"},
	{L_WORD469  ,L"bls benutzen"},
	{L_WORD470  ,L"m³ benutzen"},
	{L_WORD471  ,L"Trocken"},
	{L_WORD472  ,L"--.-"},
	{L_WORD473  ,L"Leer"},
	{L_WORD474  ,L""},
	{L_WORD475  ,L"Haupt"},
	{L_WORD476  ,L"Vor"},
	{L_WORD477  ,L"über"},
	{L_WORD478  ,L"Schutz"},
	{L_WORD484  ,L"Anwendung"},
	{L_WORD485  ,L"Unbekannt"},
	{L_WORD486  ,L"Nichts"},
	{L_WORD487  ,L"Fehler"},
	{L_WORD488  ,L"Nicht benutzt"},
	{L_WORD489  ,L"Andere"},
	{L_WORD490  ,L"Drücken"},
	{L_WORD491  ,L"@PP"},
	{L_WORD492  ,L"@Mark"},
	{L_WORD493  ,L"Deakt."},
	{L_WORD494  ,L"Aktiv."},
	{L_WORD495  ,L"Best."},
	{L_WORD496  ,L"Lim:"},
	{L_WORD497  ,L"Wert:"},
	{L_WORD498  ,L"Verweisfehler"},
	{L_WORD499  ,L"Unbek.."},
	{L_WORD510  ,L"Hochspannung"},
	{L_WORD528  ,L"Ausfall"},
	{L_WORD550  ,L"Versatz Füllstand"},
	{L_WORD551  ,L"Inklinometer"},
	{L_WORD552  ,L"Tiefgang"},
	{L_WORD553  ,L"gemessen"},
	{L_WORD564  ,L"Von TCU"},
	{L_WORD565  ,L"Grün"},
	{L_WORD566  ,L"FLASH löschen"},
	{L_WORD567  ,L"Info"},
	{L_WORD568  ,L"Fehler löschen"},
	{L_WORD569  ,L"Programm Update wird ausgeführt, bitte warten..."},
	{L_WORD570  ,L"Laufzeitkalibrierung,\n bitte den Bildschrim in der\n Mitte des Ringes berühren"},
	{L_WORD571  ,L"Abbruch"},
	{L_WORD572  ,L"Hier drücken"},
	{L_WORD573  ,L"(obere linke Position)"},
	{L_WORD574  ,L"(untere rechte Position)"},
	{L_WORD575  ,L"Seite"},
	{L_WORD576  ,L"Dateiversion"},
	{L_WORD577  ,L"Cargotanks"},
	{L_WORD578  ,L"Ballasttanks"},
	{L_WORD579  ,L"Servicetanks"},
	{L_WORD580  ,L"Schweröltanks"},
	{L_WORD581  ,L"Dieselöltanks"},
	{L_WORD582  ,L"Schmiermitteltanks"},
	{L_WORD583  ,L"verschiedene Tanks"},
	{L_WORD584  ,L"Frischwassertanks"},
	{L_WORD585  ,L"Nicht definiert"},
	{L_WORD586  ,L"Atm"},
	{L_WORD587  ,L"Boden"},
	{L_WORD588  ,L"Mitte"},
	{L_WORD589  ,L"Oben"},
	{L_WORD593  ,L"Deck"},
	{L_WORD594  ,L"Deck"},
	{L_WORD595  ,L"Leitung"},
	{L_WORD602  ,L"Nulljustierung Tankdruck!"},
	{L_WORD603  ,L"Die Tanks müssen in die Atmosphäre entlüftet werden. Dieser Vorgang beeinflusst alle Tanks in der Gruppe."},
	{L_WORD604  ,L"Nulljustierung Sensor(en)!"},
	{L_WORD605  ,L"Die Tanks müssen leer und die letzte Tankreinigung länger als 30 min. her sein. Dieser Vorgang beeinflusst alle Tanks in der Gruppe."},
	{L_WORD606  ,L"Warnung Nulljustierung:"},
	{L_WORD607  ,L"Die Tanks müssen in die Atmosphäre entlüftet werden. Dieser Vorgang beeinflusst alle Tankdruck Punkte."},
	{L_WORD608  ,L"Der Tank muss leer und die letzte Tankreinigung länger als 30 min. her sein. Dieser Vorgang beeinflusst alle Tankdruck Punkte."},
	{L_WORD609  ,L"Schweröldichte"},
	{L_WORD610  ,L"Dieselöldichte"},
	{L_WORD611  ,L"Schmiermitteldichte"},
	{L_WORD612  ,L"Frischwasserdichte"},
	{L_WORD613  ,L"Datei verkürzt"},
	{L_WORD614  ,L"Fehler im UNICODE String!"},
	{L_WORD615  ,L"V"},
	{L_WORD616  ,L"H"},
	{L_WORD617  ,L"Bb"},
	{L_WORD618  ,L"Stb"},
	{L_WORD619  ,L"Gerade"},
	{L_WORD620  ,L"Drucker an dieser TDU Einheit"},
	{L_WORD621  ,L"Temperaturen"},
	{L_WORD622  ,L"Leitungsdrücke"},
	{L_WORD623  ,L"Tankdrücke"},
	{L_WORD677  ,L"Füllstand"},
};

unsigned WordsInGermanDictionary = NELEMENTS(GermanDictionary);

wchar_t GermanUserManual[] = {L"           TDU - Bedienungsanleitung \n\
\n\
Für die vollständige Information zur Handhabung des Systems, sehen Sie bitte in die Installations- und Bedienungsanleitung.\n\
\n\
Dieser Touch Screen sollte nur mit dem Stylus-Schreiber oder der Fingerspitze bedient werden. Andere Hilfsmittel/Werkzeuge können den Bildschirm beschädigen.\n\
\n\
HINWEIS:\n\
Bevor Sie das System bedienen, müssen die Instruktionen und die Bedienungsanleitung sorgfältig gelesen und verstanden worden sein.\n\
\n\
Es wird darauf hingewiesen, dass Sie die Folgen einer falschen Bedienung des Dichte-Systems, der Alarm-Einstellungen, des Abschaltens von Alarmen und der Nulljustierung von Sensoren kennen müssen.\n\
Die falsche Bedienung kann zur Überlastung und/oder Beschädigung führen.\n\
\n\
Ersatzteile oder Anleitungen erhalten Sie bei:\n\
\n\
Scanjet Ariston AS\n\
Dokkvegen 10\n\
3920 Porsgrunn\n\
Norway \n\
\n\
Tel: +47 35 93 11 30\n\
Service: +47 958 78 644\n\
Fax: +47 35 93 11 31\n\
E-mail: service@ariston.no\n\
Web: www.ariston.no\n\
"};
int SizeOfGermanUserManual= sizeof(GermanUserManual);

