#include "TSNIncludes.h"
#pragma hdrstop
//---------------------------------------------------------------------------
NewLanguageWord DutchDictionary[]=
{
    { L_WORD1   ,L"Inschakelen"},
    { L_WORD2   ,L"Uitschakelen"},
    { L_WORD3   ,L"Aan"},
    { L_WORD4   ,L"Uit"},
    { L_WORD5   ,L"Printer"},
    { L_WORD6   ,L"Taal:"},
    { L_WORD7   ,L"Alarmen"},
    { L_WORD8   ,L"Ballasten"},
    { L_WORD9   ,L"Lading"},
    { L_WORD10  ,L"Service"},
    { L_WORD11  ,L"Temperatuur"},
    { L_WORD12  ,L"Tankdruk"},
    { L_WORD13  ,L"Kies loggen:"},
    { L_WORD14  ,L"Logtijd"},
    { L_WORD15  ,L"Uren"},
    { L_WORD16  ,L"Printer setup"},
    { L_WORD17  ,L"Open"},
    { L_WORD18  ,L"Dicht"},
    { L_WORD19  ,L"Logperiode"},
    { L_WORD20  ,L"Systeem blz 1"},
    { L_WORD21  ,L"Gebruikershandleiding"},
    { L_WORD22  ,L"Setup"},
    { L_WORD23  ,L"Printer"},
    { L_WORD24  ,L"Programma versie:"},
    { L_WORD25  ,L"Data versie:"},
    { L_WORD26  ,L"System ID:"},
    { L_WORD27  ,L"Eenheden:"},
    { L_WORD28  ,L"Taal"},
    { L_WORD29  ,L"GMT"},
    { L_WORD30  ,L"Systeem blz 2"},
    { L_WORD31  ,L"Atmosferische ref."},
    { L_WORD32  ,L"meter"},
    { L_WORD33  ,L"Trim meting:"},
    { L_WORD34  ,L"graden"},
    { L_WORD35  ,L"Diepgang:"},
    { L_WORD36  ,L"Eenheid"},
    { L_WORD37  ,L"Zeewater"},
    { L_WORD38  ,L"List source:"},
    { L_WORD39  ,L"Systeem blz 3: IO units"},
    { L_WORD40  ,L"Selecteer:"},
    { L_WORD41  ,L"Systeem blz 4: Hardware units"},
    { L_WORD42  ,L"Systeem blz 5"},
    { L_WORD43  ,L"Totaal van alle tanks"},
    { L_WORD44  ,L"Volume"},
    { L_WORD45  ,L"Gewicht"},
    { L_WORD46  ,L"Water"},
    { L_WORD47  ,L"Ballast"},
    { L_WORD48  ,L"Zware stookolie"},
    { L_WORD49  ,L"Diesel"},
    { L_WORD50  ,L"smeermiddelen"},
    { L_WORD51  ,L"Drinkwater"},
    { L_WORD52  ,L"Diversen"},
    { L_WORD53  ,L"Totaal"},
    { L_WORD54  ,L"Systeem setup blz"},
    { L_WORD55  ,L"Screen saver:"},
    { L_WORD56  ,L"minuten"},
    { L_WORD57  ,L"Alarm uit vertraging"},
    { L_WORD58  ,L"seconden"},
    { L_WORD59  ,L"SI eenheid"},
    { L_WORD60  ,L"US eenheid"},
    { L_WORD61  ,L"kleur instellen:"},
    { L_WORD62  ,L"Achtergrond"},
    { L_WORD63  ,L"Voorgrond"},
    { L_WORD64  ,L"Helderheid:"},
    { L_WORD65  ,L"Zoemer /\nLicht test"},
    { L_WORD66  ,L"Verander PIN code"},
    { L_WORD67  ,L"Schermcalibratie"},
    { L_WORD68  ,L"EEPROM"},
    { L_WORD69  ,L"Applicatie setup"},
    { L_WORD70  ,L"Kol. 1"},
    { L_WORD71  ,L"Kol. 2"},
    { L_WORD72  ,L"Kol. 3"},
    { L_WORD73  ,L"Kol. 4"},
    { L_WORD74  ,L"Naam"},
    { L_WORD75  ,L"Nul stellen tank \n druksensor van\n alle ballast tanks."},
    { L_WORD76  ,L"Nul stellen niveau \n sensor(s) van\n alle ballast tanks."},
    { L_WORD77  ,L"Ballast water density"},
    { L_WORD78  ,L"Nul stellen tank \n druksensor van\n alle ladingtanks."},
    { L_WORD79  ,L"Nul stellen niveau \n sensor(s) van\n alle ladingtanks."},
    { L_WORD80  ,L"Density voor:"},
    { L_WORD81  ,L"Nul stellen tank \n druksensor van\n alle drukpunten."},
    { L_WORD82  ,L"Gemeenschappelijke input voor alle Ballast tanks"},
    { L_WORD83  ,L"Density:"},
    { L_WORD84  ,L"Configuratie fout"},
    { L_WORD85  ,L"Text"},
    { L_WORD86  ,L"Doorgaan"},
    { L_WORD87  ,L"Vorige"},
    { L_WORD88  ,L"Volgende"},
    { L_WORD89  ,L"App.Setup"},
    { L_WORD90  ,L"Detail"},
    { L_WORD91  ,L"\nOnbekende fout in Configuratie"},
    { L_WORD92  ,L"Lading lijndruk"},
    { L_WORD93  ,L"Vapour retour lijn"},
    { L_WORD94  ,L"Water detectie"},
    { L_WORD95  ,L"Niveauschakelaar"},
    { L_WORD96  ,L"Systeem"},
    { L_WORD97  ,L"Alarm"},
    { L_WORD98  ,L"Toepassen\n op groep"},
    { L_WORD99  ,L"Niet geconfigureerd"},
    { L_WORD100 ,L"Niet in gebruik"},
    { L_WORD101 ,L"Lineair"},
    { L_WORD102 ,L"ASTM / ASTM-IP"},
    { L_WORD103 ,L"Gebruik gemeten Density"},
    { L_WORD104 ,L"T15"},
    { L_WORD105 ,L"Gebruik referentie Dichtheid"},
    { L_WORD106 ,L"Referentie 1"},
    { L_WORD107 ,L"Referentie 2"},
    { L_WORD108 ,L"Coefficient"},
    { L_WORD109 ,L"Overvul"},
    { L_WORD110 ,L"Hoog Alarm"},
    { L_WORD111 ,L"Laag Alarm"},
    { L_WORD112 ,L"Hoge Temp"},
    { L_WORD113 ,L"Lage Temp"},
    { L_WORD114 ,L"Hoge Tankdruk"},
    { L_WORD115 ,L"Lage Tankdruk"},
    { L_WORD116 ,L"Nul stellen tank \n druksensor"},
    { L_WORD117 ,L"Nul stellen niveau \n sensor"},
    { L_WORD118 ,L"Aanpassen niveau"},
    { L_WORD119 ,L"Aanpassen Sounding"},
    { L_WORD120 ,L"Aanpassen Ullage"},
    { L_WORD121 ,L"Aanpassen Volume"},
    { L_WORD122 ,L"Aanpassen Gewicht"},
    { L_WORD123 ,L"Vrijgeven"},
    { L_WORD124 ,L"Locatie"},
    { L_WORD125 ,L"Ena"},
    { L_WORD126 ,L"Gain"},
    { L_WORD127 ,L"Offset"},
    { L_WORD128 ,L"Waarde"},
    { L_WORD129 ,L"Nieuwe waarde"},
    { L_WORD130 ,L"Bevestig opdracht"},
    { L_WORD131 ,L"Pas huidige density settings toe op alle ladingtanks"},
    { L_WORD132 ,L"Pas huidige density settings toe op alle ballasttanks"},
    { L_WORD133 ,L"Pas huidige density settings toe op alle servicetanks"},
    { L_WORD134 ,L"Nieuwe Alarm limiet"},
    { L_WORD135 ,L"Pas huidige alarm settings toe op alle ladingtanks"},
    { L_WORD136 ,L"Pas huidige alarm settings toe op alle ballasttanks"},
    { L_WORD137 ,L"Pas huidige alarm settings toe op alle servicetanks"},
    { L_WORD138 ,L"Pas huidige alarm settings toe op alle Tank druksensors"},
    { L_WORD139 ,L"Pas huidige alarm settings toe op alle Temperatuur sensoren"},
    { L_WORD140 ,L"Nul stellen sensor"},
    { L_WORD141 ,L"Sensor moet belucht worden"},
    { L_WORD142 ,L"Nul stellen van niveau sensor(en)!"},
    { L_WORD143 ,L"De tank moet leeg zijn en tank cleaning  heeft gedurende 30 minuten niet plaatDensityevonden"},
    { L_WORD144 ,L"Beschermplaat!"},
    { L_WORD145 ,L"Gepeild niveau"},
    { L_WORD146 ,L"Gepeilde Sounding"},
    { L_WORD147 ,L"Gepeilde Ullage"},
    { L_WORD148 ,L"Gepeild Volume"},
    { L_WORD149 ,L"Gepeild Gewicht"},
    { L_WORD150 ,L"Voer PIN code in:"},
    { L_WORD151 ,L"Stel sensor gain in"},
    { L_WORD152 ,L"Zet sensorwaarde"},
    { L_WORD153 ,L"Waarschuwing"},
    { L_WORD154 ,L"U staat op het punt de gain van de sensor aan te passen. Dit kan de nauwkeurigheid beïnvloeden."},
    { L_WORD155 ,L"U staat op het punt de sensorwaarde aan te passen. Dit kan de nauwkeurigheid beïnvloeden"},
    { L_WORD156 ,L"Nul stellen"},
    { L_WORD157 ,L"Sensor waarde"},
    { L_WORD158 ,L"High Line Press"},
    { L_WORD159 ,L"Low Line Press"},
    { L_WORD160 ,L"Nul stellen line\n pressuresensor"},
    { L_WORD161 ,L"OK"},
    { L_WORD162 ,L"Ja"},
    { L_WORD163 ,L"Nee"},
    { L_WORD164 ,L"Doorgaan?"},
    { L_WORD165 ,L"Detail waarschuwingsoverzicht:"},
    { L_WORD166 ,L"Selecteer een tank door op de rij te klikken en de Detail knop te selecteren."},
    { L_WORD167 ,L"< Vorig"},
    { L_WORD168 ,L"Volgende >"},
    { L_WORD169 ,L"Bevestig"},
    { L_WORD170 ,L"Omschrijving"},
    { L_WORD171 ,L"Gestegen"},
    { L_WORD172 ,L"Reset"},
    { L_WORD173 ,L"Geen Alarm"},
    { L_WORD174 ,L"Zet datum (dd.mm.jj)"},
    { L_WORD175 ,L"Zet tijd (uu.mm.ss)"},
    { L_WORD176 ,L"Verkeerd tijdformaat!"},
    { L_WORD177 ,L"Tijdformaat (u.m.s)"},
    { L_WORD178 ,L"Verkeerd datum formaat"},
    { L_WORD179 ,L"Datum formaat (d.m.j)"},
    { L_WORD180 ,L"Nieuwe waarde ingeven:"},
    { L_WORD181 ,L"Geen waarde"},
    { L_WORD182 ,L"Geen sensor(en)"},
    { L_WORD183 ,L"Voer trim in. (Aft is -)"},
    { L_WORD184 ,L"Voer list in. (BB is -)"},
    { L_WORD185 ,L"Voer nieuwe Density in:"},
    { L_WORD186 ,L"0"},
    { L_WORD187 ,L"1"},
    { L_WORD188 ,L"Fout"},
    { L_WORD189 ,L"Auto"},
    { L_WORD190 ,L"Hand"},
    { L_WORD191 ,L"Geen Fout"},
    { L_WORD192 ,L"Input fout"},
    { L_WORD193 ,L"Density fout"},
    { L_WORD194 ,L"RefTmp1=RefTmp2"},
    { L_WORD195 ,L"T15 vastgezet"},
    { L_WORD196 ,L"Verkeerde coeff"},
    { L_WORD197 ,L"Waarde te hoog"},
    { L_WORD198 ,L"Waarde te laag"},
    { L_WORD199 ,L"Gebruik ASTM"},
    { L_WORD200 ,L"Gebruik Density15"},
    { L_WORD201 ,L"Selecteer ASTM tabel"},
    { L_WORD202 ,L"Foute pointer"},
    { L_WORD203 ,L"Foute waarde"},
    { L_WORD204 ,L"Onbekende tank"},
    { L_WORD205 ,L"AD niet gevonden"},
    { L_WORD206 ,L"Geen tmp sensor"},
    { L_WORD207 ,L"Waarde buiten bereik"},
    { L_WORD208 ,L"Gebruik systeem zeewater"},
    { L_WORD209 ,L"Gebruik systeem ballast"},
    { L_WORD210 ,L"Lo temp=Hi temp"},
    { L_WORD211 ,L"Input niet toegestaan"},
    { L_WORD212 ,L"Ongedifinieerde waarde"},
    { L_WORD213 ,L"Voer nogmaals in"},
    { L_WORD214 ,L"Ref Density15 te laag"},
    { L_WORD215 ,L"Ref Density15 te hoog"},
    { L_WORD216 ,L"Ref Density2 te laag"},
    { L_WORD217 ,L"Ref Density2 te hoog"},
    { L_WORD218 ,L"ASTM buiten bereik"},
    { L_WORD219 ,L"Sensor fout"},
    { L_WORD220 ,L"Gain buiten bereik"},
    { L_WORD221 ,L"Gebruik sys drinkwater"},
    { L_WORD222 ,L"Gebruik sys zware stookolie"},
    { L_WORD223 ,L"Gebruik sysdiesel"},
    { L_WORD224 ,L"Gebruik sys smeermiddelen"},
    { L_WORD225 ,L"Laag > Hoog limiet"},
    { L_WORD226 ,L"Hoog < Laag limiet"},
    { L_WORD227 ,L"Hoog = Laag limiet"},
    { L_WORD228 ,L"Niet instelbaar"},
    { L_WORD229 ,L"Geen toegangsrechten"},
    { L_WORD230 ,L"Sensor is uitgeschakeld"},
    { L_WORD231 ,L"Gebruik ASTM53 tabel"},
    { L_WORD232 ,L"Gebruik ASTM54 tabel"},
    { L_WORD233 ,L"Gebruik ref. Density 2"},
    { L_WORD234 ,L"Kan de gemeenschappelijke input niet gebruiken"},
    { L_WORD235 ,L"overschrijven kan alleen wanneer er een alarm is op Pre of Main"},
    { L_WORD236 ,L"Geen Unit"},
    { L_WORD238 ,L"Lengte"},
    { L_WORD239 ,L"Atm/Vapour druk"},
    { L_WORD240 ,L"Lading/Ballast druk"},
    { L_WORD241 ,L"Line pressure"},
    { L_WORD242 ,L"Density coef."},
    { L_WORD243 ,L"Hoek"},
    { L_WORD244 ,L"Vrij oppervlak"},
    { L_WORD245 ,L"Moment"},
    { L_WORD246 ,L"Inzinking"},
    { L_WORD247 ,L"Laadsnelheid"},
    { L_WORD248 ,L"Percentage"},
    { L_WORD249 ,L"GZ area"},
    { L_WORD250 ,L"Huidig"},
    { L_WORD251 ,L"Spanning"},
    { L_WORD252 ,L"Tijd"},
    { L_WORD253 ,L"mSeconden"},
    { L_WORD254 ,L"Dagen"},
    { L_WORD255 ,L"feet"},
    { L_WORD256 ,L"d.feet"},
    { L_WORD257 ,L"m³"},
    { L_WORD258 ,L"Liter"},
    { L_WORD259 ,L"US g."},
    { L_WORD260 ,L"US bls"},
    { L_WORD261 ,L"Ton"},
    { L_WORD262 ,L"l.ton"},
    { L_WORD263 ,L"kN"},
    { L_WORD264 ,L"m³/h"},
    { L_WORD265 ,L"USB/h"},
    { L_WORD266 ,L"°C"},
    { L_WORD267 ,L"°F"},
    { L_WORD268 ,L"mH2O"},
    { L_WORD269 ,L"mmH2O"},
    { L_WORD270 ,L"mBar"},
    { L_WORD271 ,L"Bar"},
    { L_WORD272 ,L"Psi"},
    { L_WORD273 ,L"kPa"},
    { L_WORD274 ,L"InH2O"},
    { L_WORD275 ,L"InHg"},
    { L_WORD276 ,L"t/m³ vac"},
    { L_WORD277 ,L"t/m³ air"},
    { L_WORD278 ,L"lb/uDensity"},
    { L_WORD279 ,L"Deg"},
    { L_WORD280 ,L"Rad"},
    { L_WORD281 ,L"t/m³°C"},
    { L_WORD282 ,L"t/m³°F"},
    { L_WORD283 ,L"l/g/°C"},
    { L_WORD284 ,L"l/g/°F"},
    { L_WORD285 ,L"m^4"},
    { L_WORD286 ,L"Feet^4"},
    { L_WORD287 ,L"t*m"},
    { L_WORD288 ,L"lton*Ft"},
    { L_WORD289 ,L"kNm"},
    { L_WORD290 ,L"t/cm"},
    { L_WORD291 ,L"lton/in"},
    { L_WORD292 ,L"m*Rad"},
    { L_WORD293 ,L"%"},
    { L_WORD294 ,L"‰"},
    { L_WORD295 ,L"mAmp"},
    { L_WORD296 ,L"Amp"},
    { L_WORD297 ,L"Volt"},
    { L_WORD298 ,L"mVolt"},
    { L_WORD299 ,L"mSec"},
    { L_WORD300 ,L"Sec"},
    { L_WORD301 ,L"Min"},
    { L_WORD302 ,L"Uren"},
    { L_WORD303 ,L"Dagen"},
    { L_WORD304 ,L"Niet gebruikt"},
    { L_WORD305 ,L"LevelSns"},
    { L_WORD306 ,L"LevelRef"},
    { L_WORD307 ,L"LevelFC"},
    { L_WORD308 ,L"Sounding"},
    { L_WORD309 ,L"Ullage"},
    { L_WORD310 ,L"Volume%"},
    { L_WORD311 ,L"Druk"},
    { L_WORD312 ,L"Hoge Druk"},
    { L_WORD313 ,L"Lage Druk"},
    { L_WORD314 ,L"Eindtijd"},
    { L_WORD315 ,L"Resttijd"},
    { L_WORD316 ,L"Lading type"},
    { L_WORD317 ,L"Bodem druk"},
    { L_WORD318 ,L"Mid Druk"},
    { L_WORD319 ,L"Bovenste Druk"},
    { L_WORD320 ,L"Top Druk"},
    { L_WORD321 ,L"BP gain"},
    { L_WORD322 ,L"MP gain"},
    { L_WORD323 ,L"UP gain"},
    { L_WORD324 ,L"TP gain"},
    { L_WORD325 ,L"BP Offset"},
    { L_WORD326 ,L"MP Offset"},
    { L_WORD327 ,L"UP Offset"},
    { L_WORD328 ,L"TP Offset"},
    { L_WORD329 ,L"LevS"},
    { L_WORD330 ,L"LevR"},
    { L_WORD331 ,L"LevF"},
    { L_WORD332 ,L"Snd"},
    { L_WORD333 ,L"Ul}"},
    { L_WORD334 ,L"Vo}"},
    { L_WORD335 ,L"Vol%"},
    { L_WORD336 ,L"Wgt"},
    { L_WORD337 ,L"Dens"},
    { L_WORD338 ,L"Temp"},
    { L_WORD339 ,L"Pres"},
    { L_WORD340 ,L"HTmp"},
    { L_WORD341 ,L"LTmp"},
    { L_WORD342 ,L"HoDr"},
    { L_WORD343 ,L"LaDr"},
    { L_WORD344 ,L"Lsnelheid"},
    { L_WORD345 ,L"FTim"},
    { L_WORD346 ,L"RTim"},
    { L_WORD347 ,L"Ltyp"},
    { L_WORD348 ,L"BP"},
    { L_WORD349 ,L"MP"},
    { L_WORD350 ,L"UP"},
    { L_WORD351 ,L"TP"},
    { L_WORD352 ,L"BPGn"},
    { L_WORD353 ,L"MPGn"},
    { L_WORD354 ,L"UPGn"},
    { L_WORD355 ,L"TPGn"},
    { L_WORD356 ,L"BPOf"},
    { L_WORD357 ,L"MPOf"},
    { L_WORD358 ,L"UPOf"},
    { L_WORD359 ,L"TPOf"},
    { L_WORD360 ,L"Bodem Temp"},
    { L_WORD361 ,L"Mid Temp"},
    { L_WORD362 ,L"Boven Temp"},
    { L_WORD363 ,L"Top Temp"},
    { L_WORD364 ,L"BT"},
    { L_WORD365 ,L"MT"},
    { L_WORD366 ,L"UT"},
    { L_WORD367 ,L"TT"},
    { L_WORD368 ,L"Atm sensor"},
    { L_WORD369 ,L"Power 24V(1)"},
    { L_WORD370 ,L"Power 24V(2)"},
    { L_WORD371 ,L"Power 3.3V"},
    { L_WORD372 ,L"Power 1.8V"},
    { L_WORD373 ,L"OS Status"},
    { L_WORD374 ,L"geheugen status"},
    { L_WORD375 ,L"Taaknaam"},
    { L_WORD376 ,L"draaitijd"},
    { L_WORD377 ,L"Power 5.0V"},
    { L_WORD378 ,L"Power 12V"},
    { L_WORD379 ,L"Com kanaal"},
    { L_WORD380 ,L"Com Versie"},
    { L_WORD381 ,L"opgeslagen ver."},
    { L_WORD382 ,L"Rx Buf Size"},
    { L_WORD383 ,L"Tx Buf Size"},
    { L_WORD384 ,L"Reset Status"},
    { L_WORD385 ,L"Total Restart"},
    { L_WORD386 ,L"fout teller"},
    { L_WORD387 ,L"totaal fout teller"},
    { L_WORD388 ,L"Programma"},
    { L_WORD389 ,L"Power 24V"},
    { L_WORD390 ,L"Serienummer"},
    { L_WORD391 ,L"Unit status"},
    { L_WORD392 ,L"Card status"},
    { L_WORD393 ,L"Lading naam"},
    { L_WORD394 ,L"VolCorrFactor"},
    { L_WORD395 ,L"VCF@15"},
    { L_WORD396 ,L"Gemeten ASTM"},
    { L_WORD397 ,L"Comp. Density"},
    { L_WORD398 ,L"Ref. Density15"},
    { L_WORD399 ,L"Ref.Density2"},
    { L_WORD400 ,L"Ref. Temp15"},
    { L_WORD401 ,L"Ref. Temp2"},
    { L_WORD402 ,L"Niet gedefinieerd"},
    { L_WORD403 ,L"Eenvoudig"},
    { L_WORD404 ,L"AtmPress"},
    { L_WORD405 ,L"Ballast"},
    { L_WORD406 ,L"HFO"},
    { L_WORD407 ,L"Diesel"},
    { L_WORD408 ,L"Smeermiddelen"},
    { L_WORD409 ,L"Drinkwater"},
    { L_WORD410 ,L"Zeewater"},
    { L_WORD411 ,L"API 6A"},
    { L_WORD412 ,L"API 6B"},
    { L_WORD413 ,L"API 6D"},
    { L_WORD414 ,L"API 53A"},
    { L_WORD415 ,L"API 53B"},
    { L_WORD416 ,L"API 53D"},
    { L_WORD417 ,L"API 54A"},
    { L_WORD418 ,L"API 54B"},
    { L_WORD419 ,L"API 54D"},
    { L_WORD420 ,L"DF"},
    { L_WORD421 ,L"DP"},
    { L_WORD422 ,L"DS"},
    { L_WORD423 ,L"DA"},
    //{ L_WORD424 ,L"Niveau"},
    { L_WORD425 ,L"Trim in graden"},
    { L_WORD426 ,L"Trim in meter"},
    { L_WORD427 ,L"List in graden"},
    { L_WORD428 ,L"DF (User select)"},
    { L_WORD429 ,L"DA (User select)"},
    { L_WORD430 ,L"DF@Mark"},
    { L_WORD431 ,L"DA@Mark"},
    { L_WORD432 ,L"DF@PP"},
    { L_WORD433 ,L"DA@PP"},
    { L_WORD434 ,L"Aan/Uit"},
    { L_WORD435 ,L"Systeem data"},
    { L_WORD436 ,L"Diepgang"},
    { L_WORD437 ,L"Ladingtank"},
    { L_WORD438 ,L"Andere Tanks"},
    { L_WORD439 ,L"FRO"},
    { L_WORD440 ,L"G1"},
    { L_WORD441 ,L"G2"},
    { L_WORD442 ,L"G3"},
    { L_WORD443 ,L"NL1"},
    { L_WORD444 ,L"NL2"},
    { L_WORD445 ,L"Niveau"},
    { L_WORD446 ,L"Gemeten Density"},
    { L_WORD447 ,L"List in meter"},
    { L_WORD448 ,L"Latitude"},
    { L_WORD449 ,L"Type"},
    { L_WORD450 ,L"SnsDB"},
    { L_WORD451 ,L"Plaats"},
    { L_WORD452 ,L"Min bereik"},
    { L_WORD453 ,L"Max bereik"},
    { L_WORD454 ,L"Kabellengte"},
    { L_WORD455 ,L"TCUAdres"},
    { L_WORD456 ,L"Poort"},
    { L_WORD457 ,L"IOAdres"},
    { L_WORD458 ,L"Kanaal"},
    { L_WORD459 ,L"ADCardChn"},
    { L_WORD460 ,L"Trim"},
    { L_WORD461 ,L"List"},
    { L_WORD462 ,L"Zwart"},
    { L_WORD463 ,L"Donker grijs"},
    { L_WORD464 ,L"Licht grijs"},
    { L_WORD465 ,L"Wit"},
    { L_WORD466 ,L"Blauw"},
    { L_WORD467 ,L"Print"},
    { L_WORD468 ,L"S"/*Status*/},
    { L_WORD469 ,L"gebruik bls"},
    { L_WORD470 ,L"Gebruik m³"},
    { L_WORD471 ,L"Droog"},
    { L_WORD472 ,L"--.-"},
    { L_WORD473 ,L"Leeg"},
    { L_WORD474 ,L"*****"   /*vaste lengte!*/},
    { L_WORD475 ,L"Hoofd"},
    { L_WORD476 ,L"Voor"},
    { L_WORD477 ,L"Overvul"},
    { L_WORD478 ,L"Prot"},
    { L_WORD479 ,L"Com"},
    { L_WORD480 ,L"(Rx/Tx)"},
    { L_WORD481 ,L"op TCU:"},
    { L_WORD482 ,L"op ZB485:"},
    { L_WORD483 ,L"BootLoader"},
    { L_WORD484 ,L"Applicatie"},
    { L_WORD485 ,L"Onbekend"},
    { L_WORD486 ,L"Geen"},
    { L_WORD487 ,L"Fout"},
    { L_WORD488 ,L"NoUs"},
    { L_WORD489 ,L"Andere"},
    { L_WORD490 ,L"Druk"},
    { L_WORD493 ,L"Niet actief"},
    { L_WORD494 ,L"Actief"},
    { L_WORD495 ,L"Bevestig"},
    { L_WORD496 ,L"Limiet:"},
    { L_WORD497 ,L"Waarde:"},
    { L_WORD498 ,L"Pointer Fout"},
    { L_WORD499 ,L"Unk."},
    { L_WORD500 ,L"BuitenBereik"},
    { L_WORD501 ,L"ComFout"},
    { L_WORD502 ,L"Hniv"},
    { L_WORD503 ,L"Hoogniveau"},
    { L_WORD504 ,L"Hoge lijn druk"},
    { L_WORD505 ,L"Hldruk"},
    { L_WORD506 ,L"Hoge druk"},
    { L_WORD507 ,L"Hdruk"},
    { L_WORD508 ,L"Hoge temp"},
    { L_WORD509 ,L"Htmp"},
    { L_WORD510 ,L"Hoge spanning"},
    { L_WORD511 ,L"Hspan"},
    { L_WORD512 ,L"Hogedruk 1"},
    { L_WORD513 ,L"Hdruk 1"},
    { L_WORD514 ,L"Lagedruk 1"},
    { L_WORD515 ,L"Ldruk1"},
    { L_WORD516 ,L"Com fout"},
    { L_WORD517 ,L"IOErr"},
    { L_WORD518 ,L"Laag niveau"},
    { L_WORD519 ,L"Lniv"},
    { L_WORD520 ,L"Lage lijn druk"},
    { L_WORD521 ,L"Lldruk"},
    { L_WORD522 ,L"Lage druk"},
    { L_WORD523 ,L"Ldruk"},
    { L_WORD524 ,L"Lage temp"},
    { L_WORD525 ,L"Ltmp"},
    { L_WORD526 ,L"Lage spanning"},
    { L_WORD527 ,L"Lspan"},
    { L_WORD528 ,L"Fout"},
    { L_WORD529 ,L"hoofdwatersysteem"},
    { L_WORD530 ,L"Mwat"},
    { L_WORD531 ,L"OpenLoop"},
    { L_WORD532 ,L"Overvul"},
    { L_WORD534 ,L"Ovul"},
    { L_WORD535 ,L"PreWater"},
    { L_WORD536 ,L"Pwat"},
    { L_WORD537 ,L"BereikFout"},
    { L_WORD538 ,L"ADFout"},
    { L_WORD539 ,L"Cnv&Cal Error"},
    { L_WORD540 ,L"HWFout"},
    { L_WORD541 ,L"Conv Fout"},
    { L_WORD542 ,L"Ra Fout"},
    { L_WORD543 ,L"Kortsluiting"},
    { L_WORD544 ,L"Kortsl"},
    { L_WORD545 ,L"Details"},
    { L_WORD546 ,L"Calibratie Data"},
    { L_WORD547 ,L"SerNum"},
    { L_WORD548 ,L"Bereik"},
    { L_WORD549 ,L"CalData Source"},
    { L_WORD550 ,L"Niveau offset"},
    { L_WORD551 ,L"Inclinometer"},
    { L_WORD552 ,L"Diepgang"},
    { L_WORD553 ,L"Gemeten"},
    { L_WORD554 ,L"ch"},
    { L_WORD555 ,L"Loc"},
    { L_WORD556 ,L"RawVa}"},
    { L_WORD557 ,L"CalVa}"},
    { L_WORD558 ,L"CnvCalE"},
    { L_WORD559 ,L"PROM"},
    { L_WORD560 ,L"PC"},
    { L_WORD561 ,L"TCUCa}"},
    { L_WORD562 ,L"AD Sns"},
    { L_WORD563 ,L"TCU Sns"},
    { L_WORD564 ,L"Van TCU"},
    { L_WORD565 ,L"Groen"},
    { L_WORD566 ,L"Wissen geheugen"},
    { L_WORD567 ,L"Info"},
    { L_WORD568 ,L"Wis Fout"},
    { L_WORD569 ,L"Programma updating"},
    { L_WORD570 ,L"Looptijd calibratie"},
    { L_WORD571 ,L"Stoppen"},
    { L_WORD572 ,L"Druk hier"},
    { L_WORD573 ,L"(linksboven positie)"},
    { L_WORD574 ,L"(rechtsonder positie)"},
    { L_WORD575 ,L"Bladzijde"},
    { L_WORD576 ,L"Data versie"},
    { L_WORD577 ,L"Ladingtanks"},
    { L_WORD578 ,L"Ballasttanks"},
    { L_WORD579 ,L"Service tanks"},
    { L_WORD580 ,L"Zware stookolie tanks"},
    { L_WORD581 ,L"Dieselolie tanks"},
    { L_WORD582 ,L"Smeermiddelen tanks"},
    { L_WORD583 ,L"Miscellaneous tanks"},
    { L_WORD584 ,L"Drinkwater tanks"},
    { L_WORD585 ,L"NotDef"},
    { L_WORD586 ,L"Atm"},
    { L_WORD587 ,L"Bodem"},
    { L_WORD588 ,L"Midden"},
    { L_WORD589 ,L"Boven"},
    { L_WORD590 ,L"TankDruk"},
    { L_WORD591 ,L"PumpKm"},
    { L_WORD592 ,L"MachKm"},
    { L_WORD593 ,L"Dek"},
    { L_WORD594 ,L"Dek"},
    { L_WORD595 ,L"Lijn"},
    { L_WORD596 ,L"WIMain"},
    { L_WORD597 ,L"WIPre"},
    { L_WORD598 ,L"Inc"},
    { L_WORD599 ,L"LSw"},
    { L_WORD600 ,L"Rad"},
    { L_WORD601 ,L"WIng"},
    { L_WORD602 ,L"Nul stellen tank druk!"},
    { L_WORD603 ,L"De tanks moeten geventileerd worden met de atmosfeer. Dit geldt voor alle tanks in de groep."},
    { L_WORD604 ,L"Nul stellen sensor(en)!"},
    { L_WORD605 ,L"De tank moet leeg zijn en tank cleaning  heeft gedurende 30 minuten niet plaatDensityevonden. Deze handeling geldt voor alle tanks in"},
    { L_WORD606 ,L"Zeroset waarschuwing:"},
    { L_WORD607 ,L"De tanks moeten geventileerd worden met de atmosfeer. Dit geldt voor alle tank druksensoren."},
    { L_WORD608 ,L"De tank moet leeg zijn en tank cleaning  heeft gedurende 30 minuten niet plaatDensityevonden. Deze handeling geldt voor alle druksenso"},
    { L_WORD609 ,L"Heavy Fuel Density"},
    { L_WORD610 ,L"Dieselolie Density"},
    { L_WORD611 ,L"Smeermiddelen Density"},
    { L_WORD612 ,L"Drinkwater Density"},
    { L_WORD613 ,L"File beschadigd"},
    { L_WORD614 ,L"fout in UNICODE string"},
    { L_WORD615 ,L"F"},
    { L_WORD616 ,L"A"},
    { L_WORD617 ,L"P"},
    { L_WORD618 ,L"S"},
    { L_WORD619 ,L"Gelijk maken"},
    { L_WORD620 ,L"Printer op deze TDU"},
    { L_WORD621 ,L"Temperaturen"},
    { L_WORD622 ,L"Line pressures"},
    { L_WORD623 ,L"Tank drukken"},
    { L_WORD624 ,L"CnvCal"},
    { L_WORD625 ,L"CnvErr"},
    { L_WORD626 ,L"CalErr"},
    { L_WORD627 ,L"TDU"},
    { L_WORD628 ,L"PC"},
    { L_WORD629 ,L"TCU"},
    { L_WORD630 ,L"ANPro3"},
    { L_WORD631 ,L"ANPro10"},
    { L_WORD632 ,L"IOsystem"},
    { L_WORD633 ,L"ZB_Red"},
    { L_WORD634 ,L"Wago"},
    { L_WORD635 ,L"TPCx"},
    { L_WORD636 ,L"Printer"},
    { L_WORD637 ,L"ANPro1"},
    { L_WORD638 ,L"ANPro3"},
    { L_WORD639 ,L"ANPro10"},
    { L_WORD640 ,L"Modbus"},
    { L_WORD641 ,L"Printer"},
    { L_WORD642 ,L"Void space"},
    { L_WORD643 ,L"Nul stellen void space\n druk sensor voor\n alle void spaces"},
    { L_WORD644 ,L"Nul stellen niveau\n sensor(s) voor\n alle void spaces"},
    { L_WORD646 ,L"Gebruik de huidige dichtheid instellingen voor alle void spaces"},
    { L_WORD647 ,L"Gebruik de huidige alarm instellingen voor alle void spaces"},
    { L_WORD648 ,L"Lekkage"},
    { L_WORD649 ,L"Lekkage"},
    { L_WORD650 ,L"Wacht SVP"},
    { L_WORD651 ,L"Wacht"},
    { L_WORD652 ,L"DST"},
    { L_WORD653 ,L"24V"},
    { L_WORD654 ,L"In#1"},
    { L_WORD655 ,L"In#2"},
    { L_WORD656 ,L"Het systeem wordt aangepast aan de ingevoerde waarde. Incorrecte invoer kan de werking van het systeem beïnvloeden."},
    { L_WORD657 ,L"Waarschuwing! Niveau wordt aangepast"},
    { L_WORD658 ,L"Waarschuwing! Sounding wordt aangepast"},
    { L_WORD659 ,L"Waarschuwing! Ullage wordt aangepast"},
    { L_WORD660 ,L"Waarschuwing! Volume wordt aangepast"},
    { L_WORD661 ,L"Waarschuwing! Gewicht wordt aangepast"},
    { L_WORD662 ,L"De beschermplaat moet op de sensor worden gemonteerd."},
    { L_WORD663 ,L"De beschermplaat moet van de sensor worden gedemonteerd."},
    { L_WORD664 ,L"Voer Pin code in:"},
    { L_WORD665 ,L"Voer nieuwe pin code in:"},
    { L_WORD666 ,L"Screen saver tijd"},
    { L_WORD667 ,L"Alarm vertragingstijd"},
    { L_WORD668 ,L"Voer oude pin code in:"},
    { L_WORD669 ,L"Voer de nieuwe pin code nogmaals in:"},
    { L_WORD670 ,L"ComErr Id"},
    { L_WORD671 ,L"ComErr Cmd"},
    { L_WORD672 ,L"ComErr MDensity"},
    { L_WORD673 ,L"ComErr Cnt"},
    { L_WORD674 ,L"ComErr Time"},
    { L_WORD675 ,L"Opdracht"},
    { L_WORD676 ,L"Object"},
    { L_WORD677 ,L"Niveau"},
    { L_WORD678 ,L"Lv}"},
    { L_WORD679 ,L"Displacement"},
    { L_WORD680 ,L"LCG"},
    { L_WORD681 ,L"TCG"},
    { L_WORD682 ,L"VCG"},
    { L_WORD683 ,L"List in meter"},
    { L_WORD684 ,L"Draft Mid"},
    { L_WORD685 ,L"Gewicht vloeistof"},
    { L_WORD686 ,L"Gewicht vaste stof"},
    { L_WORD687 ,L"Draft BB"},
    { L_WORD688 ,L"TFS Moment"},
    { L_WORD689 ,L"L moment"},
    { L_WORD690 ,L"T moment"},
    { L_WORD691 ,L"V moment"},
    { L_WORD692 ,L"VCG Solids"},
    { L_WORD693 ,L"VCG adjust"},
    { L_WORD694 ,L"Max VCG"},
    { L_WORD695 ,L"VCG margin"},
    { L_WORD696 ,L"Dam.max VCG"},
    { L_WORD697 ,L"Dam. VCG marg."},
    { L_WORD698 ,L"Inzinking"},
    { L_WORD699 ,L"KM"},
    { L_WORD700 ,L"GM solid"},
    { L_WORD701 ,L"GM liquid"},
    { L_WORD702 ,L"TCF"},
    { L_WORD703 ,L"LCF"},
    { L_WORD704 ,L"TCG"},
    { L_WORD705 ,L"LCG"},
    { L_WORD706 ,L"GZ"},
    { L_WORD707 ,L"GZ30"},
    { L_WORD708 ,L"GZ max"},
    { L_WORD709 ,L"GZ hoek"},
    { L_WORD710 ,L"GZ a0-30"},
    { L_WORD711 ,L"GZ a30-40"},
    { L_WORD712 ,L"Flooding angle"},
    { L_WORD713 ,L"Deadweight"},
    { L_WORD714 ,L"LCB"},
    { L_WORD715 ,L"MaxBM@"},
    { L_WORD716 ,L"MaxSF@"},
    { L_WORD717 ,L"Frame"},
    { L_WORD718 ,L"Buig.Mom."},
    { L_WORD719 ,L"Shr.Forc."},
    { L_WORD720 ,L"Cor.BMom"},
    { L_WORD721 ,L"APP dist."},
    { L_WORD722 ,L"Vorige lijst"},
    { L_WORD723 ,L"BMomHrb"},
    { L_WORD724 ,L"BMomSea"},
    { L_WORD725 ,L"SForceHrb"},
    { L_WORD726 ,L"SForceSea"},
    { L_WORD727 ,L"SteelWgt"},
    { L_WORD728 ,L"Drijfvermogen"},
    { L_WORD729 ,L"Laad"},
    { L_WORD730 ,L"Mom.Change"},
    { L_WORD731 ,L"Avg BMom"},
    { L_WORD732 ,L"Avg SForce"},
    { L_WORD733 ,L"Vaste"},
    { L_WORD734 ,L"Diepgang Voor"},
    { L_WORD735 ,L"Diepgang BB"},
    { L_WORD736 ,L"Diepgang SB"},
    { L_WORD737 ,L"Diepgang Achter"},
    { L_WORD738 ,L"TFree Surf."},
    { L_WORD739 ,L"FreeSMom."},
    { L_WORD740 ,L"GZ a0-40"},
    { L_WORD741 ,L"Constant solids"},
    { L_WORD742 ,L"Variable Solids"},
    { L_WORD743 ,L"VCF"},
    { L_WORD744 ,L"Vol15"},
    { L_WORD745 ,L"V@RT"},
    { L_WORD746 ,L"Bytes:"},
    { L_WORD747 ,L"Niveau verschil"},
    { L_WORD748 ,L"Ldif"},
    { L_WORD749 ,L"Bodem1"},
    { L_WORD750 ,L"Bodem2"},
    { L_WORD751 ,L"Bodem3"},
    { L_WORD752 ,L"Bodem4"},
    { L_WORD753 ,L"Bodem5"},
    { L_WORD754 ,L"BP1"},
    { L_WORD755 ,L"BP2"},
    { L_WORD756 ,L"BP3"},
    { L_WORD757 ,L"BP Gain1"},
    { L_WORD758 ,L"BP Gain2"},
    { L_WORD759 ,L"BP Gain3"},
    { L_WORD760 ,L"BP Offset1"},
    { L_WORD761 ,L"BP Offset1"},
    { L_WORD762 ,L"BP Offset1"},
    { L_WORD763 ,L"Fout adres"},
    { L_WORD764 ,L"Online"},
    { L_WORD765 ,L"Offline"},
    { L_WORD766 ,L"Online Status"},
    { L_WORD767 ,L"Schip rechtop"},
    { L_WORD768 ,L"Trimhoek"},
    { L_WORD769 ,L"List hoek"},
    { L_WORD770 ,L"Fabrieksinstelling"},
    { L_WORD771 ,L"TDUce"},
    { L_WORD772 ,L"Updating configuratie"},
    { L_WORD773 ,L"Voortgang"},
    { L_WORD774 ,L"Hoog"},
    { L_WORD775 ,L"Laag"},
    { L_WORD776 ,L"Capaciteit"},
    { L_WORD777 ,L"Cap"},
    { L_WORD798 ,L"HiLev Aan"},
    { L_WORD799 ,L"LoLev Aan"},
    { L_WORD808 ,L"Alarm limieten"},
    { L_WORD809 ,L"Alarm Aan/Uit"},
    { L_WORD810 ,L"Sensor waarden"},
    { L_WORD821 ,L"Dubbele naam"},
    { L_WORD851 ,L"GeenSensor"},
    { L_WORD852 ,L"Uitgeschakeld"},
    { L_WORD854 ,L"Zeegaan"},
    { L_WORD855 ,L"Tank schoonmaken"},
    { L_WORD858 ,L"Ongedefinieerd"},
    { L_WORD859 ,L"Schoonmaken"},
    { L_WORD860 ,L"Laden"},
    { L_WORD861 ,L"Lossen"},
    { L_WORD862 ,L"WAARSCHUWING: Ja selecteren zal alle Hi-level sensoren uitschakelen."},
    { L_WORD863 ,L"Gebruiker"},
    { L_WORD865 ,L"Dubbele naam"},
    { L_WORD866 ,L"Level change"},
    { L_WORD868 ,L"Aanpassen"},
    { L_WORD870 ,L"Lading tank"},
    { L_WORD871 ,L"Ballast tank"},
    { L_WORD872 ,L"Service tank"},
    { L_WORD873 ,L"Heavy Fuel Olie tank"},
    { L_WORD874 ,L"Diesel Olie tank"},
    { L_WORD875 ,L"Smeermiddelen tank"},
    { L_WORD876 ,L"Drinkwater tank"},
    { L_WORD877 ,L"Overige tanks"},
    { L_WORD878 ,L"Voer niveau offset in"},
    { L_WORD879 ,L"Voer sensor offset in"},
    { L_WORD880 ,L"U staat op het punt de offset van de sensor te veranderen. Dit zal de nauwkeurigheid beinvloeden."},
    { L_WORD881 ,L"U staat op het punt de offset van het niveau te veranderen. Dit zal de nauwkeurigheid beinvloeden."},
    { L_WORD882 ,L"Redundant"},
    { L_WORD883 ,L"Radar drempel"},
    { L_WORD889 ,L"Zekering"},
    { L_WORD892 ,L"Kapot"},
    { L_WORD893 ,L"Tanks"},
    { L_WORD894 ,L"Gebruik huidige Density voor alle tanks"},
    { L_WORD895 ,L"Gebruik huidige alarm settings voor alle tanks"},
    { L_WORD896 ,L"Olie"},
    { L_WORD897 ,L"Power"},
    { L_WORD898 ,L"Lage Spanning"},
    { L_WORD899 ,L"X Hoge Druk"},
    { L_WORD900 ,L"X Lage Druk"},
    { L_WORD907 ,L"Max list BB"},
    { L_WORD908 ,L"Max list SB"},
    { L_WORD909 ,L"Frequentie"},
    { L_WORD912 ,L"Aanpasbaar"},
    { L_WORD920 ,L"Schrijf\nconfig file"},
    { L_WORD921 ,L"Gebruik ASTM59 tabel"},
    { L_WORD922 ,L"Gebruik ASTM60 tabel"},
    { L_WORD923 ,L"ASTM 59A"},
    { L_WORD924 ,L"ASTM 59B"},
    { L_WORD925 ,L"ASTM 59D"},
    { L_WORD926 ,L"ASTM 60A"},
    { L_WORD927 ,L"ASTM 60B"},
    { L_WORD928 ,L"ASTM 60D"},
    { L_WORD929 ,L"Test"},
    { L_WORD930 ,L"Tst"},
    { L_WORD931 ,L"Licht"},
    { L_WORD932 ,L"Lcht"},
    { L_WORD937 ,L"Invoer"},
    { L_WORD943 ,L"VapourWeight"},
    { L_WORD944 ,L"Liquid Gas Weight"},
    { L_WORD945 ,L"VapWgt"},
    { L_WORD946 ,L"LGWgt"},
};

unsigned WordsInDutchDictionary = NELEMENTS(DutchDictionary);

wchar_t DutchUserManual[] = {L"           User manual for TDU\n\
\n\
Voor volledige informatie over het systeem verwijzen wij naar het installatie instructie en bedieningshandleiding.\n\
\n\
Dit touch screen moet worden bediend worden met een stylus pen of met de vingen. Ander apparatuur/gereedschap zal het scherm beschadigen.\n\
\n\
NOTE:\n\
Voordat U het systeem gebruikt dient u de gebruiksaanwijzing en bedieningsinstructie te bestuderen en begrepen te worden.\n\
\n\
Het is sterk aanbevolen dat u de werking van het Density begrijpt.\n\
Verkeerde ingave van Density kan tot overbelading of andere schade leiden.\n\
\n\
De gebruiksaanwijzing en reserveonderdelen kunnen worden besteld bij:\n\
\n\
Henri Systems Holland\n\
Scheepsmakersstraat 33\n\
3334 KG Zwijndrecht \n\
Nederland \n\
\n\
Tel: +31 78 6100 999\n\
Service: +31 78 6100 999\n\
Fax: +31 78 6103 214\n\
E-mail: info@hsh.nl\n\
Web: www.hsh.nl\n\
"};

int SizeOfDutchUserManual= sizeof(DutchUserManual);

