#include "TSNIncludes.h"
#pragma hdrstop
//---------------------------------------------------------------------------
NewLanguageWord EnglishDictionary[]=
{
//  { Keyword   ,English (0)
    { L_WORD0   ,L"FEIL-FEIL-"},
    { L_WORD1   ,L"применить"},
    { L_WORD2   ,L"отменить"},
    { L_WORD3   ,L"вкл"},
    { L_WORD4   ,L"выкл"},
    { L_WORD5   ,L"принтер"},
    { L_WORD6   ,L"язык:"},
    { L_WORD7   ,L"оповещения"},
    { L_WORD8   ,L"обмен балласта"},
    { L_WORD9   ,L"груз"},
    { L_WORD10  ,L"сервис"},
    { L_WORD11  ,L"температура"},
    { L_WORD12  ,L"давление в танке"},
    { L_WORD13  ,L"выбор записи:"},
    { L_WORD14  ,L"время записи"},
    { L_WORD15  ,L"часы"},
    { L_WORD16  ,L"установка принтера"},
    { L_WORD17  ,L"открыть"},
    { L_WORD18  ,L"закрыть"},
    { L_WORD19  ,L"период записи"},
    { L_WORD20  ,L"стр 1 системы"},
    { L_WORD21  ,L"инструкция пользователя"},
    { L_WORD22  ,L"установка"},
    { L_WORD23  ,L"принтер"},
    { L_WORD24  ,L"версия программы"},
    { L_WORD25  ,L"версия данных:"},
    { L_WORD26  ,L"ID системы:"},
    { L_WORD27  ,L"Unit System:"},
    { L_WORD28  ,L"язык"},
    { L_WORD29  ,L"GMT"},
    { L_WORD30  ,L"стр 2 системы"},
    { L_WORD31  ,L"атмосферное"},
    { L_WORD32  ,L"метр"},
    { L_WORD33  ,L"источник осадки:"},
    { L_WORD34  ,L"градус"},
    { L_WORD35  ,L"осадка:"},
    { L_WORD36  ,L"секция"},
    { L_WORD37  ,L"забортная вода"},
    { L_WORD38  ,L"источник крена:"},
    { L_WORD39  ,L"стр 3 системы: секции ввода/вывода"},
    { L_WORD40  ,L"выбрать:"},
    { L_WORD41  ,L"стр 4 системы: секции ПО"},
    { L_WORD42  ,L"стр 5 системы"},
    { L_WORD43  ,L"всего во всех танках"},
    { L_WORD44  ,L"объем"},
    { L_WORD45  ,L"вес"},
    { L_WORD46  ,L"вода"},
    { L_WORD47  ,L"балласт"},
    { L_WORD48  ,L"тяжелое ДТ"},
    { L_WORD49  ,L"ДТ"},
    { L_WORD50  ,L"ГСМ"},
    { L_WORD51  ,L"пресная вода"},
    { L_WORD52  ,L"разное"},
    { L_WORD53  ,L"итого"},
    { L_WORD54  ,L"стр установки системы"},
    { L_WORD55  ,L"скринсейвер:"},
    { L_WORD56  ,L"минуты"},
    { L_WORD57  ,L"задержка выкл сигнализации:"},
    { L_WORD58  ,L"секунды"},
    { L_WORD59  ,L"узел SI"},
    { L_WORD60  ,L"узел US"},
    { L_WORD61  ,L"установка цвета:"},
    { L_WORD62  ,L"фон"},
    { L_WORD63  ,L"передний план"},
    { L_WORD64  ,L"яркость:"},
    { L_WORD65  ,L"зуммер /\nтест освещения"},
    { L_WORD66  ,L"изменить ПИН-код"},
    { L_WORD67  ,L"калибровка экрана"},
    { L_WORD68  ,L"EEPROM"},
    { L_WORD69  ,L"установка приложения"},
    { L_WORD70  ,L"Col. 1"},
    { L_WORD71  ,L"Col. 2"},
    { L_WORD72  ,L"Col. 3"},
    { L_WORD73  ,L"Col. 4"},
    { L_WORD74  ,L"имя "},
    { L_WORD75  ,L")0 регулировка танка\датчик давления\все балластные танки."},
    { L_WORD76  ,L"0 уровень регулировки\датчик для\все балластные танки."},
    { L_WORD77  ,L"полтность балластной воды"},
    { L_WORD78  ,L"0 регулировка танка\датчик давления\все балластные танки."},
    { L_WORD79  ,L"0 уровень регулировки\датчик для\все балластные танки."},
    { L_WORD80  ,L"плотность для:"},
    { L_WORD81  ,L"0 регулировка танка\датчик давления\все точки балластных танков."},
    { L_WORD82  ,L"общий ввод для всех балластных танков"},
    { L_WORD83  ,L"плотность"},
    { L_WORD84  ,L"ошибка конфигурации"},
    { L_WORD85  ,L"текст"},
    { L_WORD86  ,L"продолжать"},
    { L_WORD87  ,L"стр вверх"},
    { L_WORD88  ,L"стр вниз"},
    { L_WORD89  ,L"установка приложения"},
    { L_WORD90  ,L"детали"},
    { L_WORD91  ,L"неизветсная ошибка конфигурации."},
    { L_WORD92  ,L"линия давления груза"},
    { L_WORD93  ,L"возвратная линия пара"},
    { L_WORD94  ,L"обнаружение протечки"},
    { L_WORD95  ,L"выключатель уровня"},
    { L_WORD96  ,L"система"},
    { L_WORD97  ,L"сигнализация"},
    { L_WORD98  ,L"прмиенить группу"},
    { L_WORD99  ,L"не сконфигурировано"},
    { L_WORD100 ,L"не используется"},
    { L_WORD101 ,L"линейный"},
    { L_WORD102 ,L"API / ASTM-IP"},
    { L_WORD103 ,L"использовать измеренную плотность"},
    { L_WORD104 ,L"исходная температура"},
    { L_WORD105 ,L"использовать исходную плотность"},
    { L_WORD106 ,L"исходная 1"},
    { L_WORD107 ,L"исходная 2"},
    { L_WORD108 ,L"коэффициент"},
    { L_WORD109 ,L"переполнение"},
    { L_WORD110 ,L"высокий уровень"},
    { L_WORD111 ,L"низкий уровень"},
    { L_WORD112 ,L"высокая температура"},
    { L_WORD113 ,L"низкая температура"},
    { L_WORD114 ,L"высокое давление танка"},
    { L_WORD115 ,L"низкое давление танка"},
    { L_WORD116 ,L"0 регулировка танка \датчик давления"},
    { L_WORD117 ,L"0 уровень регулировки \датчк(и)."},
    { L_WORD118 ,L"уровень регулировки"},
    { L_WORD119 ,L"регулировка звука"},
    { L_WORD120 ,L"регулировка факт кол-во жидкости"},
    { L_WORD121 ,L"регулировка объема"},
    { L_WORD122 ,L"регулировка веса"},
    { L_WORD123 ,L"разблокировать"},
    { L_WORD124 ,L"расположение"},
    { L_WORD125 ,L"Ena"},
    { L_WORD126 ,L"прирост"},
    { L_WORD127 ,L"офсет"},
    { L_WORD128 ,L"значение"},
    { L_WORD129 ,L"новое значение"},
    { L_WORD130 ,L"подтвердить действие"},
    { L_WORD131 ,L"применить текущие настройки плотности ко всем грузовым танкам."},
    { L_WORD132 ,L"применить текущие настройки плотности ко всем балластным танкам."},
    { L_WORD133 ,L"применить текущие настройки плотности ко всем сервисным танкам."},
    { L_WORD134 ,L"новый предел сигнализации"},
    { L_WORD135 ,L"применить текущие настройки сигнализации ко всем грузовым танкам."},
    { L_WORD136 ,L"применить текущие настройки сигнализации ко всем балластным танкам"},
    { L_WORD137 ,L"применить текущие настройки сигнализации ко всем сервисным танкам"},
    { L_WORD138 ,L"применить текущие настройки сигнализации ко всем давлениям танков"},
    { L_WORD139 ,L"применить текущие настройки сигнализации ко всем температурным точкам"},
    { L_WORD140 ,L"0 датчик регулировки"},
    { L_WORD141 ,L"Tдатчик нуждается в вентиляции"},
    { L_WORD142 ,L"0 регулировка датчиков уровня!"},
    { L_WORD143 ,L"танк следует опорожнить и не производить чистку в последующие 30 мин."},
    { L_WORD144 ,L"защитная плита!"},
    { L_WORD145 ,L"видимый уровень"},
    { L_WORD146 ,L"наблюдаемое зондирование"},
    { L_WORD147 ,L"наблюдаемая протечка"},
    { L_WORD148 ,L"наблюдаемый объем"},
    { L_WORD149 ,L"наблюдаемый вес"},
    { L_WORD150 ,L"введите ПИН-код:"},
    { L_WORD151 ,L"установить приращение датчика"},
    { L_WORD152 ,L"установить значение датчика"},
    { L_WORD153 ,L"предупреждение"},
    { L_WORD154 ,L"вы собираетесь изменить приращение датчика. это изменит погрешность!"},
    { L_WORD155 ,L"вы собираетесь изменить занчени датчика. это изменит погрешность!"},
    { L_WORD156 ,L"нулевое регулирование"},
    { L_WORD157 ,L"значения датчика"},
    { L_WORD158 ,L"высокое линейное давлние"},
    { L_WORD159 ,L"низкое линейное давление"},
    { L_WORD160 ,L"нулевая регулировка линии \nдавление датчика},
    { L_WORD161 ,L"OK"},
    { L_WORD162 ,L"да"},
    { L_WORD163 ,L"нет"},
    { L_WORD164 ,L"проджолжить?"},
    { L_WORD165 ,L"предупреждение отображения Подробности:"},
    { L_WORD166 ,L"выберите танк нахатием ряда и кнопки Подробности."},
    { L_WORD167 ,L"<предыдущий"},
    { L_WORD168 ,L"следующий >"},
    { L_WORD169 ,L"Ackn."},
    { L_WORD170 ,L"описание"},
    { L_WORD171 ,L"увеличен"},
    { L_WORD172 ,L"сброс"},
    { L_WORD173 ,L"нет сигнализации"},
    { L_WORD174 ,L"установить дату (dd.mm.yy)"},
    { L_WORD175 ,L"установить время (hh.mm.ss)"},
    { L_WORD176 ,L"ошибка ввода времени!"},
    { L_WORD177 ,L"формат времени(h.m.s)"},
    { L_WORD178 ,L"ошибка при вводе даты"},
    { L_WORD179 ,L"формат даты (d.m.y)"},
    { L_WORD180 ,L"введите новое значение:"},
    { L_WORD181 ,L"нет данных"},
    { L_WORD182 ,L"нет датчика(-ов)"},
    { L_WORD183 ,L"введите дифферент. (Aft is -)"},
    { L_WORD184 ,L"введите крен. (Port is -)"},
    { L_WORD185 ,L"введите новую плотность:"},
    { L_WORD186 ,L"0"},
    { L_WORD187 ,L"1"},
    { L_WORD188 ,L"ошибка"},
    { L_WORD189 ,L"авто"},
    { L_WORD190 ,L"ручной"},
    { L_WORD191 ,L"нет ошибки"},
    { L_WORD192 ,L"ошибка ввода"},
    { L_WORD193 ,L"ошибка плотности"},
    { L_WORD194 ,L"RefTmp1=RefTmp2"},
    { L_WORD195 ,L"RefTmp1 fixed"},
    { L_WORD196 ,L"неправ коэффициент"},
    { L_WORD197 ,L"слишком высокое значение"},
    { L_WORD198 ,L"слишком низкое значение"},
    { L_WORD199 ,L"использовать API"},
    { L_WORD200 ,L"тиспользуйте плотность 1"},
    { L_WORD201 ,L"выберите табл API"},
    { L_WORD202 ,L"недопуст метка"},
    { L_WORD203 ,L"недопуст знач"},
    { L_WORD204 ,L"неизвест танк"},
    { L_WORD205 ,L"давление не найдено"},
    { L_WORD206 ,L"нет датчика температуры"},
    { L_WORD207 ,L"значение за пределами"},
    { L_WORD208 ,L"использовать забортнуб воду"},
    { L_WORD209 ,L"использовать балласт"},
    { L_WORD210 ,L"Lo temp=Hi temp"},
    { L_WORD211 ,L"Input not allowed"},
    { L_WORD212 ,L"неопред груз"},
    { L_WORD213 ,L"повторный ввод"},
    { L_WORD214 ,L"Ref Dns1 too low"},
    { L_WORD215 ,L"Ref Dns1 too high"},
    { L_WORD216 ,L"Ref Dns2 too low"},
    { L_WORD217 ,L"Ref Dns2 too high"},
    { L_WORD218 ,L"API вне диапазона"},
    { L_WORD219 ,L"ошибка датчика"},
    { L_WORD220 ,L"приращение за пределами"},
    { L_WORD221 ,L"использовать пресную воду"},
    { L_WORD222 ,L"использовать ДТ"},
    { L_WORD223 ,L"использоватль ДТ"},
    { L_WORD224 ,L"использовать ГСМ"},
    { L_WORD225 ,L"низкий > высокий предел"},
    { L_WORD226 ,L"высокий < низкий предел"},
    { L_WORD227 ,L"высокий = низкий предел"},
    { L_WORD228 ,L"не регулируется"},
    { L_WORD229 ,L"нет разрешения на ввод"},
    { L_WORD230 ,L"датчик отключен"},
    { L_WORD231 ,L"испол табл API53"},
    { L_WORD232 ,L"испол табл API54"},
    { L_WORD233 ,L"испол относит плотность 2"},
    { L_WORD234 ,L"нет возможности использовать общий ввод"},
    { L_WORD235 ,L"перезапись возможна только во время срабат сигнализации или Pre или Main"},
    { L_WORD236 ,L"нет узла"},
    { L_WORD237 ,L""/*пустой*/},
    { L_WORD238 ,L"длина"},
    { L_WORD239 ,L"давлени атмос/пара"},
    { L_WORD240 ,L"давление груза/балласта"},
    { L_WORD241 ,L"линейное давление"},
    { L_WORD242 ,L"коэф плотности"},
    { L_WORD243 ,L"угол"},
    { L_WORD244 ,L"свободное про-во"},
    { L_WORD245 ,L"момент"},
    { L_WORD246 ,L"погружение"},
    { L_WORD247 ,L"уровень нагрузки"},
    { L_WORD248 ,L"процент"},
    { L_WORD249 ,L"GZ зона"},
    { L_WORD250 ,L"ток"},
    { L_WORD251 ,L"напряжение"},
    { L_WORD252 ,L"время"},
    { L_WORD253 ,L"м сек"},
    { L_WORD254 ,L"дни"},
    { L_WORD255 ,L"feet"},
    { L_WORD256 ,L"d.feet"},
    { L_WORD257 ,L"mі"},
    { L_WORD258 ,L"л"},
    { L_WORD259 ,L"галлоны США"},
    { L_WORD260 ,L"баррели США"},
    { L_WORD261 ,L"тонны"},
    { L_WORD262 ,L"тонны"},
    { L_WORD263 ,L"кН"},
    { L_WORD264 ,L"мин/ч"},
    { L_WORD265 ,L"USb/h"},
    { L_WORD266 ,L"°C"},
    { L_WORD267 ,L"°F"},
    { L_WORD268 ,L"mH2O"},
    { L_WORD269 ,L"mmH2O"},
    { L_WORD270 ,L"mBar"},
    { L_WORD271 ,L"бар"},
    { L_WORD272 ,L"ПСИ"},
    { L_WORD273 ,L"кПа"},
    { L_WORD274 ,L"InH2O"},
    { L_WORD275 ,L"InHg"},
    { L_WORD276 ,L"мин тем-ра вакуума"},
    { L_WORD277 ,L"мин тем-ра воздуха"},
    { L_WORD278 ,L"lb/usg"},
    { L_WORD279 ,L"угол"},
    { L_WORD280 ,L"Rad"},
    { L_WORD281 ,L"t/mі°C"},
    { L_WORD282 ,L"t/mі°F"},
    { L_WORD283 ,L"l/g/°C"},
    { L_WORD284 ,L"l/g/°F"},
    { L_WORD285 ,L"m^4"},
    { L_WORD286 ,L"Feet^4"},
    { L_WORD287 ,L"t*m"},
    { L_WORD288 ,L"lton*Ft"},
    { L_WORD289 ,L"kNm"},
    { L_WORD290 ,L"t/cm"},
    { L_WORD291 ,L"lton/in"},
    { L_WORD292 ,L"m*Rad"},
    { L_WORD293 ,L"%"},
    { L_WORD294 ,L"‰"},
    { L_WORD295 ,L"мАм"},
    { L_WORD296 ,L"Ам"},
    { L_WORD297 ,L"В"},
    { L_WORD298 ,L"мВ"},
    { L_WORD299 ,L"мс"},
    { L_WORD300 ,L"сек"},
    { L_WORD301 ,L"мин"},
    { L_WORD302 ,L"часы},
    { L_WORD303 ,L"дни"},
    { L_WORD304 ,L"неиспол"},
    { L_WORD305 ,L"датчик уровня"},
    { L_WORD306 ,L"LevelRef"},
    { L_WORD307 ,L"LevelFC"},
    { L_WORD308 ,L"зондаж"},
    { L_WORD309 ,L"протечка"},
    { L_WORD310 ,L"объем%"},
    { L_WORD311 ,L"давление"},
    { L_WORD312 ,L"высок давление"},
    { L_WORD313 ,L"низ давление"},
    { L_WORD314 ,L"время оконч"},
    { L_WORD315 ,L"время остав"},
    { L_WORD316 ,L"тип груза"},
    { L_WORD317 ,L"давление дна"},
    { L_WORD318 ,L"давление середины"},
    { L_WORD319 ,L"верх давление"},
    { L_WORD320 ,L"давление наверху"},
    { L_WORD321 ,L"BP Gain"},
    { L_WORD322 ,L"MP Gain"},
    { L_WORD323 ,L"UP Gain"},
    { L_WORD324 ,L"TP Gain"},
    { L_WORD325 ,L"офсет BP"},
    { L_WORD326 ,L"офсет MP"},
    { L_WORD327 ,L"офсет UP"},
    { L_WORD328 ,L"офсет TP"},
    { L_WORD329 ,L"LevS"},
    { L_WORD330 ,L"LevR"},
    { L_WORD331 ,L"LevF"},
    { L_WORD332 ,L"зондаж"},
    { L_WORD333 ,L"Ull"},
    { L_WORD334 ,L"объем"},
    { L_WORD335 ,L"объем%"},
    { L_WORD336 ,L"вес"},
    { L_WORD337 ,L"плот"},
    { L_WORD338 ,L"темп"},
    { L_WORD339 ,L"давл"},
    { L_WORD340 ,L"выс темп"},
    { L_WORD341 ,L"низ темп"},
    { L_WORD342 ,L"выс давл"},
    { L_WORD343 ,L"низ давл"},
    { L_WORD344 ,L"низ знач"},
    { L_WORD345 ,L"FTim"},
    { L_WORD346 ,L"RTim"},
    { L_WORD347 ,L"Ctyp"},
    { L_WORD348 ,L"BP"},
    { L_WORD349 ,L"MP"},
    { L_WORD350 ,L"UP"},
    { L_WORD351 ,L"TP"},
    { L_WORD352 ,L"BPGn"},
    { L_WORD353 ,L"MPGn"},
    { L_WORD354 ,L"UPGn"},
    { L_WORD355 ,L"TPGn"},
    { L_WORD356 ,L"BPOf"},
    { L_WORD357 ,L"MPOf"},
    { L_WORD358 ,L"UPOf"},
    { L_WORD359 ,L"TPOf"},
    { L_WORD360 ,L"темп дня"},
    { L_WORD361 ,L"темп середины"},
    { L_WORD362 ,L"темп верха"},
    { L_WORD363 ,L"темп наверху"},
    { L_WORD364 ,L"BT"},
    { L_WORD365 ,L"MT"},
    { L_WORD366 ,L"UT"},
    { L_WORD367 ,L"TT"},
    { L_WORD368 ,L"Atm sensor"},
    { L_WORD369 ,L"мощность 24V(1)"},
    { L_WORD370 ,L"мощность 24V(2)"},
    { L_WORD371 ,L"мощность 3.3V"},
    { L_WORD372 ,L"мощность 1.8V"},
    { L_WORD373 ,L"OS Status"},
    { L_WORD374 ,L"статус мерцания"},
    { L_WORD375 ,L"название задания"},
    { L_WORD376 ,L"время работы"},
    { L_WORD377 ,L"мощность 5.0V"},
    { L_WORD378 ,L"мощность 12V"},
    { L_WORD379 ,L"канал Com"},
    { L_WORD380 ,L"версия Com"},
    { L_WORD381 ,L"версия"},
    { L_WORD382 ,L"Rx размер буфера"},
    { L_WORD383 ,L"Tx размер буфера"},
    { L_WORD384 ,L"сброс статуса"},
    { L_WORD385 ,L"общий перезапуск"},
    { L_WORD386 ,L"ошибка подсчета"},
    { L_WORD387 ,L"всего ошибок"},
    { L_WORD388 ,L"программа"},
    { L_WORD389 ,L"мощность 24V"},
    { L_WORD390 ,L"серийный номер"},
    { L_WORD391 ,L"статус узла"},
    { L_WORD392 ,L"статус карты"},
    { L_WORD393 ,L"название груза"},
    { L_WORD394 ,L"VolCorrFactor"},
    { L_WORD395 ,L"VCF@Temp"},
    { L_WORD396 ,L"измер API"},
    { L_WORD397 ,L"плотность"},
    { L_WORD398 ,L"относит плотность1"},
    { L_WORD399 ,L"относит плотность2"},
    { L_WORD400 ,L"Ref. Temp1"},
    { L_WORD401 ,L"Ref. Temp2"},
    { L_WORD402 ,L"не опред"},
    { L_WORD403 ,L"простой"},
    { L_WORD404 ,L"AtmPress"},
    { L_WORD405 ,L"балласт"},
    { L_WORD406 ,L"ДТ"},
    { L_WORD407 ,L"ДТ"},
    { L_WORD408 ,L"ГСМ"},
    { L_WORD409 ,L"пресная вода"},
    { L_WORD410 ,L"забортная вода"},
    { L_WORD411 ,L"API 6A"},
    { L_WORD412 ,L"API 6B"},
    { L_WORD413 ,L"API 6D"},
    { L_WORD414 ,L"API 53A"},
    { L_WORD415 ,L"API 53B"},
    { L_WORD416 ,L"API 53D"},
    { L_WORD417 ,L"API 54A"},
    { L_WORD418 ,L"API 54B"},
    { L_WORD419 ,L"API 54D"},
    { L_WORD420 ,L"DF"},
    { L_WORD421 ,L"DP"},
    { L_WORD422 ,L"DS"},
    { L_WORD423 ,L"DA"},
   // { L_WORD424 ,L"уровень"},
    { L_WORD425 ,L"дифферент в град"},
    { L_WORD426 ,L"дифферент в метрах"},
    { L_WORD427 ,L"крен в град"},
    { L_WORD428 ,L"DF (выбор пользователя)"},
    { L_WORD429 ,L"DA (выбор пользователя)"},
    { L_WORD430 ,L"DF@Mark"},
    { L_WORD431 ,L"DA@Mark"},
    { L_WORD432 ,L"DF@PP"},
    { L_WORD433 ,L"DA@PP"},
    { L_WORD434 ,L"вкл/выкл"},
    { L_WORD435 ,L"данные системы"},
    { L_WORD436 ,L"осадка"},
    { L_WORD437 ,L"грузовой танк"},
    { L_WORD438 ,L"другие танки"},
    { L_WORD439 ,L"FRO"},
    { L_WORD440 ,L"G1"},
    { L_WORD441 ,L"G2"},
    { L_WORD442 ,L"G3"},
    { L_WORD443 ,L"NL1"},
    { L_WORD444 ,L"NL2"},
    { L_WORD445 ,L"Lev"},
    { L_WORD446 ,L"измер плотность"},
    { L_WORD447 ,L"крен в метрах"},
    { L_WORD448 ,L"широта"},
    { L_WORD449 ,L"тип"},
    { L_WORD450 ,L"SnsDB"},
    { L_WORD451 ,L"расположение"},
    { L_WORD452 ,L"мин диапазон"},
    { L_WORD453 ,L"максдиапазон"},
    { L_WORD454 ,L"длина кабеля"},
    { L_WORD455 ,L"TCUAddress"},
    { L_WORD456 ,L"Port"},
    { L_WORD457 ,L"адрес вводавывода"},
    { L_WORD458 ,L"канал"},
    { L_WORD459 ,L"ADCardChn"},
    { L_WORD460 ,L"дифферент"},
    { L_WORD461 ,L"крен"},
    { L_WORD462 ,L"черный"},
    { L_WORD463 ,L"темно-серый"},
    { L_WORD464 ,L"светло-серый"},
    { L_WORD465 ,L"белый"},
    { L_WORD466 ,L"голубой"},
    { L_WORD467 ,L"печат"},
    { L_WORD468 ,L"S"   /*статус*/},
    { L_WORD469 ,L"Use bls"},
    { L_WORD470 ,L"Use mі"},
    { L_WORD471 ,L"сухой"},
    { L_WORD472 ,L"--.-"},
    { L_WORD473 ,L"пустой"},
    { L_WORD474 ,L"*****"   /*фиксир длина!*/},
    { L_WORD475 ,L"основ"},
    { L_WORD476 ,L"предварит"},
    { L_WORD477 ,L"сверх"},
    { L_WORD478 ,L"Prot"},
    { L_WORD479 ,L"Com"},
    { L_WORD480 ,L"(Rx/Tx)"},
    { L_WORD481 ,L"on TCU:"},
    { L_WORD482 ,L"on ZB485:"},
    { L_WORD483 ,L"загрузчик"},
    { L_WORD484 ,L"приложение"},
    { L_WORD485 ,L"неизвестно"},
    { L_WORD486 ,L"нет"},
    { L_WORD487 ,L"ошибка"},
    { L_WORD488 ,L"NoUs"},
    { L_WORD489 ,L"другое"},
    { L_WORD490 ,L"нажать"},
    { L_WORD491 ,L"@PP"},
    { L_WORD492 ,L"@отметить"},
    { L_WORD493 ,L"деакт"},
    { L_WORD494 ,L"активир"},
    { L_WORD495 ,L"Ackn."},
    { L_WORD496 ,L"Lim:"},
    { L_WORD497 ,L"Val:"},
    { L_WORD498 ,L"ошибка указателя"},
    { L_WORD499 ,L"Unk."},
    { L_WORD500 ,L"вне пределов"},
    { L_WORD501 ,L"команд ошибка"},
    { L_WORD502 ,L"HLev"},
    { L_WORD503 ,L"высокий уровень"},
    { L_WORD504 ,L"выслин давление"},
    { L_WORD505 ,L"HLPr"},
    { L_WORD506 ,L"высокое давление"},
    { L_WORD507 ,L"HPre"},
    { L_WORD508 ,L"высокая тнм-ра"},
    { L_WORD509 ,L"HTmp"},
    { L_WORD510 ,L"высокое напряжение"},
    { L_WORD511 ,L"высок напряжение"},
    { L_WORD512 ,L"высокое давление1"},
    { L_WORD513 ,L"HPr1"},
    { L_WORD514 ,L"низкое давление1"},
    { L_WORD515 ,L"LPr1"},
    { L_WORD516 ,L"команд ошибка"},
    { L_WORD517 ,L"IOErr"},
    { L_WORD518 ,L"LowLevel"},
    { L_WORD519 ,L"LLev"},
    { L_WORD520 ,L"LowLinePress"},
    { L_WORD521 ,L"LLPr"},
    { L_WORD522 ,L"низкое давл"},
    { L_WORD523 ,L"LPre"},
    { L_WORD524 ,L"низк тем-ра"},
    { L_WORD525 ,L"LTmp"},
    { L_WORD526 ,L"низкое напряж"},
    { L_WORD527 ,L"низкое напряжение"},
    { L_WORD528 ,L"ошибка"},
    { L_WORD529 ,L"осн вода"},
    { L_WORD530 ,L"MWat"},
    { L_WORD531 ,L"откр цепь"},
    { L_WORD532 ,L"oloop"},
  //  { L_WORD109 ,L"перелив"},
    { L_WORD534 ,L"перелив"},
    { L_WORD535 ,L"PreWater"},
    { L_WORD536 ,L"PWat"},
    { L_WORD537 ,L"ошибка диапазона"},
    { L_WORD538 ,L"ADErr"},
    { L_WORD539 ,L"Cnv&Cal Error"},
    { L_WORD540 ,L"HWErr"},
    { L_WORD541 ,L"ошибка конфиг"},
    { L_WORD542 ,L"RaErr"},
    { L_WORD543 ,L"кор замыкание"},
    { L_WORD544 ,L"Scirc"},
    { L_WORD545 ,L"детали"},
    { L_WORD546 ,L"калибр данные"},
    { L_WORD547 ,L"SerNum"},
    { L_WORD548 ,L"диапазон"},
    { L_WORD549 ,L"CalData Source"},
    { L_WORD550 ,L"офсет уровня"},
    { L_WORD551 ,L"инклинометр"},
    { L_WORD552 ,L"осадка"},
    { L_WORD553 ,L"измерено"},
    { L_WORD554 ,L"ch"},
    { L_WORD555 ,L"Loc"},
    { L_WORD556 ,L"RawVal"},
    { L_WORD557 ,L"CalVal"},
    { L_WORD558 ,L"CnvCalE"},
    { L_WORD559 ,L"PROM"},
    { L_WORD560 ,L"PC"},
    { L_WORD561 ,L"TCUCal"},
    { L_WORD562 ,L"AD Sns"},
    { L_WORD563 ,L"TCU Sns"},
    { L_WORD564 ,L"From TCU"},
    { L_WORD565 ,L"зеленый"},
    { L_WORD566 ,L"стирание флеш"},
    { L_WORD567 ,L"инфо"},
    { L_WORD568 ,L"стирание ошибки"},
    { L_WORD569 ,L"идет обновление программы..."},
    { L_WORD570 ,L"калибровка,\n коснитесь экрана\n в центре кольца"},
    { L_WORD571 ,L"отмена"},
    { L_WORD572 ,L"нажать здесь},
    { L_WORD573 ,L"(верхнее левое положение)"},
    { L_WORD574 ,L"(нижнее правое положение)"},
    { L_WORD575 ,L"страница"},
    { L_WORD576 ,L"вресия ПО"},
    { L_WORD577 ,L"грузовые танки"},
    { L_WORD578 ,L"балластные танки"},
    { L_WORD579 ,L"сревсиный танки"},
    { L_WORD580 ,L"такни тяжелого ДТ"},
    { L_WORD581 ,L"танки диз масла"},
    { L_WORD582 ,L"смазочные танки"},
    { L_WORD583 ,L"смешанные танки"},
    { L_WORD584 ,L"танки пресной воды"},
    { L_WORD585 ,L"NotDef"},
    { L_WORD586 ,L"Atm"},
    { L_WORD587 ,L"дно"},
    { L_WORD588 ,L"середина"},
    { L_WORD589 ,L"верх"},
    { L_WORD590 ,L"давление танка"},
    { L_WORD591 ,L"насос станция"},
    { L_WORD592 ,L"мотор отсек"},
    { L_WORD593 ,L"палуба"},
    { L_WORD594 ,L"палуба"},
    { L_WORD595 ,L"линия"},
    { L_WORD596 ,L"WIMain"},
    { L_WORD597 ,L"WIPre"},
    { L_WORD598 ,L"Inc"},
    { L_WORD599 ,L"LSw"},
    { L_WORD600 ,L"Rad"},
    { L_WORD601 ,L"WIng"},
    { L_WORD602 ,L"нулевое давление регулировочного танка!"},
    { L_WORD603 ,L"танки следует проветрить. это повлияет на все танки группы."},
    { L_WORD604 ,L"нулеовой датчки регулировки!"},
    { L_WORD605 ,L"танки следует опоржнить и не производить чистку в теч последующих 30 мин. влияет на все танки группы."},
    { L_WORD606 ,L"предупреждение нулевой установки:"},
    { L_WORD607 ,L"танки следует проветрить. это повлияет на все точки замера давления танков."},
    { L_WORD608 ,L"танки следует опоржнить и не производить чистку в теч последующих 30 мин. влияет на все точки замера давления танков."},
    { L_WORD609 ,L"плтность ДТ"},
    { L_WORD610 ,L"плотность масла ДТ"},
    { L_WORD611 ,L"плотность ГСМ"},
    { L_WORD612 ,L"плотность пресной воды"},
    { L_WORD613 ,L" файл поврежден"},
    { L_WORD614 ,L"ошибка в строчке ЮНИКОДА!"},
    { L_WORD615 ,L"F "},
    { L_WORD616 ,L"A "},
    { L_WORD617 ,L"P "},
    { L_WORD618 ,L"S "},
    { L_WORD619 ,L"равный"},
    { L_WORD620 ,L"принтер ан данном узле системы мониторинга"},
    { L_WORD621 ,L"температуры"},
    { L_WORD622 ,L"линейные давления"},
    { L_WORD623 ,L"давления танка"},
    { L_WORD624 ,L"CnvCal"},
    { L_WORD625 ,L"CnvErr"},
    { L_WORD626 ,L"CalErr"},
    { L_WORD627 ,L"TDU"},
    { L_WORD628 ,L"PC"},
    { L_WORD629 ,L"TCU"},
    { L_WORD630 ,L"ANPro3"},
    { L_WORD631 ,L"ANPro10"},
    { L_WORD632 ,L"IOsystem"},
    { L_WORD633 ,L"ZB_Red"},
    { L_WORD634 ,L"Wago"},
    { L_WORD635 ,L"TPCx"},
    { L_WORD636 ,L"принтер"},
    { L_WORD637 ,L"ANPro1"},
    { L_WORD638 ,L"ANPro3"},
    { L_WORD639 ,L"ANPro10"},
    { L_WORD640 ,L"Modbus"},
    { L_WORD641 ,L"принтер"},
    { L_WORD642 ,L"свободное место"},
    { L_WORD643 ,L"свободное место нулевой регулировки\n датчик давления для\n всех свободны мест."},
    { L_WORD644 ,L"нклевоц уроень регулировки\n датчик(s) для\n всех свободных места."},
    { L_WORD646 ,L"применить текущие установки плотности ко всем свободным местам."},
    { L_WORD647 ,L"Apply current alarm settings to all void spaces"},
    { L_WORD648 ,L"протечка"},
    { L_WORD649 ,L"утечка"},
    { L_WORD650 ,L"Пожалуйста, подождите"},
    { L_WORD651 ,L"подождите"},
    { L_WORD652 ,L"DST"},
    { L_WORD653 ,L"24V"},
    { L_WORD654 ,L"In#1"},
    { L_WORD655 ,L"In#2"},
    { L_WORD656 ,L"система будет отрегулирована с учетом вставленного клапан. некорретный ввод повлечет неисправность системы."},
    { L_WORD657 ,L"Предупреждение! Отрегулируйте уровень"},
    { L_WORD658 ,L"Предупреждение! отрегуливроать зондирование"},
    { L_WORD659 ,L"Предупреждение! отрегулируйте незаполненный объем"},
    { L_WORD660 ,L"Предупреждение! отрегулируйте объем"},
    { L_WORD661 ,L"Предупреждение! отрегулируйте вес"},
    { L_WORD662 ,L"на датчик следует установить защитную плиту."},
    { L_WORD663 ,L"с датчика следует снять зашитную плиту."},
    { L_WORD664 ,L"введите ПИН-код:"},
    { L_WORD665 ,L"ведите новый ПИН-код:"},
    { L_WORD666 ,L"время скринсейвера, мин"},
    { L_WORD667 ,L"время задержки сигнализации, сек"},
    { L_WORD668 ,L"введите старый пин-код:"},
    { L_WORD669 ,L"заново введите новый пин-код:"},
    { L_WORD670 ,L"ComErr Id"       },
    { L_WORD671 ,L"ComErr Cmd"  },
    { L_WORD672 ,L"ComErr Msg"  },
    { L_WORD673 ,L"ComErr Cnt"  },
    { L_WORD674 ,L"ComErr Time" },
    { L_WORD675 ,L"команда"},
    { L_WORD676 ,L"объект"},
    { L_WORD677 ,L"уровень"},
    { L_WORD678 ,L"Lvl"},
    { L_WORD679 ,L"водоизмещение"},
    { L_WORD680 ,L"LCG"},
    { L_WORD681 ,L"TCG"},
    { L_WORD682 ,L"VCG"},
    { L_WORD683 ,L"крен в метрах"},
    { L_WORD684 ,L"средняя осадка"},
    { L_WORD685 ,L"вес жидкости"},
    { L_WORD686 ,L"общий вес"},
    { L_WORD687 ,L"Draft P"},
    { L_WORD688 ,L"TFS Moment"},
    { L_WORD689 ,L"момент L"},
    { L_WORD690 ,L"момент T"},
    { L_WORD691 ,L"момент V"},
    { L_WORD692 ,L"VCG Solids"},
    { L_WORD693 ,L"регул VCG"},
    { L_WORD694 ,L"Max VCG"},
    { L_WORD695 ,L"отступ VCG"},
    { L_WORD696 ,L"Dam.max VCG"},
    { L_WORD697 ,L"Dam. VCG marg."},
    { L_WORD698 ,L"погружение"},
    { L_WORD699 ,L"KM"},
    { L_WORD700 ,L"твердый GM"},
    { L_WORD701 ,L"жидкий GM"},
    { L_WORD702 ,L"TCF"},
    { L_WORD703 ,L"LCF"},
    { L_WORD704 ,L"TCG"},
    { L_WORD705 ,L"LCG"},
    { L_WORD706 ,L"GZ"},
    { L_WORD707 ,L"GZ30"},
    { L_WORD708 ,L"GZ max"},
    { L_WORD709 ,L"GZ angle"},
    { L_WORD710 ,L"GZ a0-30"},
    { L_WORD711 ,L"GZ a30-40"},
    { L_WORD712 ,L"угол перелива"},
    { L_WORD713 ,L"осадка"},
    { L_WORD714 ,L"LCB"},
    { L_WORD715 ,L"MaxBM@"},
    { L_WORD716 ,L"MaxSF@"},
    { L_WORD717 ,L"рама"},
    { L_WORD718 ,L"Bend.Mom."},
    { L_WORD719 ,L"Shr.Forc."},
    { L_WORD720 ,L"Cor.BMom"},
    { L_WORD721 ,L"APP dist."},
    { L_WORD722 ,L"PrevFrame"},
    { L_WORD723 ,L"BMomHrb"},
    { L_WORD724 ,L"BMomSea"},
    { L_WORD725 ,L"SForceHrb"},
    { L_WORD726 ,L"SForceSea"},
    { L_WORD727 ,L"вес стали"},
    { L_WORD728 ,L"непотопляемость"},
    { L_WORD729 ,L"нагрузка"},
    { L_WORD730 ,L"измен момента"},
    { L_WORD731 ,L"Avg BMom"},
    { L_WORD732 ,L"Avg SForce"},
    { L_WORD733 ,L"твердые"},
    { L_WORD734 ,L"осадка нос"},
    { L_WORD735 ,L"осадка левый борт"},
    { L_WORD736 ,L"Draft stbd"},
    { L_WORD737 ,L"осадка корма"},
    { L_WORD738 ,L"TFree Surf."},
    { L_WORD739 ,L"FreeSMom."},
    { L_WORD740 ,L"GZ a0-40"},
    { L_WORD741 ,L"пост твердые частицы"},
    { L_WORD742 ,L"переменные твердые частицы"},
    { L_WORD743 ,L"VCF"},
    { L_WORD744 ,L"Vol@RefTmp"},
    { L_WORD745 ,L"V@RT"},
    { L_WORD746 ,L"байт:"},
    { L_WORD747 ,L"разница уровня"},
    { L_WORD748 ,L"LDif"},
    { L_WORD749 ,L"дно1"},
    { L_WORD750 ,L"дно2"},
    { L_WORD751 ,L"дно3"},
    { L_WORD752 ,L"дно4"},
    { L_WORD753 ,L"дно5"},
    { L_WORD754 ,L"BP1"},
    { L_WORD755 ,L"BP2"},
    { L_WORD756 ,L"BP3"},
    { L_WORD757 ,L"BP Gain1"},
    { L_WORD758 ,L"BP Gain2"},
    { L_WORD759 ,L"BP Gain3"},
    { L_WORD760 ,L"BP офсет1"},
    { L_WORD761 ,L"BP офсет1"},
    { L_WORD762 ,L"BP офсет1"},
    { L_WORD763 ,L"адрес ошибки"},
    { L_WORD764 ,L"он-лайн"},
    { L_WORD765 ,L"офф-лайн"},
    { L_WORD766 ,L"статус он-лайна"},
    { L_WORD767 ,L"ровнео полож судна"},
    { L_WORD768 ,L"угол дифферента"},
    { L_WORD769 ,L"угол крена"},
    { L_WORD770 ,L"установки по умолч"},
    { L_WORD771 ,L"TDUce"},
    { L_WORD772 ,L"обновление конфигурации..."},
    { L_WORD773 ,L"прогресс"},
    { L_WORD774 ,L"высокий"},
    { L_WORD775 ,L"низкий"},
    { L_WORD776 ,L"объем"},
    { L_WORD777 ,L"колпачок"},
    { L_WORD778 ,L"Ovfill Lim"},
    { L_WORD779 ,L"HiLev Lim"},
    { L_WORD780 ,L"HiVol Lim"},
    { L_WORD781 ,L"HiVol%Lim"},
    { L_WORD782 ,L"HiWgt Lim"},
    { L_WORD783 ,L"HiUll Lim"},
    { L_WORD784 ,L"LoLev Lim"},
    { L_WORD785 ,L"предел низкого объема"},
    { L_WORD786 ,L"предел низкого объема %"},
    { L_WORD787 ,L"предел низкого веса"},
    { L_WORD788 ,L"LoUll Lim"},
    { L_WORD789 ,L"HiTmp Lim"},
    { L_WORD790 ,L"LoTmp Lim"},
    { L_WORD791 ,L"HiPre Lim"},
    { L_WORD792 ,L"LoPre Lim"},
    { L_WORD793 ,L"DnsDifLim"},
    { L_WORD794 ,L"LevChgLim"},
    { L_WORD795 ,L"HiLRLim"},
    { L_WORD796 ,L"LoLRLim"},
    { L_WORD797 ,L"OvFill Ena"},
    { L_WORD798 ,L"применить ВУ"},
    { L_WORD799 ,L"применить НУ"},
    { L_WORD899 ,L"применить ВТ"},
    { L_WORD800 ,L"применить НТ"},
    { L_WORD801 ,L"применить ВД"},
    { L_WORD802 ,L"применить НД"},
    { L_WORD803 ,L"применить РазПлотности"},
    { L_WORD804 ,L"применить ПровУр"},
    { L_WORD805 ,L"применить Hi LR Enable"},
    { L_WORD806 ,L"применить Lo LR Enable"},
    { L_WORD807 ,L"установки/инфо груза"},
    { L_WORD808 ,L"пределы сигнализации"},
    { L_WORD809 ,L"сигнализация вкл/выкл"},
    { L_WORD810 ,L"параметры датчика"},
    { L_WORD811 ,L"статус датчика"},
    { L_WORD812 ,L"сепаратор"},
    { L_WORD813 ,L"конец под-меню"},
    { L_WORD814 ,L"применить BP1"},
    { L_WORD815 ,L"применить BP2"},
    { L_WORD816 ,L"применить BP3"},
    { L_WORD817 ,L"применить BP"},
    { L_WORD818 ,L"применить MP"},
    { L_WORD819 ,L"применить UP"},
    { L_WORD820 ,L"применить TP"},
    { L_WORD821 ,L"дубликат названия"},
    { L_WORD822 ,L"BT Gain"     },
    { L_WORD823 ,L"MT Gain"     },
    { L_WORD824 ,L"UT Gain"     },
    { L_WORD825 ,L"TT Gain"     },
    { L_WORD826 ,L"BT офсет"   },
    { L_WORD827 ,L"MT офсет"   },
    { L_WORD828 ,L"UT офсет"   },
    { L_WORD829 ,L"TT офсет"   },
    { L_WORD830 ,L"BT"},
    { L_WORD831 ,L"MT"},
    { L_WORD832 ,L"UT"},
    { L_WORD833 ,L"TT"},
    { L_WORD834 ,L"BTGn"},
    { L_WORD835 ,L"MTGn"},
    { L_WORD836 ,L"UTGn"},
    { L_WORD837 ,L"TTGn"},
    { L_WORD838 ,L"BTOf"},
    { L_WORD839 ,L"MTOf"},
    { L_WORD840 ,L"UTOf"},
    { L_WORD841 ,L"TTOf"},
    { L_WORD842 ,L"применить BT"},
    { L_WORD843 ,L"применить MT"},
    { L_WORD844 ,L"применить UT"},
    { L_WORD845 ,L"применить TT"},
    { L_WORD846 ,L"сис задержка ввода/вывода"},
    { L_WORD847 ,L"метр измер"},
    { L_WORD848 ,L"интерфейс"},
    { L_WORD849 ,L"Intrf"},
    { L_WORD850 ,L"вода"},
    { L_WORD851 ,L"нет датчика"},
    { L_WORD852 ,L"отключено"},
    { L_WORD853 ,L"Normal LSw"},
    { L_WORD854 ,L"мореплавание"},
    { L_WORD855 ,L"чистка танка"},
    { L_WORD856 ,L"рабочий режим"},
    { L_WORD857 ,L"рабочий режим"},
    { L_WORD858 ,L"неопрел"},
    { L_WORD859 ,L"чистка"},
    { L_WORD860 ,L"нагрузка"},
    { L_WORD861 ,L"разгрузка"},
    { L_WORD862 ,L"ПРЕДУПРЕЖДЕНИЕ: при выборе ДА отключатся все датчики уровня!"},
    { L_WORD863 ,L"пользователь"},
    { L_WORD864 ,L"MsrdDnsStat"},
    { L_WORD865 ,L"дубликат названия"},
    { L_WORD866 ,L"изменение уровня"},
    { L_WORD867 ,L"LChng"},
    { L_WORD868 ,L"регулировка"},
    { L_WORD869 ,L"Saab"},
    { L_WORD870 ,L"грузовой танк"},
    { L_WORD871 ,L"балластный танк"},
    { L_WORD872 ,L"сервисный танк"},
    { L_WORD873 ,L"такн малса тяжелого ДТ"},
    { L_WORD874 ,L"танк масла ДТ"},
    { L_WORD875 ,L"танк гсм"},
    { L_WORD876 ,L"танк пресной воды"},
    { L_WORD877 ,L"смешанный танк"},
    { L_WORD878 ,L"установтиь оффсет уровня"},
    { L_WORD879 ,L"установить оффсет датчика"},
    { L_WORD880 ,L"вы собираетесь изменить оффсет датчика. это изменит погрешность!"},
    { L_WORD881 ,L"вы собираетесь изменить оффсет уровня. это изменит погрешность!"},
    { L_WORD882 ,L"резервирование"},
    { L_WORD883 ,L"порог радара"},
    { L_WORD884 ,L"RTrH"},
    { L_WORD885 ,L"крышка 98%"},
    { L_WORD886 ,L"крышка 100%"},
    { L_WORD887 ,L"C98%"},
    { L_WORD888 ,L"C100%"},
    { L_WORD889 ,L"предохранитель"},
    { L_WORD890 ,L"AC"},
    { L_WORD891 ,L"Batt"},
    { L_WORD892 ,L"разбито"},
    { L_WORD893 ,L"танки"},
    { L_WORD894 ,L"применить текущие установки плотности ко всем танкам."},
    { L_WORD895 ,L"применить текущие установки сигнализации ко всем танкам."},
    { L_WORD896 ,L"масло"},
    { L_WORD897 ,L"мощность"},
    { L_WORD898 ,L"низкое напряжение"},
    { L_WORD899 ,L"X высокое давление"},
    { L_WORD900 ,L"X низкое давление"},
    { L_WORD901 ,L"XHiPr"},
    { L_WORD902 ,L"XLoPr"},
    { L_WORD903 ,L"X HiPre Lim"},
    { L_WORD904 ,L"X LoPre Lim"},
    { L_WORD905 ,L"период качки"},
    { L_WORD906 ,L"частота качки"},
    { L_WORD907 ,L"макс список P"},
    { L_WORD908 ,L"макс список S"},
    { L_WORD909 ,L"частота"},
    { L_WORD910 ,L"Hz"},
    { L_WORD911 ,L"нажать все состояние"},
    { L_WORD912 ,L"регулир"},
    { L_WORD913 ,L"нажать вакуум"},
    { L_WORD914 ,L"VapRet"},
    { L_WORD915 ,L"PAlStat"},
    { L_WORD916 ,L"утечка UTI"},
    { L_WORD917 ,L"UTI"},
    { L_WORD918 ,L"удаленный URef - UTI"},
    { L_WORD919 ,L"DUTI"},
    { L_WORD920 ,L"записать\файл nconfig"},
    { L_WORD921 ,L"Use API59 table"},
    { L_WORD922 ,L"Use API60 table"},
    { L_WORD923 ,L"API 59A"},
    { L_WORD924 ,L"API 59B"},
    { L_WORD925 ,L"API 59D"},
    { L_WORD926 ,L"API 60A"},
    { L_WORD927 ,L"API 60B"},
    { L_WORD928 ,L"API 60D"},
    { L_WORD929 ,L"тест"},
    { L_WORD930 ,L"тест"},
    { L_WORD931 ,L"свет"},
    { L_WORD932 ,L"Lgt"},
    { L_WORD933 ,L"Conv"},
    { L_WORD934 ,L"Cnv"},
    { L_WORD935 ,L"TSS"},
    { L_WORD936 ,L"TZS"},
    { L_WORD937 ,L"ввод"},
    { L_WORD938 ,L"основной тип"},
    { L_WORD939 ,L"API 53E"},
    { L_WORD940 ,L"API 54E"},
    { L_WORD941 ,L"API 59E"},
    { L_WORD942 ,L"API 60E"},
    { L_WORD943 ,L"вес пара"},
    { L_WORD944 ,L"вес газа"},
    { L_WORD945 ,L"вес пара"},
    { L_WORD946 ,L"GasW"},
    { L_WORD947 ,L"плаву"},
    { L_WORD948 ,L"аммониак"      },
    { L_WORD949 ,L"бутадиен"      },
    { L_WORD950 ,L"изобутилен"   },
    { L_WORD951 ,L"пропилен"     },
    { L_WORD952 ,L"пропеноксид"   },
    { L_WORD953 ,L"винилхлорид" },
    { L_WORD954 ,L"обхем оффсета"},
    { L_WORD955 ,L"VOff"},
    { L_WORD956 ,L"объем нетто"},
    { L_WORD957 ,L"NVol"},
    { L_WORD958 ,L"NVol@Ref"},
    { L_WORD959 ,L"NVolR"},
    { L_WORD960 ,L"вес нетто"},
    { L_WORD961 ,L"NWgt"},
    { L_WORD962 ,L"частичная нагрузка"},
    { L_WORD963 ,L"частичная нагрузка"},
    { L_WORD964 ,L"бутан"          },
    { L_WORD965 ,L"пропан"         },
    { L_WORD966 ,L"Н-бутан"        },
    { L_WORD967 ,L"ISO-бутан"      },
    { L_WORD968 ,L"1-бутен"        },
    { L_WORD969 ,L"Crude C4"        },
    { L_WORD970 ,L"рафинат 1"     },
    { L_WORD971 ,L"рафинат 2"     },
    { L_WORD972 ,L"пропилен Ref"   },
    { L_WORD973 ,L"газолин    "     },
    { L_WORD974 ,L"Flexicoker LPG"  },
    { L_WORD975 ,L"сульфур-1"       },
    { L_WORD976 ,L"сульфур-2"       },
    { L_WORD977 ,L"сульфур-3"       },
    { L_WORD978 ,L"сульфур-4"       },
    { L_WORD979 ,L"сульфур-5"       },
    { L_WORD980 ,L"сульфур-6"       },
    { L_WORD981 ,L"вы собираетесь регулировать оффсет уровня. это повлияет на погрешнсть!"},
    { L_WORD982 ,L"установить табличный оффсет"},
    { L_WORD983 ,L"табличный оффсет"},
    { L_WORD984 ,L"пользовательский"},
    { L_WORD985 ,L"Temp1"},
    { L_WORD986 ,L"Temp2"},
    { L_WORD987 ,L"Temp3"},
    { L_WORD988 ,L"Temp4"},
    { L_WORD989 ,L"Temp5"},
    { L_WORD990 ,L"Temp6"},
    { L_WORD991 ,L"Temp7"},
    { L_WORD992 ,L"Temp8"},
    { L_WORD993 ,L"Temp9"},
    { L_WORD994 ,L"Temp10"},
    { L_WORD995 ,L"MolMass"},
    { L_WORD996 ,L"Air"},
    { L_WORD997 ,L"u"},
    { L_WORD998 ,L"ошибка HartCom"},
};

unsigned WordsInEnglishDictionary = NELEMENTS(EnglishDictionary);

wchar_t EnglishUserManual[] = {L"           User manual for TDU\n\
\n\
For full information about the operation of the system, see the INSTALATION, INSTRUCTION AND OPERATION MANUAL.\n\
\n\
This touch screen shall be operated by a stylus pen or the finger tip. Other equipment/tools will damage the screen.\n\
\n\
NOTE:\n\
Before you start operating the system, the INSTRUCTION AND OPERATION MANUAL must be studied and understood.\n\
\n\
It is strongly recommended that you know the consequences of wrong use of the density system, alarm settings, alarm disabling and zero adjust of sensors.\n\
FAILURE to do this correct can cause overloading or damage.\n\
\n\
The manual and other spare parts can be ordered from:\n\
\n\
Scanjet Ariston AS\n\
Dokkvegen 10\n\
3920 Porsgrunn\n\
Norway \n\
\n\
Tel: +47 35 93 11 30\n\
Service: +47 958 78 644\n\
Fax: +47 35 93 11 31\n\
E-mail: service@ariston.no\n\
Web: www.ariston.no\n\
"};

int SizeOfEnglishUserManual= sizeof(EnglishUserManual);

