#pragma hdrstop
#include "TSNIncludes.h"

//---------------------------------------------------------------------------
NewLanguageWord NorwegianDictionary[]=
{
//	{ Keyword	,Word
	//{ L_WORD0   ,L""},
	{ L_WORD1   ,L"Koble inn"},
	{ L_WORD2   ,L"Koble ut"},
	{ L_WORD3   ,L"På"},
	{ L_WORD4   ,L"Av"},
	{ L_WORD5   ,L"Skriver"},
	{ L_WORD6   ,L"Språk:"},
	{ L_WORD7   ,L"Alarmer"},
	{ L_WORD8   ,L"Ballast veksling"},
	{ L_WORD9   ,L"Last"},
	//{ L_WORD10  ,L""},
	{ L_WORD11  ,L"Temperatur"},
	{ L_WORD12  ,L"Tank trykk"},
	{ L_WORD13  ,L"Velg logger:"},
	{ L_WORD14  ,L"Logtidspunkt"},
	{ L_WORD15  ,L"Timer"},
	{ L_WORD16  ,L"Skriveroppsett"},
	{ L_WORD17  ,L"Åpne"},
	{ L_WORD18  ,L"Lukk"},
	{ L_WORD19  ,L"Loggeperiode"},
	{ L_WORD20  ,L"Systemside 1"},
	{ L_WORD21  ,L"Bruker manual"},
	{ L_WORD22  ,L"Oppsett"},
	{ L_WORD23  ,L"Skriver"},
	{ L_WORD24  ,L"Program versjon"},
	{ L_WORD25  ,L"Data versjon:"},
	//{ L_WORD26  ,L""},
	{ L_WORD27  ,L"Måleenhet:"},
	{ L_WORD28  ,L"Språk"},
	{ L_WORD29  ,L"GMT"},
	{ L_WORD30  ,L"Systemside 2"},
	{ L_WORD31  ,L"Atmosfære kilde"},
	//{ L_WORD32  ,L""},
	{ L_WORD33  ,L"Trim kilde:"},
	{ L_WORD34  ,L"grader"},
	{ L_WORD35  ,L"Dypgående"},
	{ L_WORD36  ,L"Enhet"},
	{ L_WORD37  ,L"Sjøvann"},
	{ L_WORD38  ,L"List kilde:"},
	{ L_WORD39  ,L"Systemside 3: IO enhet"},
	{ L_WORD40  ,L"Velg:"},
	{ L_WORD41  ,L"Systemside 4: Hardware enhet"},
	{ L_WORD42  ,L"Systemside 5"},
	{ L_WORD43  ,L"Totalt alle tanker"},
	{ L_WORD44  ,L"Volum"},
	{ L_WORD45  ,L"Vekt"},
	{ L_WORD46  ,L"Vann"},
	{ L_WORD47  ,L"Ballast"},
	{ L_WORD48  ,L"Tungolje"},
	{ L_WORD49  ,L"Diesel olje"},
	{ L_WORD50  ,L"Smørolje"},
	{ L_WORD51  ,L"Ferskvann"},
	{ L_WORD52  ,L"Forskjellige"},
	{ L_WORD53  ,L"Sluttsum"},
	{ L_WORD54  ,L"System oppsettside"},
	{ L_WORD55  ,L"Skjermsparer"},
	{ L_WORD56  ,L"min."},
	{ L_WORD57  ,L"Avtid for alarm:"},
	{ L_WORD58  ,L"sek."},
	{ L_WORD59  ,L"SI enhet"},
	{ L_WORD60  ,L"US enhet"},
	{ L_WORD61  ,L"Velg farge:"},
	{ L_WORD62  ,L"Bakgrunn"},
	{ L_WORD63  ,L"Forgrunn"},
	{ L_WORD64  ,L"Lysstyrke:"},
	{ L_WORD65  ,L"Lyd/lampe\nsjekk"},
	{ L_WORD66  ,L"Endre PIN kode"},
	{ L_WORD67  ,L"Kalibrer skjerm"},
	{ L_WORD68  ,L"EEPROM"},
	{ L_WORD69  ,L"Bruker oppsett"},
	{ L_WORD70  ,L"Kol. 1"},
	{ L_WORD71  ,L"Kol. 2"},
	{ L_WORD72  ,L"Kol. 3"},
	{ L_WORD73  ,L"Kol. 4"},
	{ L_WORD74  ,L"Navn "},
	{ L_WORD75  ,L"Nulljuster tank\n trykk føler for\n alle ballasttanker."},
	{ L_WORD76  ,L"Nulljuster \nnivåføler(e) for\n alle ballasttanker."},
	{ L_WORD77  ,L"Sjøvanns tetthet"},
	{ L_WORD78  ,L"Nulljuster tank\n trykk føler for\n alle lastetanker."},
	{ L_WORD79  ,L"Nulljuster \nnivåføler(e) for\n alle lastetanker."},
	{ L_WORD80  ,L"Egenvekt for:"},
	{ L_WORD81  ,L"Nulljuster tank\n trykk føler for\n alle tank trykk."},
	{ L_WORD82  ,L"Fellesinnsetting for alle ballast tanker"},
	{ L_WORD83  ,L"Egenvekt"},
	{ L_WORD84  ,L"Konfigureringsfeil"},
	{ L_WORD85  ,L"Tekst"},
	{ L_WORD86  ,L"Fortsett"},
	{ L_WORD87  ,L"Forrige ^"},
	{ L_WORD88  ,L"Neste v"},
	{ L_WORD89  ,L"Oppsett"},
	{ L_WORD90  ,L"Detalj"},
	{ L_WORD91  ,L"\nUkjent feil i konfigureringen."},
	{ L_WORD92  ,L"Lastlinje trykk"},
	{ L_WORD93  ,L"Gass retur linje"},
	{ L_WORD94  ,L"Vanninntrenging"},
	{ L_WORD95  ,L"Nivå bryter"},
	//{ L_WORD96  ,L""},
	{ L_WORD97  ,L"Alarmer"},
	{ L_WORD98  ,L"Sett for\ngruppen"},
	{ L_WORD99  ,L"Ikke konfigurert"},
	{ L_WORD100 ,L"Ikke i bruk"},
	{ L_WORD101 ,L"Lineær"},
	//{ L_WORD102 ,L""},
	{ L_WORD103 ,L"Bruk målt egenvekt"},
	{ L_WORD104 ,L"Referanse temeratur"},
	{ L_WORD105 ,L"Bruk refefanse egenvekt"},
	{ L_WORD106 ,L"Referanse 1"},
	{ L_WORD107 ,L"Referanse 2"},
	{ L_WORD108 ,L"Koeffisient "},
	{ L_WORD109 ,L"Overfylling"},
	{ L_WORD110 ,L"Høyt nivå"},
	{ L_WORD111 ,L"Lavt nivå"},
	{ L_WORD112 ,L"Høy temperatur"},
	{ L_WORD113 ,L"Lav temperatur"},
	{ L_WORD114 ,L"Høyt tanktrykk"},
	{ L_WORD115 ,L"Lavt tanktrykk"},
	{ L_WORD116 ,L"Nulljuster \ntanktrykkføler"},
	{ L_WORD117 ,L"Nulljuster \nnivåføler"},
	{ L_WORD118 ,L"Juster nivå"},
	{ L_WORD119 ,L"Juster sounding"},
	{ L_WORD120 ,L"Juster ullage"},
	{ L_WORD121 ,L"Juster volum"},
	{ L_WORD122 ,L"Juster vekt"},
	{ L_WORD123 ,L"Lås opp"},
	{ L_WORD124 ,L"Plass"},
	{ L_WORD125 ,L"På"},
	{ L_WORD126 ,L"Forsterk"},
	{ L_WORD127 ,L"Nullpunkt"},
	{ L_WORD128 ,L"Verdi"},
	{ L_WORD129 ,L"Ny verdi"},
	{ L_WORD130 ,L"Bekreft"},
	{ L_WORD131 ,L"Sett denne egenvekten for alle lastetanker"},
	{ L_WORD132 ,L"Sett denne egenvekten for alle ballasttanker"},
	{ L_WORD133 ,L"Sett denne egenvekten for alle servicetanker"},
	{ L_WORD134 ,L"Ny alarmgrense"},
	{ L_WORD135 ,L"Sett disse alarmgrensene for alle lastetanker"},
	{ L_WORD136 ,L"Sett disse alarmgrensene for alle ballasttanker"},
	{ L_WORD137 ,L"Sett disse alarmgrensene for alle servicetanker"},
	{ L_WORD138 ,L"Sett disse alarmgrensene for alle tanktrykk"},
	{ L_WORD139 ,L"Sett disse alarmgrensene for alle temperaturer"},
	{ L_WORD140 ,L"Nuljuster føler"},
	{ L_WORD141 ,L"Føleren må luftes til atmosfære"},
	{ L_WORD142 ,L"Nulljuster nivåføler(e)"},
	{ L_WORD143 ,L"Tanken må være tom og ingen tankrengjøringen må ha foregått de siste 30 minuttene"},
	{ L_WORD144 ,L"Nivået vil bli justert til innsatt nivå. Ukorrekt innsetting vil føre til feilvisning."},
	{ L_WORD145 ,L"Observert nivå"},
	{ L_WORD146 ,L"Observert sounding"},
	{ L_WORD147 ,L"Observert ullage"},
	{ L_WORD148 ,L"Observert volum"},
	{ L_WORD149 ,L"Observert vekt"},
	{ L_WORD150 ,L"Sett inn PIN kode"},
	{ L_WORD151 ,L"Sett inn forsterkning"},
	{ L_WORD152 ,L"Sett in følerverdi"},
	{ L_WORD153 ,L"Advarsel"},
	{ L_WORD154 ,L"Du justerer nå forsterkningen på føleren. Dette kan ha innvirkning på nøyaktigheten!"},
	{ L_WORD155 ,L"Du er i ferd med å justere føleren. Dette kan ha invirkning på nøyaktigheten!"},
	{ L_WORD156 ,L"Nulljustering"},
	{ L_WORD157 ,L"Følerverdier"},
	{ L_WORD158 ,L"Høyt linjetrykk"},
	{ L_WORD159 ,L"Lavt linjetrykk"},
	{ L_WORD160 ,L"Nulljuster \nlinjetrykkføler"},
	//{ L_WORD161 ,L""},
	{ L_WORD162 ,L"Ja"},
	{ L_WORD163 ,L"Nei"},
	{ L_WORD164 ,L"Fortsett?"},
	{ L_WORD165 ,L"Advarsel, detaljoppsett"},
	{ L_WORD166 ,L"Velg en tank ved å merke raden og trykk Detaljknappen."},
	{ L_WORD167 ,L"< Forrige"},
	{ L_WORD168 ,L"Neste >"},
	{ L_WORD169 ,L"Kvittere"},
	{ L_WORD170 ,L"Beskrivelse"},
	{ L_WORD171 ,L"Oppstått"},
	{ L_WORD172 ,L"Godtatt"},
	{ L_WORD173 ,L"Ingen alarmer"},
	{ L_WORD174 ,L"Sett dato (dd.mm.åå)"},
	{ L_WORD175 ,L"Sett klokke (tt.mm.ss)"},
	{ L_WORD176 ,L"Feil på innsatt klokke"},
	{ L_WORD177 ,L"Klokke format (t.m.s)"},
	{ L_WORD178 ,L"Feil på innsatt dato"},
	{ L_WORD179 ,L"Datoformat (d.m.å)"},
	{ L_WORD180 ,L"Sett inn ny verdi"},
	{ L_WORD181 ,L"Ingen verdi"},
	{ L_WORD182 ,L"Ingen føler"},
	{ L_WORD183 ,L"Sett inn trim (Akter -)"},
	{ L_WORD184 ,L"Sett inn list (Babord -)"},
	{ L_WORD185 ,L"Sett inn egenvekt"},
	//{ L_WORD186 ,L""},
	//{ L_WORD187 ,L""},
	{ L_WORD188 ,L"Feil"},
	{ L_WORD189 ,L"Auto"},
	{ L_WORD190 ,L"Manuell"},
	{ L_WORD191 ,L"Ingen feil"},
	{ L_WORD192 ,L"Innsetingsfeil"},
	{ L_WORD193 ,L"Feil i egenvekt"},
	{ L_WORD194 ,L"RefTmp1=RefTmp2"},
	{ L_WORD195 ,L"RefTmp1 fast"},
	{ L_WORD196 ,L"Feil koeffisient"},
	{ L_WORD197 ,L"Verdien er for høy"},
	{ L_WORD198 ,L"Verdien er for lav"},
	{ L_WORD199 ,L"Bruk API"},
	{ L_WORD200 ,L"Bruk ref.egenvekt 1"},
	{ L_WORD201 ,L"Velg API tabell"},
	{ L_WORD202 ,L"Pekerfeil!"},
	{ L_WORD203 ,L"Feil i verdi"},
	{ L_WORD204 ,L"Ukjent tank"},
	{ L_WORD205 ,L"AD ikke funnet"},
	{ L_WORD206 ,L"Ingen temp sensor"},
	{ L_WORD207 ,L"Verdi utenfor område"},
	{ L_WORD208 ,L"Bruk felles sjøvann"},
	{ L_WORD209 ,L"Bruk felles ballast"},
	{ L_WORD210 ,L"Lav temp = høy temp"},
	{ L_WORD211 ,L"Innsetting ulovelig"},
	{ L_WORD212 ,L"Udefinert last"},
	{ L_WORD213 ,L"Gjenta innsetting"},
	{ L_WORD214 ,L"Ref egenvekt 1 for lav"},
	{ L_WORD215 ,L"Ref egenvekt 1 for høy"},
	{ L_WORD216 ,L"Ref egenvekt 2 for lav"},
	{ L_WORD217 ,L"Ref egenvekt 2 for høy"},
	{ L_WORD218 ,L"API utenfor område"},
	{ L_WORD219 ,L"Følerfeil"},
	{ L_WORD220 ,L"Forst. utenfor område"},
	{ L_WORD221 ,L"Bruk felles ferskvann"},
	{ L_WORD222 ,L"Bruk felles tungolje"},
	{ L_WORD223 ,L"Bruk felles diesel"},
	{ L_WORD224 ,L"Bruk felles smørolje"},
	{ L_WORD225 ,L"Lav > høy grense"},
	{ L_WORD226 ,L"Høy < lav grense"},
	{ L_WORD227 ,L"Høy = lav grense"},
	{ L_WORD228 ,L"Ikke justerbar"},
	{ L_WORD229 ,L"Innsetting ulovelig"},
	{ L_WORD230 ,L"Sensor er koblet ut"},
	{ L_WORD231 ,L"Bruk API53 tabellen"},
	{ L_WORD232 ,L"Bruk API54 tabellen"},
	{ L_WORD233 ,L"Bruk ref. egenvekt 2"},
	{ L_WORD234 ,L"Ingen felles innsetting "},
	{ L_WORD235 ,L"Overstyring er kun mulig når det er alarm på enten Pre eller Main"},
	{ L_WORD236 ,L"Ingen enhet"},
	//{ L_WORD237 ,L""},
	{ L_WORD238 ,L"Lengde"},
	{ L_WORD239 ,L"Atm/gass trykk"},
	{ L_WORD240 ,L"Cargo / ballasttrykk"},
	{ L_WORD241 ,L"Linjetrykk"},
	{ L_WORD242 ,L"Egenvekts koeffisient"},
	{ L_WORD243 ,L"Vinkel"},
	{ L_WORD244 ,L"Fri veskeoverflate"},
	{ L_WORD245 ,L"Moment"},
	{ L_WORD246 ,L"Neddykking"},
	{ L_WORD247 ,L"Lastehastighet"},
	{ L_WORD248 ,L"Prosent"},
	{ L_WORD249 ,L"GZ areal"},
	{ L_WORD250 ,L"Strøm"},
	{ L_WORD251 ,L"Spenning"},
	{ L_WORD252 ,L"Tid"},
	{ L_WORD253 ,L"millisekunder"},
	{ L_WORD254 ,L"Dager"},
	{ L_WORD255 ,L"fot"},
	{ L_WORD256 ,L"d.fot"},
	//{ L_WORD257 ,L""},
	{ L_WORD258 ,L"liter"},
	//{ L_WORD259 ,L""},
	//{ L_WORD260 ,L""},
	//{ L_WORD261 ,L""},
	//{ L_WORD262 ,L""},
	//{ L_WORD263 ,L""},
	{ L_WORD264 ,L"m³/t"},
	{ L_WORD265 ,L"USb/t"},
	//{ L_WORD266 ,L""},
	//{ L_WORD267 ,L""},
	//{ L_WORD268 ,L""},
	//{ L_WORD269 ,L""},
	//{ L_WORD270 ,L""},
	//{ L_WORD271 ,L""},
	//{ L_WORD272 ,L""},
	//{ L_WORD273 ,L""},
	//{ L_WORD274 ,L""},
	//{ L_WORD275 ,L""},
	{ L_WORD276 ,L"t/m³ vakum"},
	{ L_WORD277 ,L"t/m³ luft"},
	//{ L_WORD278 ,L""},
	{ L_WORD279 ,L"Grad"},
	//{ L_WORD280 ,L""},
	//{ L_WORD281 ,L""},
	//{ L_WORD282 ,L""},
	//{ L_WORD283 ,L""},
	//{ L_WORD284 ,L""},
	//{ L_WORD285 ,L""},
	{ L_WORD286 ,L"Fot^4"},
	//{ L_WORD287 ,L""},
	//{ L_WORD288 ,L""},
	//{ L_WORD289 ,L""},
	//{ L_WORD290 ,L""},
	//{ L_WORD291 ,L""},
	//{ L_WORD292 ,L""},
	//{ L_WORD293 ,L""},
	//{ L_WORD294 ,L""},
	{ L_WORD295 ,L"mA"},
	{ L_WORD296 ,L"Amp"},
	{ L_WORD297 ,L"Volt"},
	{ L_WORD298 ,L"mVolt"},
	{ L_WORD299 ,L"mSek"},
	{ L_WORD300 ,L"Sek"},
	{ L_WORD301 ,L"Min"},
	{ L_WORD302 ,L"Timer"},
	{ L_WORD303 ,L"Dager"},
	{ L_WORD304 ,L"Ubrukt"},
	{ L_WORD305 ,L"Nivå@sens"},
	{ L_WORD306 ,L"Nivå@ref"},
	{ L_WORD307 ,L"Nivå@FS"},
	//{ L_WORD308 ,L""},
	//{ L_WORD309 ,L""},
	{ L_WORD310 ,L"Volum%"},
	{ L_WORD311 ,L"Trykk"},
	{ L_WORD312 ,L"Høyt trykk"},
	{ L_WORD313 ,L"Lavt trykk"},
	{ L_WORD314 ,L"Ferdigtid"},
	{ L_WORD315 ,L"Gjenstår"},
	{ L_WORD316 ,L"Lasttype"},
	{ L_WORD317 ,L"Bunntrykk"},
	{ L_WORD318 ,L"Midtrykk"},
	{ L_WORD319 ,L"Øvretrykk"},
	{ L_WORD320 ,L"Toptrykk"},
	{ L_WORD321 ,L"BP forst."},
	{ L_WORD322 ,L"MP forst."},
	{ L_WORD323 ,L"UP forst."},
	{ L_WORD324 ,L"TP forst."},
	{ L_WORD325 ,L"BP nullpunkt"},
	{ L_WORD326 ,L"MP nullpunkt"},
	{ L_WORD327 ,L"UP nullpunkt"},
	{ L_WORD328 ,L"TP nullpunkt"},
	{ L_WORD329 ,L"NivS"},
	{ L_WORD330 ,L"NivR"},
	{ L_WORD331 ,L"NivF"},
	//{ L_WORD332 ,L""},
	//{ L_WORD333 ,L""},
	//{ L_WORD334 ,L""},
	//{ L_WORD335 ,L""},
	{ L_WORD336 ,L"Vekt"},
	{ L_WORD337 ,L"Egev"},
	{ L_WORD338 ,L"Temp"},
	{ L_WORD339 ,L"Tryk"},
	{ L_WORD340 ,L"HTem"},
	{ L_WORD341 ,L"LTem"},
	{ L_WORD342 ,L"HøTr"},
	{ L_WORD343 ,L"LaTr"},
	{ L_WORD344 ,L"LHast"},
	{ L_WORD345 ,L"STid"},
	{ L_WORD346 ,L"GTid"},
	{ L_WORD347 ,L"LTyp"},
	//{ L_WORD348 ,L""},
	//{ L_WORD349 ,L""},
	//{ L_WORD350 ,L""},
	//{ L_WORD351 ,L""},
	{ L_WORD352 ,L"BPFo"},
	{ L_WORD353 ,L"MPFo"},
	{ L_WORD354 ,L"UPFo"},
	{ L_WORD355 ,L"TPFo"},
	{ L_WORD356 ,L"BPNu"},
	{ L_WORD357 ,L"MPNu"},
	{ L_WORD358 ,L"UPNu"},
	{ L_WORD359 ,L"TPNu"},
	{ L_WORD360 ,L"Bunntemp"},
	{ L_WORD361 ,L"Midttemp"},
	{ L_WORD362 ,L"Øvretemp"},
	{ L_WORD363 ,L"Toptemp"},
	//{ L_WORD364 ,L""},
	//{ L_WORD365 ,L""},
	//{ L_WORD366 ,L""},
	//{ L_WORD367 ,L""},
	//{ L_WORD368 ,L""},
	//{ L_WORD369 ,L""},
	//{ L_WORD370 ,L""},
	//{ L_WORD371 ,L""},
	//{ L_WORD372 ,L""},
	//{ L_WORD373 ,L""},
	//{ L_WORD374 ,L""},
	{ L_WORD375 ,L"Oppgavenavn"},
	{ L_WORD376 ,L"Oppetid"},
	//{ L_WORD377 ,L""},
	//{ L_WORD378 ,L""},
	{ L_WORD379 ,L"Kom. kanal"},
	{ L_WORD380 ,L"Kom. versjon"},
	{ L_WORD381 ,L"Lagringsversjon"},
	{ L_WORD382 ,L"RX størrelse"},
	{ L_WORD383 ,L"TX størrelse"},
	{ L_WORD384 ,L"Omstartstatus"},
	{ L_WORD385 ,L"Antall omstarter"},
	{ L_WORD386 ,L"Feilteller"},
	{ L_WORD387 ,L"Totalt feil"},
	//{ L_WORD388 ,L""},
	//{ L_WORD389 ,L""},
	{ L_WORD390 ,L"Serie nummer"},
	{ L_WORD391 ,L"Enhetsstatus"},
	{ L_WORD392 ,L"Kortstatus"},
	{ L_WORD393 ,L"Lastenavn"},
	{ L_WORD394 ,L"VolKorFaktor"},
	//{ L_WORD395 ,L""},
	{ L_WORD396 ,L"Målt API"},
	{ L_WORD397 ,L"Komp. egenvekt"},
	{ L_WORD398 ,L"Egenvekt 1"},
	{ L_WORD399 ,L"Egenvekt 2"},
	//{ L_WORD400 ,L""},
	//{ L_WORD401 ,L""},
	{ L_WORD402 ,L"Ikke definert"},
	{ L_WORD403 ,L"Enkel"},
	{ L_WORD404 ,L"Atm. trykk"},
	//{ L_WORD405 ,L""},
	{ L_WORD406 ,L"Tungolje"},
	//{ L_WORD407 ,L""},
	{ L_WORD408 ,L"Smøreolje"},
	{ L_WORD409 ,L"Ferskvann"},
	{ L_WORD410 ,L"Sjøvann"},
	//{ L_WORD411 ,L""},
	//{ L_WORD412 ,L""},
	//{ L_WORD413 ,L""},
	//{ L_WORD414 ,L""},
	//{ L_WORD415 ,L""},
	//{ L_WORD416 ,L""},
	//{ L_WORD417 ,L""},
	//{ L_WORD418 ,L""},
	//{ L_WORD419 ,L""},
	//{ L_WORD420 ,L""},
	//{ L_WORD421 ,L""},
	//{ L_WORD422 ,L""},
	//{ L_WORD423 ,L""},
	{ L_WORD677 ,L"Nivå"},
	{ L_WORD425 ,L"Trim i grader"},
	{ L_WORD426 ,L"Trim i meter"},
	{ L_WORD427 ,L"List i grader"},
	{ L_WORD428 ,L"DF (brukervalg)"},
	{ L_WORD429 ,L"DA (Brukervalg)"},
	{ L_WORD430 ,L"DF@Merke"},
	{ L_WORD431 ,L"DA@Merke"},
	//{ L_WORD432 ,L""},
	//{ L_WORD433 ,L""},
	{ L_WORD434 ,L"På/Av"},
	{ L_WORD435 ,L"Systemdata"},
	{ L_WORD436 ,L"Dypgående"},
	//{ L_WORD437 ,L""},
	{ L_WORD438 ,L"Andre tanker"},
	//{ L_WORD439 ,L""},
	//{ L_WORD440 ,L""},
	//{ L_WORD441 ,L""},
	//{ L_WORD442 ,L""},
	//{ L_WORD443 ,L""},
	//{ L_WORD444 ,L""},
	{ L_WORD445 ,L"Nivå"},
	{ L_WORD446 ,L"Målt egenvekt"},
	{ L_WORD447 ,L"List i meter"},
	{ L_WORD448 ,L"Breddegrad"},
	//{ L_WORD449 ,L""},
	//{ L_WORD450 ,L""},
	{ L_WORD451 ,L"Plassering"},
	{ L_WORD452 ,L"Min område"},
	{ L_WORD453 ,L"Max område"},
	{ L_WORD454 ,L"Kabellengde"},
	{ L_WORD455 ,L"TCUadresse"},
	{ L_WORD456 ,L"Port"},
	{ L_WORD457 ,L"IOadresse"},
	{ L_WORD458 ,L"Kanal"},
	{ L_WORD459 ,L"ADkort kanal"},
	{ L_WORD460 ,L"Trim"},
	{ L_WORD461 ,L"List"},
	{ L_WORD462 ,L"Sort"},
	{ L_WORD463 ,L"Mørk grå"},
	{ L_WORD464 ,L"Lys grå"},
	{ L_WORD465 ,L"Hvit"},
	{ L_WORD466 ,L"Blå"},
	{ L_WORD467 ,L"Skriv ut"},
	//{ L_WORD468 ,L""},
	{ L_WORD469 ,L"Bruk bls"},
	{ L_WORD470 ,L"Bruk m³"},
	{ L_WORD471 ,L"Tørr"},
	//{ L_WORD472 ,L""},
	{ L_WORD473 ,L"Tom"},
	//{ L_WORD474 ,L""},
	//{ L_WORD475 ,L""},
	//{ L_WORD476 ,L""},
	//{ L_WORD477 ,L""},
	//{ L_WORD478 ,L""},
	{ L_WORD479 ,L"Kom"},
	//{ L_WORD480 ,L""},
	{ L_WORD481 ,L"på TCU:"},
	{ L_WORD482 ,L"på ZB485"},
	//{ L_WORD483 ,L""},
	{ L_WORD484 ,L"Applikasjon"},
	{ L_WORD485 ,L"Ukjent"},
	{ L_WORD486 ,L"Ingen"},
	{ L_WORD487 ,L"Feil"},
	{ L_WORD488 ,L"Ubru"},
	{ L_WORD489 ,L"Andre"},
	{ L_WORD490 ,L"Trykk"},
	//{ L_WORD491 ,L""},
	{ L_WORD492 ,L"@Merke"},
	{ L_WORD493 ,L"Deakt."},
	{ L_WORD494 ,L"Aktiv"},
	{ L_WORD495 ,L"Bekr."},
	{ L_WORD496 ,L"Gr.:"},
	{ L_WORD497 ,L"Ver:"},
	{ L_WORD498 ,L"Peker feil"},
	{ L_WORD499 ,L"Ukj."},
	{ L_WORD500 ,L"Utenfor omr."},
	{ L_WORD501 ,L"Kom feil"},
	{ L_WORD502 ,L"HNiv"},
	{ L_WORD503 ,L"Høynivå"},
	{ L_WORD504 ,L"Høyt linjetrykk"},
	{ L_WORD505 ,L"HLTr"},
	{ L_WORD506 ,L"Høyt trykk"},
	{ L_WORD507 ,L"HTry"},
	{ L_WORD508 ,L"Høy temp"},
	{ L_WORD509 ,L"HTmp"},
	{ L_WORD510 ,L"Høy spenning"},
	{ L_WORD511 ,L"HSpen"},
	{ L_WORD512 ,L"Høyt trykk1"},
	{ L_WORD513 ,L"HTr1"},
	{ L_WORD514 ,L"Lavt trykk1"},
	{ L_WORD515 ,L"LTr1"},
	{ L_WORD516 ,L"Kom feil"},
	{ L_WORD517 ,L"IOFei"},
	{ L_WORD518 ,L"Lavt nivå"},
	{ L_WORD519 ,L"LNiv"},
	{ L_WORD520 ,L"Lavt linjetrykk"},
	{ L_WORD521 ,L"LLTr"},
	{ L_WORD522 ,L"Lavt trykk"},
	{ L_WORD523 ,L"LTry"},
	{ L_WORD524 ,L"Lav temp"},
	{ L_WORD525 ,L"LTmp"},
	{ L_WORD526 ,L"Lav spenning"},
	{ L_WORD527 ,L"LSpen"},
	{ L_WORD528 ,L"Feil"},
	{ L_WORD529 ,L"Main vann"},
	{ L_WORD530 ,L"MVann"},
	{ L_WORD531 ,L"Åpen krets"},
	{ L_WORD532 ,L"åkret"},
   // { L_WORD109 ,L"Overfylling"},
	{ L_WORD534 ,L"OvFy"},
	{ L_WORD535 ,L"Pre vann"},
	{ L_WORD536 ,L"PVann"},
	{ L_WORD537 ,L"Utenfor område"},
	{ L_WORD538 ,L"ADFei"},
	{ L_WORD539 ,L"Kon&Kal feil"},
	{ L_WORD540 ,L"HWFe"},
	{ L_WORD541 ,L"Konvert feil"},
	{ L_WORD542 ,L"OmrF"},
	{ L_WORD543 ,L"Kortslutning"},
	{ L_WORD544 ,L"Kslu"},
	{ L_WORD545 ,L"Detaljer"},
	{ L_WORD546 ,L"Kalibreringsdata"},
	{ L_WORD547 ,L"SerNum"},
	{ L_WORD548 ,L"Område"},
	{ L_WORD549 ,L"KalData kilde"},
	{ L_WORD550 ,L"Nivåjustering"},
	{ L_WORD551 ,L"Vinkelmåler"},
	{ L_WORD552 ,L"Dypgående"},
	{ L_WORD553 ,L"Målt"},
	//{ L_WORD554 ,L""},
	//{ L_WORD555 ,L""},
	{ L_WORD556 ,L"RåVerdi"},
	{ L_WORD557 ,L"KalVerdi"},
	{ L_WORD558 ,L"KnvKalF"},
	//{ L_WORD559 ,L""},
	//{ L_WORD560 ,L""},
	{ L_WORD561 ,L"TCUkal"},
	{ L_WORD562 ,L"AD føl"},
	{ L_WORD563 ,L"TCU føl"},
	{ L_WORD564 ,L"Fra TCU"},
	{ L_WORD565 ,L"Grønn"},
	{ L_WORD566 ,L"Sletter FLASH"},
	{ L_WORD567 ,L"Opplysning"},
	{ L_WORD568 ,L"Sletting feilet"},
	{ L_WORD569 ,L"Oppdaterer program, vennligst vent..."},
	{ L_WORD570 ,L"Touch screen kalibreting.\n Trykk midt i ringen"},
	{ L_WORD571 ,L"Avbryt"},
	{ L_WORD572 ,L"Trykk her"},
	{ L_WORD573 ,L"(Øvre venstre hjørne)"},
	{ L_WORD574 ,L"(Nedre høyre hjørne)"},
	{ L_WORD575 ,L"Side"},
	{ L_WORD576 ,L"Dataversjon"},
	{ L_WORD577 ,L"Lastetanker"},
	{ L_WORD578 ,L"Ballasttanker"},
	{ L_WORD579 ,L"Servicetanker"},
	{ L_WORD580 ,L"Tungoljetanker"},
	{ L_WORD581 ,L"Dieseloljetanker"},
	{ L_WORD582 ,L"Smøreoljetanker"},
	{ L_WORD583 ,L"Diverse tanker"},
	{ L_WORD584 ,L"Ferskvannstanker"},
	{ L_WORD585 ,L"IkkeDef"},
	//{ L_WORD586 ,L""},
	{ L_WORD587 ,L"Bunn"},
	{ L_WORD588 ,L"Midt"},
	{ L_WORD589 ,L"Øvre"},
	{ L_WORD590 ,L"TnkTrykk"},
	//{ L_WORD591 ,L""},
	//{ L_WORD592 ,L""},
	//{ L_WORD593 ,L""},
	//{ L_WORD594 ,L""},
	//{ L_WORD595 ,L""},
	//{ L_WORD596 ,L""},
	//{ L_WORD597 ,L""},
	//{ L_WORD598 ,L""},
	//{ L_WORD599 ,L""},
	//{ L_WORD600 ,L""},
	//{ L_WORD601 ,L""},
	{ L_WORD602 ,L"Nulljuster tanktrykk!"},
	{ L_WORD603 ,L"Tanken må være luftet til atmosfære. Dette innvirker på alle tanker i gruppen."},
	{ L_WORD604 ,L"Nulljuster føler(e)!"},
	{ L_WORD605 ,L"Tankene må være tomme og ikke vasket på 30 minutter. Dette innvirker på alle tanker i gruppen."},
	{ L_WORD606 ,L"Nulljustering advarsell:"},
	{ L_WORD607 ,L"Tankene må være luftet til atmosfære. Dette innvirker på alle tanktrykkpunktene i gruppen"},
	{ L_WORD608 ,L"Tankene må være tomme og ikke vært vasket på 30 minutter. Dette innvirker på alle tanktrykkpunktene i gruppen"},
	{ L_WORD609 ,L"Tungolje egenvekt"},
	{ L_WORD610 ,L"Diesel egenvekt"},
	{ L_WORD611 ,L"Smørolje egenvekt"},
	{ L_WORD612 ,L"Ferskvann egenvekt"},
	{ L_WORD613 ,L"Fil kuttet!"},
	{ L_WORD614 ,L"Feil i UNICODE!"},
	//{ L_WORD615 ,L""},
	//{ L_WORD616 ,L""},
	{ L_WORD617 ,L"B "},
	//{ L_WORD618 ,L""},
	{ L_WORD619 ,L"Plan"},
	{ L_WORD620 ,L"Skriver på TDU"},
	{ L_WORD621 ,L"Temperaturer"},
	{ L_WORD622 ,L"Linjetrykk"},
	{ L_WORD623 ,L"Tanktrykk"},
	//{ L_WORD624 ,L""},
	//{ L_WORD625 ,L""},
	//{ L_WORD626 ,L""},
	//{ L_WORD627 ,L""},
	//{ L_WORD628 ,L""},
	//{ L_WORD629 ,L""},
	//{ L_WORD630 ,L""},
	//{ L_WORD631 ,L""},
	//{ L_WORD632 ,L""},
	//{ L_WORD633 ,L""},
	//{ L_WORD634 ,L""},
	//{ L_WORD635 ,L""},
	//{ L_WORD636 ,L""},
	//{ L_WORD637 ,L""},
	//{ L_WORD638 ,L""},
	//{ L_WORD639 ,L""},
	//{ L_WORD640 ,L""},
	//{ L_WORD641 ,L""},
	//{ L_WORD642 ,L""},
	//{ L_WORD643 ,L""},
	//{ L_WORD644 ,L""},
	//{ L_WORD645 ,L""},
	//{ L_WORD646 ,L""},
	//{ L_WORD647 ,L""},
	//{ L_WORD648 ,L""},
	//{ L_WORD649 ,L""},
	//{ L_WORD650 ,L""} ,
};

unsigned WordsInNorwegianDictionary = NELEMENTS(NorwegianDictionary);
wchar_t NorwegianUserManual[] = {L"           Brukermanual for TDU\n\
\n\
Les INSTALATION, INSTRUCTION AND OPERATION MANUALen for å få full oversikt of forståelse for systemet\n\
\n\
Skjermen skal opereres med en egnet penn eller fingertuppen. Annet utstyr / penner vil ødelegge skjermen.\n\
\n\
NOTE:\n\
Les og forstå innholdet i INSTRUCTION AND OPERATION MANUAL.\n\
\n\
Det er NØDVENDIG å kjenne konsekvensene av feil bruk av egenvekt, sette feil alarmgrenser, slå av alarmer eller justere sensorparametere.\n\
Hvis dette gjøres feil kan det resultere i skader og/eller overlasting.\n\
\n\
Brukermanual og reservedeler kan bestiller fra:\n\
\n\
Scanjet Ariston AS\n\
Dokkvegen 10\n\
3920 Porsgrunn\n\
Norway \n\
\n\
Tel: +47 35 93 11 30\n\
Service: +47 958 78 644\n\
Fax: +47 35 93 11 31\n\
E-mail: service@ariston.no\n\
Web: www.ariston.no\n\
"};
int SizeOfNorwegianUserManual= sizeof(NorwegianUserManual);


